### ISSUE TITLE
Stop using ORM

### ISSUE THREAD

**Issue by jd** [gnocchixyz/gnocchi#10]
https://bugs.launchpad.net/gnocchi/+bug/1626618

**Comment by chungg** [comment]
i should probably mention, if i didn't before, i never verified this. based on workflow i don't think it's a massive amount of overhead.

**Comment by BigChief45** [comment]
Maybe we could do some benchmarks using different ORMs? I thought the days of writing SQL directly were over. Excuse my ignorance...

**Comment by jd** [comment]
There's no abstraction layer that covers everything that SQL could do, especially using advanced RDBMS. ORM are great for rapid prototyping or simple apps, but then limitation and perf starts kick in.
Though to be honest, I don't think we do anything fancy with RDBMS so the ORM is not limiting us in anyway for now. :)

**Comment by jd** [comment]
As there's no plan for this and it's clearly not a blocker but just an idea, I'm gonna close it.
