### ISSUE TITLE
How to configure ceilometer and gnocchi to adapt different measurement interval for different vm

### ISSUE THREAD

**Issue by gujun4990** [gnocchixyz/gnocchi#1005]
Hello, I want to ask a question about ceilometer and gnocchi. The situation is like this: I want to realize a requirement that different virtual machines use different measures interval. For example, I have three virtual machines( vm1, vm2 and vm3 ). The measurement interval is 300s for vm1 and vm2, but it is 180s for vm3. I want to realize the goal that the different virtual machines use different archive_policy (different granularity). But I found ceilometer doesn't support the function setting different archive_policy. So I want to know whether gnocchi can support the operation.
BTW: The version of gnocchi is 4.0.2.

**Comment by chungg** [comment]
i can't remember if this is possible with Ceilometer. i doubt it though.

i imagine you could either:
- create a policy with both intervals.
- create a policy using common multiple and resample up to what you require... like create a policy of 60s, and resample to 300s or 180s as required.

**Comment by gujun4990** [comment]
I have tried your method and it works for me. Thank you.
