### ISSUE TITLE
Grafana plugin fails to install

### ISSUE THREAD

**Issue by paaguti** [gnocchixyz/gnocchi#1006]
Before reporting an issue on Gnocchi, please be sure to provide all necessary
information.

### Which version of Gnocchi are you using
master on devstack stable/queens

### How to reproduce your problem
Add enable_service to activate grafana

### What is the result that you get
./stack.sh crashes

### What is result that you expected
Working devstack

I just want to know which _stable_ version I should install on my devstack release stable/queens.

Thanks, /PA

PS: The end of the crash log:
```
--2018-11-16 10:42:31--  https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana_4.3.1_amd64.deb
Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 52.218.248.232
Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|52.218.248.232|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 47222394 (45M) [application/x-debian-package]
Saving to: ‘/tmp/grafanapkg-SbYJa’

/tmp/grafanapkg-SbY 100%[===================>]  45.03M  2.14MB/s    in 13s

2018-11-16 10:42:45 (3.46 MB/s) - ‘/tmp/grafanapkg-SbYJa’ saved [47222394/47222394]

(Reading database ... 83963 files and directories currently installed.)
Preparing to unpack /tmp/grafanapkg-SbYJa ...
Unpacking grafana (4.3.1) over (4.3.1) ...
Setting up grafana (4.3.1) ...
Restarting grafana-server service... OK
Processing triggers for systemd (229-4ubuntu21.8) ...
Processing triggers for ureadahead (0.100.0-19) ...
ureadahead will be reprofiled on next reboot
installing gnocchixyz-gnocchi-datasource @ 1.7.0
from url: https://grafana.com/api/plugins/gnocchixyz-gnocchi-datasource/versions/1.7.0/download
into: /var/lib/grafana/plugins

Failed downloading. Will retry once.
Failed downloading. Will retry once.

Error: ✗ Corrupt http response from source. Please try again.

```

**Comment by tobias-urdin** [comment]
Please provide more information and we can investigate further, until then closed.

**Comment by paaguti** [comment]
Sorry, but do you want me to remember a problem I had more than three years ago? ;-) 
With all that has happened in this time, I hope you forgive me if I don't...

**Comment by tobias-urdin** [comment]
I'm just cleaning backlog, I don't expect anything from you :) But if you are still having an issue I would like to know about it.
