### ISSUE TITLE
Help 'manually' populating Gnocchi

### ISSUE THREAD

**Issue by Smiliebg** [gnocchixyz/gnocchi#1008]
### Which version of Gnocchi are you using
root@gnocchi:~# gnocchi server version
+---------+-------+
| Field   | Value |
+---------+-------+
| version | 4.3.2 |
+---------+-------+

I need to evaluate an approach querying Gnocchi data received by Ceilometer. However, I do not currently have any OpenStack installation running that would feed Gnocchi. Additionally, I have managed to figure to some extend data that Ceilometer should be sending - but am concerned I might miss some crucial piece of key/pair value of attributes.

Could anyone provide me with (anonymous or randomly generated) data for ceilometer?

I am using MySQL as indexer and file as storage.

Or if anyone has like a script to feed valid Ceilometer data, that would be perfect :)

Thanks!

**Comment by sileht** [comment]
We don't have such data there. You should can use devstack to quickly setup an Openstack installation.
