### ISSUE TITLE
resampling got minus samples for rate:mean aggregation method

### ISSUE THREAD

**Issue by mslovy** [gnocchixyz/gnocchi#1009]
I use rate:mean policy rules for metric cpu with 1minutes,30 days. When I get the metric with granularity 60, everything goes well. However when I setting resemble=600, I got lots of minus samples, but all cpu samples should be positive.

**Comment by mslovy** [comment]
I don’t think it related to the vm restart, it might be related to the resample for rate:xxx, because when I retrive data from cpu mean, not rate:mean,with a resample 600. No negative data i got.

**Comment by mslovy** [comment]
normal for rate:mean
[root@control1 ~]# openstack metric measures show b49886db-bcdd-43ad-bfb2-26f4ddd6a787 --aggregation rate:mean --granularity 60
+---------------------------+-------------+--------------+
| timestamp                 | granularity |        value |
+---------------------------+-------------+--------------+
| 2018-12-16T15:11:00+08:00 |        60.0 | 5460000000.0 |
| 2018-12-16T15:12:00+08:00 |        60.0 |   50000000.0 |
| 2018-12-16T15:13:00+08:00 |        60.0 |  382500000.0 |
| 2018-12-16T15:14:00+08:00 |        60.0 |   47500000.0 |
| 2018-12-16T15:15:00+08:00 |        60.0 |   40000000.0 |
| 2018-12-16T15:16:00+08:00 |        60.0 |   22500000.0 |
| 2018-12-16T15:17:00+08:00 |        60.0 |   22500000.0 |
| 2018-12-16T15:18:00+08:00 |        60.0 |   20000000.0 |
| 2018-12-16T15:19:00+08:00 |        60.0 |   20000000.0 |
| 2018-12-16T15:20:00+08:00 |        60.0 |   22500000.0 |
| 2018-12-16T15:21:00+08:00 |        60.0 |   17500000.0 |
| 2018-12-16T15:22:00+08:00 |        60.0 |   12500000.0 |
| 2018-12-16T15:23:00+08:00 |        60.0 |   12500000.0 |
| 2018-12-16T15:24:00+08:00 |        60.0 |   10000000.0 |
| 2018-12-16T15:25:00+08:00 |        60.0 |   12500000.0 |
| 2018-12-16T15:26:00+08:00 |        60.0 |   15000000.0 |
| 2018-12-16T15:27:00+08:00 |        60.0 |   17500000.0 |
| 2018-12-16T15:28:00+08:00 |        60.0 |   30000000.0 |
+---------------------------+-------------+--------------+

resample for rate:mean —— **seems the result is unexpected**
the vm is keeping running during this period
[root@control1 ~]# openstack metric measures show b49886db-bcdd-43ad-bfb2-26f4ddd6a787 --aggregation rate:mean --granularity 60 --resample 120
+---------------------------+-------------+---------------+
| timestamp                 | granularity |         value |
+---------------------------+-------------+---------------+
| 2018-12-16T15:12:00+08:00 |       120.0 | -2538750000.0 |
| 2018-12-16T15:14:00+08:00 |       120.0 |  -171250000.0 |
| 2018-12-16T15:16:00+08:00 |       120.0 |    -8750000.0 |
| 2018-12-16T15:18:00+08:00 |       120.0 |    -1250000.0 |
| 2018-12-16T15:20:00+08:00 |       120.0 |    -1250000.0 |
| 2018-12-16T15:22:00+08:00 |       120.0 |    -2500000.0 |
| 2018-12-16T15:24:00+08:00 |       120.0 |           0.0 |
| 2018-12-16T15:26:00+08:00 |       120.0 |    -1250000.0 |
+---------------------------+-------------+---------------+

normal for mean
[root@control1 ~]# openstack metric measures show b49886db-bcdd-43ad-bfb2-26f4ddd6a787 --aggregation mean --granularity 60
+---------------------------+-------------+---------------+
| timestamp                 | granularity |         value |
+---------------------------+-------------+---------------+
| 2018-12-16T15:11:00+08:00 |        60.0 | 6406666666.67 |
| 2018-12-16T15:12:00+08:00 |        60.0 | 11040000000.0 |
| 2018-12-16T15:13:00+08:00 |        60.0 | 11922500000.0 |
| 2018-12-16T15:14:00+08:00 |        60.0 | 12775000000.0 |
| 2018-12-16T15:15:00+08:00 |        60.0 | 12950000000.0 |
| 2018-12-16T15:16:00+08:00 |        60.0 | 13057500000.0 |
| 2018-12-16T15:17:00+08:00 |        60.0 | 13142500000.0 |
| 2018-12-16T15:18:00+08:00 |        60.0 | 13225000000.0 |
| 2018-12-16T15:19:00+08:00 |        60.0 | 13315000000.0 |
| 2018-12-16T15:20:00+08:00 |        60.0 | 13397500000.0 |
| 2018-12-16T15:21:00+08:00 |        60.0 | 13477500000.0 |
| 2018-12-16T15:22:00+08:00 |        60.0 | 13532500000.0 |
| 2018-12-16T15:23:00+08:00 |        60.0 | 13577500000.0 |
| 2018-12-16T15:24:00+08:00 |        60.0 | 13625000000.0 |
| 2018-12-16T15:25:00+08:00 |        60.0 | 13672500000.0 |
| 2018-12-16T15:26:00+08:00 |        60.0 | 13720000000.0 |
| 2018-12-16T15:27:00+08:00 |        60.0 | 13782500000.0 |
| 2018-12-16T15:28:00+08:00 |        60.0 | 13885000000.0 |
| 2018-12-16T15:29:00+08:00 |        60.0 | 13915000000.0 |
+---------------------------+-------------+---------------+

Resample for mean —— **seems the result is expected**
[root@control1 ~]# openstack metric measures show b49886db-bcdd-43ad-bfb2-26f4ddd6a787 --aggregation mean --granularity 60 --resample 120
+---------------------------+-------------+---------------+
| timestamp                 | granularity |         value |
+---------------------------+-------------+---------------+
| 2018-12-16T15:10:00+08:00 |       120.0 | 6406666666.67 |
| 2018-12-16T15:12:00+08:00 |       120.0 | 11481250000.0 |
| 2018-12-16T15:14:00+08:00 |       120.0 | 12862500000.0 |
| 2018-12-16T15:16:00+08:00 |       120.0 | 13100000000.0 |
| 2018-12-16T15:18:00+08:00 |       120.0 | 13270000000.0 |
| 2018-12-16T15:20:00+08:00 |       120.0 | 13437500000.0 |
| 2018-12-16T15:22:00+08:00 |       120.0 | 13555000000.0 |
| 2018-12-16T15:24:00+08:00 |       120.0 | 13648750000.0 |
| 2018-12-16T15:26:00+08:00 |       120.0 | 13751250000.0 |
| 2018-12-16T15:28:00+08:00 |       120.0 | 13885000000.0 |
+---------------------------+-------------+---------------+

**Comment by sileht** [comment]
You are using `--aggregation rate:mean --granularity 60 --resample 120`, so you ask Gnocchi to do the `rate:mean(120)` of the `rate:mean(60)`.

The result is the expected result for this operation as it computes the `rate` of the `rate`.

Like many other math operations, resampling a `rate:XXX` doesn't make sense.

**Comment by mslovy** [comment]
so  how to resample the rate metric or currently these is no way to do that ? @sileht

**Comment by sileht** [comment]
You can do the resample then the rate  on the fly with the dynamic aggregate API over your uptime mean aggregate.
https://gnocchi.xyz/rest.html#dynamic-aggregates
