### ISSUE TITLE
Devstack Queens, which version of gnocchi do I need

### ISSUE THREAD

**Issue by vofish** [gnocchixyz/gnocchi#1011]
Before reporting an issue on Gnocchi, please be sure to provide all necessary
information.

### Which version of Gnocchi are you using
origin/stable/4.1

I'm using Devstack Queens (origin/stable/queens) with gnocchi (origin/stable/4.1).
What is recommended version of gnocchi for Queens?

**Comment by chungg** [comment]
i don't believe the api has changed since 4.0 so the latest version (4.3) would be recommended. but since it's devstack you'll probably have to consider if the requirements conflict or not.

**Comment by vofish** [comment]
Thanks for your answer, Gord.
Is it OK to use version 4.1 with Queens?

**Comment by chungg** [comment]
i don't actively contribute to openstack anymore so i'm not sure what cycle Queens is but i believe so. Gnocchi 4.1 should work with anything Ocata onwards
