### ISSUE TITLE
 Keystone failure: No response status code, is CORS correctly configured ? error 

### ISSUE THREAD

**Issue by universcom** [gnocchixyz/gnocchi#1014]
Hello 
i read all things about error in this page.
i user queens openstack an gnocchi and we want visualize gnocchi by grafana

**Comment by universcom** [comment]
![gnocchi](https://user-images.githubusercontent.com/32667017/51398167-1c74cf00-1b58-11e9-8b9f-94a0fcba05df.png)

**Comment by GibeomOh** [comment]
Did you specify value of allowed_origin of the cors section in gnocchi.conf?

**Comment by tobias-urdin** [comment]
Please provide more information and we can investigate further, until then closed.
