### ISSUE TITLE
Division by zero incorrect JSON

### ISSUE THREAD

**Issue by yavi** [gnocchixyz/gnocchi#1023]
"Infinity" result caused by division by zero should either return an error or be quoted.

### Which version of Gnocchi are you using
4.3.1dev28
### How to reproduce your problem
Cause a division by zero in dynamic aggregate by using "/" operator with a metric that has measures of value 0 as second argument.

### What is the result that you get
JSON with unquoted "Infinity"

### What is result that you expected
An error or JSON with "Infinity" correctly quoted (or changed to NaN and quoted?).

**Comment by chungg** [comment]
can you provide the json result verbatim and possibly the POST and/or client request? just so we address the correct issue. thanks

**Comment by yavi** [comment]
The POST (simplified by directly using 0 instead of a metric that returns 0)

```JSON
{
  "operations": "(/ (* 100 ( aggregate mean (metric memory.usage mean))) 0 )",
	"resource_type": "instance",
	"search": {
		"=": {
			"project_id": "88cf6fffd770455c83097b604eef2c92"
		}
	}
}
```

Returns:
```
{
  "measures": {
    "aggregated": [
      [
        "2019-05-23T10:20:00+00:00",
        300.0,
        Infinity
      ],
      [
        "2019-05-23T10:25:00+00:00",
        300.0,
        Infinity
      ],
      [
        "2019-05-23T10:30:00+00:00",
        300.0,
        Infinity
      ],
      [
        "2019-05-23T10:35:00+00:00",
        300.0,
        Infinity
      ],
      [
        "2019-05-23T10:40:00+00:00",
        300.0,
        Infinity
      ],
      [
        "2019-05-23T10:45:00+00:00",
        300.0,
        Infinity
      ]
    ]
  }
}
```

Either Infinity should be quoted or there should be a division by zero error.

On a side note - is there a way to consistently prevent division by zero? Usually I would just max(metric,1), but there is no 'max' operator, just aggregator - and aggregators do not accept numbers, only metrics.

**Comment by chungg** [comment]
thanks for details. will try to look at this if no one else gets around to it.

with regards to solution, is there a strong preference for `"Infinity"` or error? I'm wondering if it's better to just do what AWS does and drop the datapoint. alternatively, we can pull `null` so it fits json standards. or something else?

hmm... if you're ok the series will always be positive you can use clip[1] to set a lower bound.

[1] https://github.com/gnocchixyz/gnocchi/blob/master/doc/source/rest.j2#L912-L914

**Comment by yavi** [comment]
* dropping values is a case of failing silently, not intuitive and kind of hard to debug/notice
* quoted infinity will probably need patching in consumers to not return errors
* a null should be well understood by existing consumers 
* an error immediately points out the issue, as division by zero is one, and nulls will usually still mess up your result.

I'd personally opt for either null or an error, can't really say what is best. Dropping values would be the best but only if we had a way of putting a warning in response (result + warnings: data points were dropped due to division by zero) so we know what happened.
