### ISSUE TITLE
how to store weekly data on gnocchi

### ISSUE THREAD

**Issue by RameshChowdeshetty** [gnocchixyz/gnocchi#1024]
i have created an archive policy is as follows,

{
        "definition": [
            {
                "granularity": "7 days, 0:00:00",
                "points": 14285,
                "timespan": "99995 days, 0:00:00"
            }
        ],
        "name": "week_policy",
        "back_window": 1000000,
        "aggregation_methods": [
            "sum",
            "std",
            "mean",
            "count",
            "max",
            "min"
        ]
    }

then i am inserting below measures into a metric which is created with above policy

[
{"timestamp": "2000-05-15", "value": 10930.639648}, 
{"timestamp": "2000-05-22", "value": 10624.790039}, 
{"timestamp": "2000-05-29", "value": 10302.30957}, 
{"timestamp": "2000-06-05", "value": 10793.110352}, 
{"timestamp": "2000-06-12", "value": 10615.120117}, 
{"timestamp": "2000-06-19", "value": 10448.400391}, 
{"timestamp": "2000-06-26", "value": 10403.69043}, 
{"timestamp": "2000-07-03", "value": 10450.360352}, 
{"timestamp": "2000-07-10", "value": 10627.139648}, 
{"timestamp": "2000-07-17", "value": 10812.400391}, 
{"timestamp": "2000-07-24", "value": 10731.44043}, 
{"timestamp": "2000-07-31", "value": 10514.290039}
]

after insert it is showing 202 status code but when i try to get the measures it is returning empty. Is this the correct way of storing weekly data  ? .Can somebody help me to sort out this issue.

**Comment by chungg** [comment]
gnocchi processes data asynchronously so depending on your configuration it's possible that the data you inserted has yet to be processed. you can figure this out by checking the `/v1/status` endpoint or the equivalent client command. you can configure the processing rate through a combination of setting `metric_processing_delay` and `workers`. more details can be found in the docs: https://gnocchi.xyz/operating.html#metricd

if there's no backlog, then can you provide more details on your POST and GET requests

that said, i don't suggest archive policies with large granularities unless the frequency of your data is also large or else you will run into scaling issues. gnocchi provides ability to aggregate on request: https://gnocchi.xyz/rest.html#resample.

**Comment by RameshChowdeshetty** [comment]
i am just inserting the above 13 measures. but it is not reading. I have a requirement that i will be getting weekly data directly to me so i can't use resample. I just need to store the weekly data , please let me no the exact way to store weekly data.
