### ISSUE TITLE
4.2.6 and 4.3.3 are not on PyPI

### ISSUE THREAD

**Issue by lukapeschke** [gnocchixyz/gnocchi#1025]
The `stable/4.2` and `stable/4.3` branches have some useful patches which aren't part of any release, like https://github.com/gnocchixyz/gnocchi/commit/c531da6ac555c0dd8936eecd27de2ab8ccb633ee and https://github.com/gnocchixyz/gnocchi/commit/81173aa212c737bb04707a22ba24ed1bc3c252af . However, some projects, like kolla-ansible, use the latest release of `stable/4.3` by default, instead of the tip of the branch. Making a new release on the `stable/4.3` and `stable/4.2` branches would be helpful, as people might be afraid to deploy from the tip of a branch, event if it is marked as stable.

**Comment by jd** [comment]
You're right, I'll try to make a release soonish.

**Comment by lukapeschke** [comment]
Awesome, thanks!

**Comment by jd** [comment]
I've pushed the `git tags`, but releasing on PyPI seems broken for various reasons. I don't have time to dig into that, but whoever wants is free to do. I'll retitle just for tracking the issue.

**Comment by lukapeschke** [comment]
Thanks @jd . I can't find the PyPI build logs, could you please point to that ?

**Comment by jd** [comment]
Deploy is done by Travis, you can look at the log at least here https://travis-ci.org/gnocchixyz/gnocchi/jobs/535794086 and maybe in some other jobs — I think they all try to release :(

**Comment by lukapeschke** [comment]
Thanks @chungg! Should https://github.com/gnocchixyz/gnocchi/commit/d12a3fb53651aefc51e3d05e07151ac5ac53d14e be backported to stable/4.2 and stable/4.3 ?

**Comment by chungg** [comment]
apologies, i don't have time to backport to 4.2.6 as it requires fixing 4.1 and earlier due upgrade tests. it's fixed in 4.3 so that hopefully is fixed.

**Comment by lukapeschke** [comment]
Thanks for your work @chungg ! Should your last commit be tagged as 4.3.4 in order to trigger a release and a push to pypi ? (I'm not very familiar with pypi)

**Comment by chungg** [comment]
sigh. another error. this is the bane of my existence. :( i'll take a look but for reference the error is below.

https://travis-ci.org/gnocchixyz/gnocchi/jobs/565266273#L496

**Comment by lukapeschke** [comment]
Is the error caused by the six version conflict here https://travis-ci.org/gnocchixyz/gnocchi/jobs/565266273#L623 ? Do you have an idea why bleach is installed ? It doesn't seem to be pulled by any of gnocchi's dependencies

**Comment by chungg** [comment]
it's part of twine which travis uses to deploy to pypi i believe. not sure why it's being stupid and not installing correct version. possibly something to do with our ci image.

**Comment by jd** [comment]
Yes, `six` to be installed system-wide and `pip` is not called with the `--upgrade` switch by Travis when installing `twine`. That's likely why it fails. :(

**Comment by chungg** [comment]
we've released 4.3.4. let us know if you have issue. i'll try addressing things on 4.3+.

**Comment by lukapeschke** [comment]
Perfect, thanks a lot guys!
