### ISSUE TITLE
How to put constant value to ceilometer resource attribute

### ISSUE THREAD

**Issue by m0zart89** [gnocchixyz/gnocchi#1026]
Before reporting an issue on Gnocchi, please be sure to provide all necessary
information.

### Which version of Gnocchi are you using
gnocchi 4.2.5

Hello, community!

I have openstack with several regions: US1, EU1. I have resource "instance_network_interface" with my custom attribute "region_id". My goal is to do "gnocchi measures aggregation ... --groupby project_id --groupby region_id" to get data grouped project and region. What is the correct way to put constant attribute "region_id" to my resource (without hardcode).

gnocchi_resource.yaml:
```  
- resource_type: instance_network_interface
    metrics:
    ...
    attributes:
      name: resource_metadata.vnic_name
      instance_id: resource_metadata.instance_id
      region_id: 'EU1'
```

### How to reproduce your problem
`gnocchi measures aggregation ... --groupby project_id --groupby region_id`
### What is the result that you get
+---------------------------------------------+---------------------------+-------------+-------------------+
| group                                       | timestamp                 | granularity |             value |
+---------------------------------------------+---------------------------+-------------+-------------------+
| project_id: 0bd784e2...223, region_id: None | 2019-05-18T03:00:00+03:00 |     86400.0 |      5959712333.0 |
| project_id: 752ef33b...656, region_id: None  | 2019-05-18T03:00:00+03:00 |     86400.0 |      5952152165.0 |

### What is result that you expected
+---------------------------------------------+---------------------------+-------------+-------------------+
| group                                       | timestamp                 | granularity |             value |
+---------------------------------------------+---------------------------+-------------+-------------------+
| project_id: 0bd784e2...223, region_id: EU1  | 2019-05-18T03:00:00+03:00 |     86400.0 |      5959712333.0 |
| project_id: 0bd784e2...223, region_id: US1  | 2019-05-19T03:00:00+03:00 |     86400.0 |      5908975265.0 |
| project_id: 752ef33b...656, region_id: EU1  | 2019-05-18T03:00:00+03:00 |     86400.0 |      5952152165.0 |
| project_id: 752ef33b...656, region_id: US1  | 2019-05-19T03:00:00+03:00 |     86400.0 |      5958534802.0 |

What I need to do with my files ? :
gnocchi_resource.yaml.
polling.yaml
pipeline.yaml
meters.d/meters.yaml

**Comment by chungg** [comment]
this probably is better asked on openstack communication channels. also, as a disclaimer, i haven't done anything openstack related in a very long time.

i imagine you want to extract that region info from instance metadata (i'm assuming nova does this) and do something similar to https://github.com/openstack/ceilometer/commit/21a810fec6bbf19584cad7aa5aff59ecea826907 but without the event definition changes.

**Comment by m0zart89** [comment]
Partially solved:
```
- resource_type: instance_network_interface
    metrics:
    ...
    attributes:
      name: resource_metadata.vnic_name
      instance_id: resource_metadata.instance_id
      instance_host: resource_metadata.instance_host
```
because of:
ceilometer/publisher/gnocchi.py:
`    
def sample_attributes(self, sample):
    attrs = {}
    sample_dict = sample.as_dict()

    for name, definition in self._attributes.items():
        value = definition.parse(sample_dict)
        if value is not None:
            attrs[name] = value
    return attrs`

sample.as_dict() -
`
{
'user_id': u'923...0f2',
'name': u'network.incoming.delta',
'resource_id': u'instance-00000027-a00...03b-tapb330714d-fb',
'timestamp': u'2019-05-27T09: 00: 57.684200',
'resource_metadata': {
    u'instance_host': u'os-host1',
    u'image': {
        u'id': u'e2b8...c47'
    },
    u'ephemeral_gb': 0,
    u'flavor': {
        u'name': u'basic1.xs',
        u'ram': 1024,
        u'ephemeral': 0,
        u'vcpus': 1,
        u'swap': 0,
        u'disk': 20,
        u'id': u'643...d2a'
    },
    u'memory_mb': 1024,
    u'display_name': u'deleteme4',
    u'parameters': {

    },
    u'state': u'running',
    u'status': u'active',
    u'disk_gb': 20,
    u'fref': None,
    u'mac': u'fa... 39',
    u'task_state': u'',
    u'image_ref_url': None,
    u'root_gb': 20,
    u'name': u'tapb330714d-fb',
    u'host': u'b86...332',
    u'vnic_name': u'tapb330714d-fb',
    u'instance_id': u'a0091...03b',
    u'instance_type': u'basic1.xs',
    u'vcpus': 1,
    u'image_ref': u'e2b...c47',
    u'architecture': u'x86_64',
    u'os_type': u'hvm'
},
'volume': 0,
'source': 'openstack',
'unit': u'B',
'project_id': u'107...0bf',
'type': 'delta',
'id': 'f38...621',
'monotonic_time': None
}
`
