### ISSUE TITLE
Aggregate api 403 for resource project owner

### ISSUE THREAD

**Issue by mslovy** [gnocchixyz/gnocchi#1039]
### Which version of Gnocchi are you using
gnocchi version： 4.3.3

### How to reproduce your problem
with a  token,  resource project owner, and call api below return: 403

 v1/aggregates?detail=true&granularity=60&start=2019-07-24T06:03

with body:
{
    "operations": [
        "/",
        [
            "metric",
            [
                "5e6e4f5a-aad7-4b7b-a1ed-6e4f9ca8015e",
                "rate:mean"
            ]
        ],
        1000000000
    ]
}

Since the policy file say:
"metric_owner": "project_id:%(resource.project_id)s",
"get metric": "rule:admin_or_creator or rule:metric_owner",

and with the aggregate code below：
https://github.com/gnocchixyz/gnocchi/blob/master/gnocchi/rest/aggregates/api.py#L300

the expected result will be that the metric owner with resource.project_id can access the metric.

however, because of the list_metrics index api return data:
[{'created_by_user_id': u'4a74325b4c09428ea8a62874c042a315', 'name': u'cpu', 'creator': u'4a74325b4c09428ea8a62874c042a315:c50c963c32d947e4b6c683b16096a178', 'resource_id': UUID('867e7da0-d6f6-494d-b9cf-bffc2b3c94ab'), 'created_by_project_id': u'c50c963c32d947e4b6c683b16096a178', 'archive_policy': <gnocchi.indexer.sqlalchemy_base.ArchivePolicy object at 0x7f2d45ad4b10>, 'id': UUID('5e6e4f5a-aad7-4b7b-a1ed-6e4f9ca8015e'), 'unit': u'ns'}, {'project_id': u'7ed03f28e1504ad79bb1be97205efca6', 'user_id': u'ab5a2ea76e074fd9806803f121bd7bd5', 'user': u'ab5a2ea76e074fd9806803f121bd7bd5:7ed03f28e1504ad79bb1be97205efca6', 'roles': [u'member', u'reader'], 'domain_id': None}, <oslo_policy.policy.Enforcer object at 0x7f2d6074ebd0>]

and the  resource_id is an ObjectType. not flatten to a dict like resource.project_id: xxxxx. Therefore, the oslo.policy enforce cannot match the attribute resource.project_id and return fasle.

**Comment by chungg** [comment]
sorry, i don't quite understand this, you're mentioning `resource_id` and `resource.project_id`. is the issue that the metric returned by list_metrics is not flattening resource properly to resolve resource.project_id? or is resource not there at all?

i don't know about the policy and if the metric_owner policy is valid (i am not familiar with oslo.policy). it seems like we should maybe try dropping:
```            for metric in metrics:
                api.enforce("get metric", metric)``` and instead pass use ```        policy_filter = pecan.request.auth_helper.get_metric_policy_filter(
            pecan.request, "list metric")``` and pass that in as a policy filter for to `list_metrics`

**Comment by mslovy** [comment]
list_metrics is not flattening resource properly to resolve resource.project_id.  The resource in metric object is a Resource object there and not flatten so that the policy engine cannot resolve the resource.project_id there.



> sorry, i don't quite understand this, you're mentioning `resource_id` and `resource.project_id`. is the issue that the metric returned by list_metrics is not flattening resource properly to resolve resource.project_id? or is resource not there at all?

**Comment by mslovy** [comment]
I think we should properly flatten the target before we pass it to oslo.policy. 

oslo.policy just  load the policy.json:

"metric_owner": "project_id:%(resource.project_id)s", which means the project_id in the api or token, should exactly match values of resource.project_id.

however, not flatten Resource Object result in the oslo.policy cannot load the value of resource.project_id. That is reason the enforce cannot be passed.
