### ISSUE TITLE
oslo_config.cfg.NoSuchOptError

### ISSUE THREAD

**Issue by universcom** [gnocchixyz/gnocchi#1045]
i want use gnocchi python api and run simple below code:
```
from keystoneauth1 import loading
from oslo_config import cfg
from gnocchiclient import auth
from gnocchiclient.v1 import client

conf = cfg.ConfigOpts()
auth_plugin = loading.load_auth_from_conf_options(conf, "gnocchi_credentials")
gnocchi = client.Client(session_options={'auth': auth_plugin})
gnocchi.resource.list("generic")
```
i get error: 
`oslo_config.cfg.NoSuchOptError: no such option gnocchi_credentials in group [DEFAULT]`

where are do config for resolve this error? 
tnx

**Comment by chungg** [comment]
sorry, i don't have openstack. i would suggest trying openstack channels and/or installing devstack and enabling ceilometer. hopefully, it still works and will configure ceilometer+gnocchi+keystone for you.

**Comment by tobias-urdin** [comment]
You need to load config options before trying to use them. Unrelated to Gnocchi.
