### ISSUE TITLE
Reaggregation default

### ISSUE THREAD

**Issue by viktorkrivak** [gnocchixyz/gnocchi#1046]
Gnocch automatically select non-sense reaggregation method. 
For example:
openstack metric measures aggregation -m cpu --query 'server_group=17a7b3f8-e258-4b12-9f98-78a57cad1a1e' --resource-type instance --aggregation rate:mean

select same method for reaggregation as we used for aggregation. So result is "rate of change of rate of change" which produce nonsense negative number.

This can be easily fixed by adding reaggregation parameter, but since gnocchi have some capabilities to select default reaggregation it should always strip rate: prefix from that method.

I know that "metric measures aggregation" is going to be deprecated in favor of metric aggregates which have much more power, but lots of SW still used this feature because it is sufficient. This problem occurs for example in Aodh when you try autoscalling. When you have at least two instances in server_group aodh will start to get nonsense number like negatives etc.

I know the best course of action should be to fix Aodh to use new aggregates method but since "metric measures aggregation" is not fully deprecated I think it should choose sensible defaults for reaggregation. 

Change I propose just add two lines:

    diff --git a/gnocchi/rest/api.py b/gnocchi/rest/api.py
    index 4be3f795..2d8d691d 100644
        --- a/gnocchi/rest/api.py
    +++ b/gnocchi/rest/api.py
    @@ -1920,6 +1920,8 @@ class AggregationController(rest.RestController):
     
             if reaggregation is None:
                 reaggregation = aggregation
    +            if ':' in reaggregation:
    +                reaggregation = reaggregation.split(':')[1]
     
             for metric in metrics:
                 enforce("get metric", metric)

**Comment by chungg** [comment]
i agree, it's confusing. to be honest, i think the default reaggregation should've been 'mean' rather than just the series aggregation repeated. that said, i think the api has been out for long enough that this may break existing users' workflow. dropping `rate:` seems harmless enough but i'd lean more to just fixing aodh first.

**Comment by viktorkrivak** [comment]
I agree that Aodh needs to be fixed. But we probably need to re-implement whole aggregation query to gnocchi and with this also change Aodh API. Because at this moment there is no way to set operations query on aggregates. When we fix Aodh there will be another problem that Heat which is mostly used to setup autoscaling and use Aodh to notify. So heat also need to be changed because it doesn't have ability to set operations either. It will be a long run.

I'm pretty sure that this change can't break anything because no one can use rate aggregation of rate to something meaningful. And it will be a quick fix for this problem in older SW, which can stay until this method become obsolete. 

I want some discussion before I propose pull-request. Just to be sure that this can't break anything.

**Comment by chungg** [comment]
well, this in theory could break something but i agree, i'm not sure how many people are running around computing the acceleration of the series (and if they are it's probably explicit).

i'm indifferent but i'll let this sit for a bit in case anyone else wants to give feedback.

**Comment by tobias-urdin** [comment]
Should be fixed with https://opendev.org/openstack/aodh/commit/74eadfbd58359b7ebe9e1e40ae6b6ff245146bb8 and then bugfix https://github.com/gnocchixyz/gnocchi/pull/1202 - please let me know otherwise and we can reopen.
