### ISSUE TITLE
Project is unmaintained

### ISSUE THREAD

**Issue by cpl** [gnocchixyz/gnocchi#1049]
See #1047 and #1048

**Comment by jd** [comment]
I've fixed the title for you. :)

**Comment by lhuang001** [comment]
I am very sad to hear this news. could you tell me how much aodh and ceilometer will be affected？

**Comment by chungg** [comment]
none of the contributors to gnocchi actively participate in openstack so gnocchi's status is unrelated to ceilometer/aodh.

anyone is free to contribute to gnocchi still. we just currently don't have time to fix things like documentation and ci.

**Comment by unamuno** [comment]
Maybe you should change the main README then.

**Comment by berendt** [comment]
@lhuang001 Please check http://lists.openstack.org/pipermail/openstack-discuss/2019-November/010922.html. Probably MongoDB will be used for Ceilometer again.

**Comment by berendt** [comment]
@chungg Can you please include a hint in the README? So it is not really obvious at the moment that there is no active further development taking place.

**Comment by chungg** [comment]
> @lhuang001 Please check http://lists.openstack.org/pipermail/openstack-discuss/2019-November/010922.html. Probably MongoDB will be used for Ceilometer again.

sigh. that thread bums me out.

i don't contribute/follow openstack anymore but if anyone is undecided what to adopt (if gnocchi doesn't fit your needs), we dropped mongo and ceilometer api because it stored and returned an absurd amount of data[1] and required significant resources to be thrown at it for results ranging from 'not good' to 'hot garbage'. 

whatever solution you choose for monitoring/billing/etc... don't choose ceilometer api+mongo unless:

1. your cloud has an insignificant number of users
2. they rewrite the storage schema and change the ceilometer api response aka everything
3. you're a sadist

if any of those apply to you, even then, just do some googling and find something better.

[1] https://www.slideshare.net/GordonChung/ceilometer-to-gnocchi/3

**Comment by tobias-urdin** [comment]
There was a thread back in November about this, there are probably multiple people that are willing to step up to take over the maintenance of the project, while this might not boost the development of new features and mostly mean a working product and hopefully bug fixes. [1].

It was never decided on how the proceed so need to follow up on that, either the project will be forked back to OpenStack infrastructure or hopefully somebody can get help from the Gnocchi team to be added as a maintainer which can maintain the CI and review bugfixes.

I would volunteer some of my time to keep the CI and reviewing bug, I can hopefully take some more time to dig deeper on how to resolve, hopefully sooner than later if nobody beats me to it.

[1] http://lists.openstack.org/pipermail/openstack-discuss/2019-November/010922.html

**Comment by chungg** [comment]
just to clarify, is the request to fork code back to OpenStack and have current Gnocchi members review there OR to add additional members to the current team in github OR something else?

i'm completely open to adding other members, we just haven't seen any contributions so the membership has remained as is.

in regards to moving it back to OpenStack, i'm not oppose to it but speaking for myself, i don't have the capacity to follow that community so feedback will be limited at best... not that it's particularly valuable :)

**Comment by jd** [comment]
> i'm completely open to adding other members, we just haven't seen any contributions so the membership has remained as is.

That. We never prevented anyone to send PR to this repository and try to fix the CI or improve things. I just never happened.

The first step if anyone really wants to keep this project alive is to actually contribute here and try to improve things.

As somebody said once: talk is cheap. Show me the code. 😉

**Comment by Adrian-Turjak** [comment]
Related to this discussion: https://review.opendev.org/#/c/744592

**Comment by tobias-urdin** [comment]
The main Gnocchi CI is working again, we will still need to work on getting it on Ubuntu Bionic then hop to Ubuntu Focal. The python-gnocchiclient is still having issues, the integration tests is hanging, if anybody wants to help troubleshoot that.

**Comment by tobias-urdin** [comment]
Update: Master was green before but is now red again, I haven't had time to check it out so any help is appreciated. I was hoping that I could get stable/4.3 fixed as well but was never able to get time to finish it. I will try to get some time free to help fixing the CI when I can.

**Comment by tobias-urdin** [comment]
There is now patches pending to fix CI for master, the stable branch still needs to be fixed.

**Comment by tobias-urdin** [comment]
Unpinning and closing, we are doing our best to keep CI stable and merge what we can. Any help is greatly appreciated! Please ping @gnocchixyz/devs team and we will try to do our best.
