### ISSUE TITLE
how can i get multi metrics of multi resources in a singal request

### ISSUE THREAD

**Issue by lhuang001** [gnocchixyz/gnocchi#1052]
gnocchi version 4.1.4
gnocchiclient version 7.0.5

i can`t find a api which could retrive multi metrics of multi resources in a singal request.
maybe this official doc mentioned it,
(https://gnocchi.nodead.net/rest.html#list-of-supported-operations)， 
so could you offer a sample of how to use it?  Thanks for your help.

**Comment by chungg** [comment]
you need to clarify your question. but https://gnocchi.nodead.net/rest.html#get-one-or-more-metrics may be a start

i don't know the equivalent call in the client or if it exists.
