### ISSUE TITLE
No more revision since some date

### ISSUE THREAD

**Issue by tomm144** [gnocchixyz/gnocchi#1055]
Hi,
few days ago i found that some volume resource revisions missing history. I have no idea what hapenned.
Thanks.

### Which version of Gnocchi are you using
Gnocchi 4.3.3
Gnocchi Client 7.0.1-0ubuntu1
### How to reproduce your problem
I have no idea what hapenned
### What is the result that you get
- creator: d9274e66bc9f4d29b89e0156d844abcc:27af624d6b174222a47d664f73f7e924
  ended_at: null
  id: 0a685903-daa8-4680-902a-c18c2e481c98
  metrics:
    volume.size: 54c71987-411c-47bb-b384-fc20d5ca5697
  original_resource_id: 0a685903-daa8-4680-902a-c18c2e481c98
  project_id: 25168aeeb5c54169a71b993ab10556ce
  **revision_end: '2020-01-22T18:00:03.498633+00:00'**
  revision_start: '2020-01-22T17:00:59.476097+00:00'
  started_at: '2020-01-09T15:34:11.135669+00:00'
  type: volume
  user_id: 5d5628e15f114b8ba70c2635a6e2f45a
### What is result that you expected
- creator: d9274e66bc9f4d29b89e0156d844abcc:27af624d6b174222a47d664f73f7e924
  ended_at: null
  id: 9a3f562a-9113-4da2-bdaf-b625d01212fb
  metrics:
    volume.size: 15167c4b-8023-47a4-8eab-bd6e15d04e58
  original_resource_id: 9a3f562a-9113-4da2-bdaf-b625d01212fb
  project_id: 25168aeeb5c54169a71b993ab10556ce
  **revision_end: null**
  revision_start: '2020-02-07T09:00:39.610112+00:00'
  started_at: '2020-01-22T12:15:24.898398+00:00'
  type: volume
  user_id: 5d5628e15f114b8ba70c2635a6e2f45a

**Comment by jd** [comment]
Is this the only revision you have for the whole resource?

**Comment by tomm144** [comment]
Not sure what do you mean.
After highlited date i cannot see any new revisions for this resource. Before that date are revisions.
After some digging i found out that in mysql(?) database are rows recognizably belong to "broken" revisions with accurate dates. And after deleting these rows problematic revision work again.

**Comment by tobias-urdin** [comment]
Please provide more information and we can investigate further, until then closed.
