### ISSUE TITLE
Gnocchi server in openstack(stein version) is look like not function.

### ISSUE THREAD

**Issue by intentc** [gnocchixyz/gnocchi#1060]
Before reporting an issue on Gnocchi, please be sure to provide all necessary
information.

### Which version of Gnocchi are you using
#gnocchi server version 
| version | 4.3.2 |
#gnocchi --version 
gnocchi 7.0.6
### What is the result that you get
run following command :
(virtualenv) [root@openstack01 opt]# gnocchi metric list | head -n 5
+--------------------------------------+---------------------+-------------------------------+---------+--------------------------------------+
| id                                   | archive_policy/name | name                          | unit    | resource_id                          |
+--------------------------------------+---------------------+-------------------------------+---------+--------------------------------------+
| 09ff3bfe-902e-4003-b2f2-d908da3f23e5 | ceilometer-low      | vcpus                         | vcpu    | 8e79ec9b-bbf4-4e60-9f57-3a5959e65fa4 |
| 18195e5a-c252-4649-a2eb-22c9223ad4a7 | ceilometer-low-rate | cpu                           | ns      | 0528992f-7072-4ec9-9cb9-709341a4e404 |
| 1a774e55-7f70-4daa-8457-2e14d908cb55 | ceilometer-low-rate | network.incoming.packets      | packet  | 33928e48-8439-5589-b254-62ef599b038e |
| 1d601604-9e64-4c3d-abe1-e51291753203 | ceilometer-low-rate | network.incoming.bytes        | B       | 33928e48-8439-5589-b254-62ef599b038e |

### What is result that you expected
Dataresource type (vcpus,cpu...) should has some values,but there nothing happend.
I install gnocchi-server in one openstack environment,and use gnocchi to find virtual machines's metries in openstack .
openstack version is stein, linux release is centos7.6,deploy openstack through kolla-ansible's multinode measure.

**Comment by jd** [comment]
Likely an issue with your Ceilometer deployment.
This is a bug report place for Gnocchi, we can't help with that.
