### ISSUE TITLE
UUID collisions between services will prevent resources from being created in gnocchi.

### ISSUE THREAD

**Issue by kgube** [gnocchixyz/gnocchi#1063]
### Which version of Gnocchi are you using
4.2.6

### How to reproduce your problem
Create an instance in nova, then use the openstack CLI client to create an image in glance with the `--id` parameter set to the UUID of the instance. The image and the instance will now have the same UUID, which isn't a problem in openstack because both are managed in different databases.

### What is the result that you get
Ceilometer will create a resource for the instance in Gnocchi, but will fail to create a resource for the image, as the UUID is already in the database. No metrics will be created and no measures will be stored for the image.

As we are using ceilometer and gnocchi for billing in our openstack deployments, we have the problem that a user might use this method to create images for which they would not get billed.

### What is result that you expected
Ideally, Gnocchi would store metadata, metrics and measures for both resources.

Now, I'm aware of the current status of the project and I know a bit of Gnocchies internals, so I believe it is very unlikely that this will ever get fixed, but I wanted to report it at least.

**Comment by tobias-urdin** [comment]
Not sure how to categorize this, but the chance of this happening is close to zero and I'm pretty changing to accommodate for that is pretty useless.

I guess the resource type could be factored into the uniqueness of the UUID but seems unlikely nobody will push that work nor hit that issue.

**Comment by kgube** [comment]
Yeah, the chance of that happening by accident is basically zero.
I assumed a malicious user when I reported this, but even if there was one, they wouldn't cause any real damage and we would notice it sooner or later.

Allowing duplicate IDs for different resource types is probably a pain to implement and a new source of bugs for very little gain.
We might be better off with just monitoring the ceilometer logs for indications of ID collisions, so I think you can close this Issue.
