### ISSUE TITLE
gnocchi CPU time is supposed accumulated nano time, but when VM stopped, the accumulation seems starting from 0 again, which end up cpu_util appear native by '(* ( / (aggregate rate:mean (metric cpu mean)) 60000000000.0) 100)'

### ISSUE THREAD

**Issue by MingjunShan** [gnocchixyz/gnocchi#1079]
Gnocchi version tag 4.4 (4.3.1?), but may be re-producible at at gnocchi

 create new instance, then the CPU nano time and cpu util to percentage based on solution of issue (https://github.com/gnocchixyz/gnocchi/issues/1044), all looks good
To produce issue: shut down the instance, after a while, the CPU util show nagative.
The cause behind seems the data generated by ceilometer restart from zero, instance accumulating from before being stopped. see sample: 

Any 

### How to reproduce your problem
Install devstack with gnocchi,
### What is the result that you get
gnocchi aggregates --resource-type instance  '(metric cpu mean)'  'id=effd51c4-3df8-4df4-966b-bfb9b9d6a947'
| effd51c4-3df8-4df4-966b-bfb9b9d6a947/cpu/mean | 2020-11-02T13:45:00+00:00 |       300.0 | 301230000000.0 |
| effd51c4-3df8-4df4-966b-bfb9b9d6a947/cpu/mean | 2020-11-02T13:50:00+00:00 |       300.0 | 302260000000.0 |
| effd51c4-3df8-4df4-966b-bfb9b9d6a947/cpu/mean | 2020-11-02T13:55:00+00:00 |       300.0 | 303270000000.0 |
| effd51c4-3df8-4df4-966b-bfb9b9d6a947/cpu/mean | 2020-11-02T14:00:00+00:00 |       300.0 |  31800000000.0 |
| effd51c4-3df8-4df4-966b-bfb9b9d6a947/cpu/mean | 2020-11-02T14:05:00+00:00 |       300.0 |  32890000000.0 |
| effd51c4-3df8-4df4-966b-bfb9b9d6a947/cpu/mean | 2020-11-02T14:10:00+00:00 |       300.0 |  33940000000.0 |

You can see above the abosulate value is supposed to be growing, but it dropped from 303270000000.0 to 31800000000.0,  eventually: 
 gnocchi aggregates --resource-type instance  '(/ (aggregate rate:mean (metric cpu mean)) 300000000000.0)'  'id=effd51c4-3df8-4df4-966b-bfb9b9d6a947' 
aggregated | 2020-11-02T13:45:00+00:00 |       300.0 | 0.33666666666666667 |
| aggregated | 2020-11-02T13:50:00+00:00 |       300.0 |  0.3433333333333333 |
| aggregated | 2020-11-02T13:55:00+00:00 |       300.0 | 0.33666666666666667 |
| aggregated | 2020-11-02T14:00:00+00:00 |       300.0 |  -90.49000000000001 |

See the CPU percetange appears -90%. 
### What is result that you expected
The result expected from ceilometer is to have acculative nano time when the VM is stopped, the CPU util should show always positive value.

**Comment by chungg** [comment]
i can't remember the official way to handle this. in openstack, i believe it captures `rate:mean` by default. so you would want something like `gnocchi aggregates --resource-type instance '(/ (metric cpu rate:mean) 300000000000.0)' 'id=effd51c4-3df8-4df4-966b-bfb9b9d6a947'`

i'm not sure that solves your issue. the alternative would be to use `clip` to set a lower bound in this case. `gnocchi aggregates --resource-type instance '(/ (clip_min (metric cpu rate:mean) 0) 300000000000.0)' 'id=effd51c4-3df8-4df4-966b-bfb9b9d6a947'` which will effectively ignore any negative results.

**Comment by MingjunShan** [comment]
Thank you @chungg  the way of clip_min seems a clean way, other than manually picking out the errored one.

**Comment by mrunge** [comment]
Since this seems to be answered, can it be closed?

**Comment by unlenen** [comment]
It does not solve the problem , I use the 4.3.4 version and there is no clip_min func on it . I also upgraded to 4.3.5 with pip3 install gnocchi --upgrade . Nothing changes.   It is a cpu metric which can not be less than 0 but it may gives negative outputs.

Supported funcs :   gnocchi capabilities list| tr ',' '\n' | grep -v pct

 'median'
 'sum'
 'count'
 'std'
 'mean'
 'rate:first'
 'rate:min'
 'rate:std'
 'first'
 'rate:median'
 'last'
 'rate:last'
 'rate:mean'
 'rate:count'
 'max'
 'rate:sum'
 'rate:max'
 'min'

When It happens:
__________________________________________________________________________________________________
Openstack heat autoscaleer group scale up or down my app cluster .


Demo : 
__________________________________________________________________________________________________
STACK_NAME="argela11"

T_END=$(date +'%Y-%m-%dT%H:%M:00.000000')
T_BEGIN=$(date +'%Y-%m-%dT%H:%M:00.000000'  --date='2 minutes ago' )

RESOURCE_ID=$(openstack stack list| grep $STACK_NAME| awk -F '|' '{print $2}'| awk '{print $1}')

echo "Time : $T_BEGIN  -  $T_END"

curl -s -X POST -H "X-Auth-Token: $AUTH_TOKEN" \
 -H "Accept-Encoding: gzip, deflate" \
 -H "Accept: application/json" \
 -H "Content-Type: application/json" \
 -d '{
  "operations": [clip_min ,[
    "/",
    [
      "aggregate",
      "rate:mean",
      [
        "metric",
        "cpu",
        "mean"
      ]
    ],
    600000000
  ] ,0],
  "resource_type": "instance",
  "search": {
    "=": {
      "server_group": "'${RESOURCE_ID}'"
    }
  }
}' \
'http://192.168.134.197:8021/v1/aggregates?needed_overlap=1&granularity=60&start='${T_BEGIN}'&stop='${T_END}
---------------------------------------------------------------------------


Output : 
![resim](https://user-images.githubusercontent.com/63339192/108988631-bf886300-76a5-11eb-8910-e417b91654c2.png)

**Comment by manuvakery1** [comment]
> metric cpu rate:mean

Any workaound available for this

**Comment by tobias-urdin** [comment]
See https://github.com/gnocchixyz/gnocchi/issues/1044
