### ISSUE TITLE
Help to fix CI, review, and get PRs merged

### ISSUE THREAD

**Issue by rafaelweingartner** [gnocchixyz/gnocchi#1086]
Hello @chungg, @jd, @sileht, 
We have currently the following PRs open:
* https://github.com/gnocchixyz/gnocchi/pull/1059
* https://github.com/gnocchixyz/gnocchi/pull/1062
* https://github.com/gnocchixyz/python-gnocchiclient/pull/104

We have already been able to get PR https://github.com/gnocchixyz/gnocchi/pull/1056 merged.

We see that there are some issues with the CI. How can we help you guys fixing the CI process, and possibly getting some reviews and PRs merged?

We would like to contribute more, but we are a bit lost on how to reach people that can merge the PRs for instance.

**Comment by jd** [comment]
Thanks for the ping. We can't really spend time fixing the CI, but happy to do some review.
Adding @tobias-urdin who should be on the list of core reviewers if he ever accepts it. You can ping @gnocchixyz/devs to ping everyone at once.

**Comment by tobias-urdin** [comment]
I will be able to do reviews, I won't be able to work on the CI for some more time though due to internal projects.

**Comment by rafaelweingartner** [comment]
We are actually offering help, not just asking to fix the CI. If you guys allow us to, we would like to contribute more, such as fixing the CI. Currently we have some open PRs, and probably in the future we will have more to contribute back to the community. However, we see that the community needs a health and stable CI and CD process. Therefore, if you guys are comfortable, we would like to help you guys with it.

**Comment by jd** [comment]
Yes, happy to get help. Most of the team is now working on other things, but if new people wants to come and help, we're happy to onboard new people in the team. We just added @tobias-urdin to the team — they fixed the CI a few weeks ago.
We'll make our best to review your PR in the meantime. 😄

**Comment by tobias-urdin** [comment]
That would be great! I have some pending PRs that tries to fix some things, seeing as master is red again that's a good place to start. I wanted to get stable/4.3 branch green after I got master green but haven't got to it yet.

**Comment by tobias-urdin** [comment]
There is now patches pending to fix CI for master, the stable branch still needs to be fixed.

**Comment by rafaelweingartner** [comment]
@tobias-urdin the PRs to master were not working on master.  We managed to fix that in our PRs. Can you guys reconsider it?

**Comment by tobias-urdin** [comment]
@gnocchixyz/devs 1062 and 1059

**Comment by tobias-urdin** [comment]
Closing as I'm following up in https://github.com/gnocchixyz/gnocchi/pull/1059
