### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by tobias-urdin** [gnocchixyz/gnocchi#1091]
The old travis-ci.org will be read-only as of December 31th 2020. We need to migrate to travis-ci.com.

**Comment by tobias-urdin** [comment]
@jd I've sent a request to approve the travis-ci.com app for the gnocchi organization.

**Comment by jd** [comment]
I accepted.

TBH I'd rather move to GitHub Action if that's possible. Your call!

**Comment by tobias-urdin** [comment]
Thanks! Seeing as this is the minimum effort I'll continue but keep that in mind for the future.

**Comment by tobias-urdin** [comment]
@jd doesn't look like I can do it, even though it's approved when I click "Manage repositories on GitHub" for the gnocchixyz organization it just requests access again. Might need an owner to login and approve and click manage for all repositories, I'm following the guide [1].

[1] https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by tobias-urdin** [comment]
If you could, login to travis-ci.com with your GitHub, click your avatar -> Settings, Click the gnocchixyz organization and click "Manage repositories on GitHub" and manage all of them there. Then go to the Migrate tab and migrate all projects, should hopefully be just two click then I'm out of your way.

**Comment by jd** [comment]
Should  be good now, I migrated all the repos.

**Comment by tobias-urdin** [comment]
Thank you @jd
