### ISSUE TITLE
gnocchi-api is out of memory frequently

### ISSUE THREAD

**Issue by magiceses** [gnocchixyz/gnocchi#1111]
Before reporting an issue on Gnocchi, please be sure to provide all necessary
information.

### Which version of Gnocchi are you using
version 3.1

### How to reproduce your problem
Deploy 500 nodes in an openstack cluster（About 5000 virtual machines）

ceilometer monitore data
`
memory.util
memory.usage
cpu
cpu_util
disk.device.read.requests
disk.write.bytes
disk.read.requests
disk.read.bytes
disk.write.requests
disk.device.read.bytes
disk.device.write.bytes
disk.device.write.requests
network.incoming.bytes
network.outgoing.packets
network.incoming.packets
network.outgoing.bytes
volume.read.bytes
volume.write.bytes
`

### What is the result that you get
gnocchi-api is out of memory frequently(current limit is 16Gi)

### What is result that you expected
I want to know how much memory gnocchi-api needs to handle so much data; Any body help?

**Comment by tobias-urdin** [comment]
Hello, we have a very high load on our Gnocchi API nodes as well but haven't had any issues with memory. We are running 4 Gnocchi API services, how many are you running?

You are also running a older version, do you have the possibility to test a newer version?

**Comment by magiceses** [comment]
> Hello, we have a very high load on our Gnocchi API nodes as well but haven't had any issues with memory. We are running 4 Gnocchi API services, how many are you running?
> 
> You are also running a older version, do you have the possibility to test a newer version?

Thank you for reply. My project's gnocchi-api is deployed in k8s cluster, 3 replica, memory limit is 16Gi, oom once a day. And i have not environmental conditions to test the new gnocchi version currently ,sorry.

**Comment by mrunge** [comment]
There is a known memory issue in ujson version 2, the fix got in 2.0.3. Gnocchi uses that without pinning, so there is a chance that you'd use that version. It's worth to take a look.

**Comment by magiceses** [comment]
my WSGI settings is 
``` 
WSGIDaemonProcess gnocchi processes=32 threads=64 user=gnocchi group=gnocchi display-name=%{GROUP}
```

**Comment by magiceses** [comment]
> There is a known memory issue in ujson version 2, the fix got in 2.0.3. Gnocchi uses that without pinning, so there is a chance that you'd use that version. It's worth to take a look.
> Also see #1136

Thanks. I'll take a look.

**Comment by magiceses** [comment]
I test ujson version 2.0.3 ,here is script in container gnocchi-api:
```
()[root@gnocchi-api-69c75646dc-lzg9l /]# ls -lh test.json
-rw-r--r-- 1 root root 65M Jul  1 10:17 test.json
```
```
import ujson

print ujson.__version__ # 2.0.3

while True:
    with open('test.json') as infile:
        data = ujson.load(infile)
```

And i found memory leak maybe stall exist;

the memory usage of gnocchi-api before test 
`
kubectl top po -n openstack gnocchi-api-69c75646dc-lzg9l`
`NAME                           CPU(cores)   MEMORY(bytes)`
`gnocchi-api-69c75646dc-lzg9l   1m           951Mi
`

when testing
`
kubectl top po -n openstack gnocchi-api-69c75646dc-lzg9l`
`NAME                           CPU(cores)   MEMORY(bytes)`
`gnocchi-api-69c75646dc-lzg9l   965m         1685Mi
`

Interrupt program;
And waiting for 20min
`
kubectl top po -n openstack gnocchi-api-69c75646dc-lzg9l`
`NAME                           CPU(cores)   MEMORY(bytes)`
`gnocchi-api-69c75646dc-lzg9l   1m           1019Mi
`

see that there are still 68M of memory that have not been released; but when i use `json` to test the script , it did not happen.

Is there anything wrong with my test method?

> There is a known memory issue in ujson version 2, the fix got in 2.0.3. Gnocchi uses that without pinning, so there is a chance that you'd use that version. It's worth to take a look.
> Also see #1136

**Comment by magiceses** [comment]
today, gnocchi-api raise error: The fn-radosclient service process was killed by the operating system due to excessive memory usage

**Comment by tobias-urdin** [comment]
Unfortunately it's hard for us to troubleshoot this any further so you'd need to figure out the issue. I would recommend upgrading to a newer version, verify you run with a newer version of ujson, check any other potential to why memory would be high.
