### ISSUE TITLE
create 4.3.5 tag

### ISSUE THREAD

**Issue by mrunge** [gnocchixyz/gnocchi#1117]
It's been a while since 4.3.4 has been released. Can you please tag 4.3.5 in the 4.3 branch in order to pick up the latest fixes up there? They are fixing issues running on python3.

Thank you.

**Comment by tobias-urdin** [comment]
released 4.3.5 - maybe @jd can fix pypi release

**Comment by jd** [comment]
What's broken?

**Comment by tobias-urdin** [comment]
i'm assuming it's a manual step

**Comment by jd** [comment]
Supposedly travis pushes releases to PyPI

**Comment by mrunge** [comment]
Apparently, it did not.

**Comment by tobias-urdin** [comment]
@jd the pypi deploy failed because it invoked with python 2.7 and pip is not supporting it anymore https://travis-ci.com/github/gnocchixyz/gnocchi/jobs/481262454#L554

would you mind pushing one manually? I will look into a fix that deploys using python 3 when I have some spare time over.

**Comment by jd** [comment]
https://pypi.org/project/gnocchi/4.3.5/
