### ISSUE TITLE
Web site

### ISSUE THREAD

**Issue by mrunge** [gnocchixyz/gnocchi#1144]
There are two web pages for gnocchi, one on gnocchi.xyz, the other one on gnocchi.osci,io. The latter is referenced from github. Which one is the one to use? Do we know who is paying for these/hosting them? ... who to contact for updates?

**Comment by mrunge** [comment]
Okay, thank you. I was contacted about that and wanted to make sure we don't get into the same situation again.

**Comment by mrunge** [comment]
> gnocchi.osci.io is managed by your company, @mrunge l

If it was *my* company, I probably wouldn't be working anymore.

**Comment by mscherer** [comment]
Yeah, we weren't able to get it back in time when it expired, so we moved it to osci.io. I know @duck-rh is looking at it.

**Comment by duck-rh** [comment]
Quack,

Just to clarify for people caring outside RH.

So from what I've seen gnocchi.xyz simplyproxy to the OSCI one. It would be nice to know who took over the xyz domain but as it is it's not a problem.

As for the publishing there are build failures so it's not up-to-date. Bumping the OS would solve these problems. I guess no one cares about the details so I should probably jump to a solution. I'm thus going to reinstall the VM so expect a short downtime.

\\_o<
