### ISSUE TITLE
Delete branches up to 4.3

### ISSUE THREAD

**Issue by tobias-urdin** [gnocchixyz/gnocchi#1156]
We should delete all old stable/.* branches up to 4.3 and 4.4 which is the currently active releases.

**Comment by tobias-urdin** [comment]
@jd input on deleting all branches up to 4.3

**Comment by jd** [comment]
I don't think we should delete anything. What's the problem with keeping them?

**Comment by tobias-urdin** [comment]
just general cleanup, ci is probably dead, we probably won't merge any new code ever into those

the tags is still there

**Comment by jd** [comment]
Right, though if anyone wants to pick up or backport a patch (even without CI) it's still possible in theory.
At best we can rename them to `unmaintained/stable/3.x` or the like if you want.

**Comment by tobias-urdin** [comment]
Sure, or if you are ok with something like ``eol-3.x`` etc? I will refrain from configuring CI for those branches if so

**Comment by jd** [comment]
Sure, maybe keep the same pattern with something like `eol/3.x`.

**Comment by tobias-urdin** [comment]
Indeed, I'll do that.
