### ISSUE TITLE
When python version is 3, it still find python2

### ISSUE THREAD

**Issue by HanGuangyu** [gnocchixyz/gnocchi#1168]
The version of Gnocchi: 4.3.4

service status is failed.
I find in 93 lines of gnocchi/cli/api.py, it use 'python' as plugin, not python3.
And if the python version is 3 in the environment, it can't find python, because the name is python3.

I want to ask whether the question should in there, should we add a judge to distinguish what version of python in use and use different plugin.

The fllowing is code:
    args = [
        "--if-not-plugin", "python", "--plugin", "python3", "--endif",
        "--%s" % conf.api.uwsgi_mode, "%s:%d" % (
            conf.host or conf.api.host,
            conf.port or conf.api.port),
        "--master",
        "--enable-threads",
        "--thunder-lock",
        "--hook-master-start", "unix_signal:15 gracefully_kill_them_all",
        "--die-on-term",
        "--processes", str(math.floor(workers * 1.5)),
        "--threads", str(workers),
        "--lazy-apps",
        "--chdir", "/",
        "--wsgi", "gnocchi.rest.wsgi",
        "--pyargv", " ".join(sys.argv[1:]),
    ]

**Comment by tobias-urdin** [comment]
Fixed by https://github.com/gnocchixyz/gnocchi/pull/1171
