### ISSUE TITLE
Only v1/resource/generic returns 500 internal server error, and all other API calls work well

### ISSUE THREAD

**Issue by intos-mingjun** [gnocchixyz/gnocchi#1181]
See below of how to re-produce the error. Only resource/generic returns error, and other api call all good. The same configuration on 4.3 works well even on the same API endpoint. 

### Which version of Gnocchi are you using
4.4

### How to reproduce your problem
Make a rest call by CURL to the api endpoint, or simply call "gnocchi resource list"
curl -g -i -X GET http://192.168.8.16:8041/v1/resource/generic?details=true -H "Accept: application/json" -H "User-Agent: gnocchi keystoneauth1/4.4.0 python-requests/2.26.0 CPython/3.9.5" -H "X-Auth-Token:xxx"

### What is the result that you get
HTTP/1.1 500 Internal Server Error
Date: Mon, 27 Dec 2021 00:57:03 GMT
Server: Apache/2.4.48 (Debian)
Content-Length: 531
Connection: close
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>

### What is result that you expected
Expect to print all resource list in details

**Comment by chungg** [comment]
i would expect this to have a corresponding traceback in server side logs if it returns a 500.

**Comment by tobias-urdin** [comment]
This needs more information to troubleshoot, could potentially be that we don't catch an exception about it not being found.

**Comment by tobias-urdin** [comment]
Closing, feel free to update with more information to reopen.
