### ISSUE TITLE
get error 500 if request 'get_all' with invalid values. 

### ISSUE THREAD

**Issue by Dmitry-Eremeev** [gnocchixyz/gnocchi#1196]
### How to reproduce your problem
send invalid request to gnocchi api
metric?query=KoZlthVNGjXDeWPaEgRP

### What is the result that you get
500 Internal Server Error

### What is result that you expected
400 Bad Request
Invalid input: extra keys not allowed @ data[u'query']

**Comment by tobias-urdin** [comment]
Fixed by https://github.com/gnocchixyz/gnocchi/pull/1197
