### ISSUE TITLE
metricd processing is slow

### ISSUE THREAD

**Issue by manuvakery1** [gnocchixyz/gnocchi#1222]
### Which version of Gnocchi are you using
I am running gnocchi `4.3.4` in HA using redis for coordination
incoming storage - redis
aggregate storage- swift s3 driver
### How to reproduce your problem
I have 2k+ instances running in multi-region OpenStack cluster. I have deployed gnocchi centrally so metrics from all regions are collected in a single place. I have noticed metricd processing is not as fast as it is intended to be. I see the following 
```
"storage/number of metric having measures to process": 17864,
 "storage/total number of measures to process": 204035
```
I have 54 metricd deamons running across 4 nodes. I see the number always near to 200k. Following is my gnocchi configuration
```
[DEFAULT]
use_stderr = False
debug = False
coordination_url = redis://redis:6379
parallel_operations = 16
use_journal = false

[incoming]
driver = redis
redis_url = redis://redis:6379

[indexer]
url = mysql+pymysql://gnocchi:gnocchipass@db/gnocchi?charset=utf8

[metricd]
workers = 16
metric_processing_delay = 60
greedy = True
metric_reporting_delay = 120
metric_cleanup_delay = 300
processing_replicas = 3

[storage]
driver = s3
s3_bucket_prefix = gnocchi
s3_check_consistency_timeout = 60
s3_max_pool_connections = 50
```
. ceilometer polling interval is 300sec. and meters collected are 
```
ceilometer_pipeline_meters:
  - "cpu"
  - "compute.instance.booting.time"
  - "network.incoming.bytes"
  - "network.outgoing.bytes"
  - "image.size"
  - "image.download"
  - "image.serve"
  - "volume.size"
  - "snapshot.size"
  - "backup.size"
  - "volume.backup.size"
  - "disk.device.read.bytes"
  - "disk.device.write.bytes"
  - "disk.device.read.requests"
  - "disk.device.write.requests"
 ```
gnocchi archive policy
```
{
  "aggregation_methods": [
    "max",
    "sum",
    "mean"
  ],
  "back_window": 0,
  "definition": [
    {
      "points": 8760,
      "timespan": "365 days, 0:00:00",
      "granularity": "1:00:00"
    },
    {
      "points": 4032,
      "timespan": "14 days, 0:00:00",
      "granularity": "0:05:00"
    }
  ],
  "name": "custom"
}
```

### What is result that you expected
I want more aggressive metricd processing.  What if I reduce the `metric_processing_delay` to `10`?

**Comment by tomm144** [comment]
We have similiar config (with redis) and we had same issue. 
In our case helped to clean up old resources and metrics. 
Tons of data are stored in mysql database so you should check it too.
Hope it helps.

**Comment by tomm144** [comment]
@manuvakery1 take a look at command gnocchi batch delete.

**Comment by manuvakery1** [comment]
@tomm144 what have done to clear the resource_history table?

**Comment by tomm144** [comment]
@manuvakery1  we delete old metrics/resources with this command gnocchi batch resource delete "ended_at<'-XXX days'" .
This delete unused metric and resources and delete them from the database. 
Btw. it is not good idea (for us) mark all old metrics for deleting in one command  :-)

**Comment by manuvakery1** [comment]
@tomm144 I have cleared a lot of old resources. now the resource-history table has only 300k entries whereas it was 8000k. But I don't see any significant improvement in processing speed.  Also I noticed the metricd worker takes almost 20 minutes in between each metric set processing. 
```
[infra-admin@infrastructure0 ~]$ sudo grep -arn 'gnocchi.chef: Measures for' /var/log/gnocchi/ | grep 210371
/var/log/gnocchi/metricd.log:26516:2022-03-29 11:30:50,004 [210371] DEBUG    gnocchi.chef: Measures for 146 metrics processed
/var/log/gnocchi/metricd.log:35655:2022-03-29 11:49:18,820 [210371] DEBUG    gnocchi.chef: Measures for 121 metrics processed
/var/log/gnocchi/metricd.log:46134:2022-03-29 12:08:00,564 [210371] DEBUG    gnocchi.chef: Measures for 121 metrics processed
/var/log/gnocchi/metricd.log:62539:2022-03-29 12:30:13,389 [210371] DEBUG    gnocchi.chef: Measures for 146 metrics processed
/var/log/gnocchi/metricd.log:76887:2022-03-29 12:51:57,561 [210371] DEBUG    gnocchi.chef: Measures for 146 metrics processed
/var/log/gnocchi/metricd.log:87919:2022-03-29 13:09:49,464 [210371] DEBUG    gnocchi.chef: Measures for 121 metrics processed
/var/log/gnocchi/metricd.log:102009:2022-03-29 13:31:40,453 [210371] DEBUG    gnocchi.chef: Measures for 148 metrics processed
/var/log/gnocchi/metricd.log:114752:2022-03-29 13:49:30,345 [210371] DEBUG    gnocchi.chef: Measures for 121 metrics processed
/var/log/gnocchi/metricd.log:128266:2022-03-29 14:10:41,596 [210371] DEBUG    gnocchi.chef: Measures for 147 metrics processed
/var/log/gnocchi/metricd.log:143655:2022-03-29 14:32:27,847 [210371] DEBUG    gnocchi.chef: Measures for 147 metrics processed
/var/log/gnocchi/metricd.log:154478:2022-03-29 14:50:16,784 [210371] DEBUG    gnocchi.chef: Measures for 121 metrics processed
```

**Comment by chungg** [comment]
i would probably disable [metricd]greedy processing if you're using redis. when i tried it (years ago), it was more noise than anything.

i've never tried the s3 storage or mysql indexer but to debug you may want to try the `status` rest endpoint to get some more performance numbers as it's not possible to tell based on the logs above. you can also vaguely tell by monitoring the metricd daemon (checking cpu utilisation). it should be effectively max'ing your cpu when it's going (for better or worse)

if i remember correctly, i don't think you'd ever get to 10s refresh intervals (you'd need an absurd amount of metricd workers). it'd probably make more sense to just pass in `refresh=true` to ensure you want latest measures are factored in result.

**Comment by manuvakery1** [comment]
@chungg I will try disabling [metricd]greedy. In my case, the bottleneck was swift (aggregate storage) PUT operation taking too much time. I am using the s3 driver with swift s3api so that metrics will be stored in a single container instead of a container per metric. Swift PUT operations are very slow because the container has 500k+ objects. I need to find out a way to migrate old metrics and use the swift driver.  Swift works better with a lot of containers with not too many objects than a single container with more than 100K objects or I have to use container sharding.

**Comment by manuvakery1** [comment]
Closing this issue as the issue is not with gnocchi but  backend storage is slow
