### ISSUE TITLE
gnocchi doesn't match incoming metric names against archive_policy_rules

### ISSUE THREAD

**Issue by yadneshk** [gnocchixyz/gnocchi#1263]
Before reporting an issue on Gnocchi, please be sure to provide all necessary
information.

### Which version of Gnocchi are you using
`4.4.1`

### How to reproduce your problem
- Create an archive-policy-rule in gnocchi to map all `volume` metrics to archive policy `medium`
```
$ openstack metric archive-policy-rule list 
+---------+---------------------+----------------+
| name    | archive_policy_name | metric_pattern |
+---------+---------------------+----------------+
| vol-med | medium              | volume.*       |
| default | low                 | *              |
+---------+---------------------+----------------+
```

- Create a volume resource in openstack
```
$ openstack volume list 
+--------------------------------------+------------+-----------+------+---------------------------------+
| ID                                   | Name       | Status    | Size | Attached to                     |
+--------------------------------------+------------+-----------+------+---------------------------------+
| d8a8ddd5-fb71-4831-8cba-ac39999a0ddd | vol1       | available |    1 |                                 |
+--------------------------------------+------------+-----------+------+---------------------------------+
```

### What is the result that you get

- The archive policy `high` is assigned to it which is defined in `/etc/ceilometer/pipeline.yaml`. 
```
openstack metric list | grep d8a8ddd5-fb71-4831-8cba-ac39999a0ddd
| 0f3af7a8-d021-4a1a-97a9-f86640d85928 | high | volume.size | GB  | d8a8ddd5-fb71-4831-8cba-ac39999a0ddd |

$ cat /etc/ceilometer/pipeline.yaml 
---
sources:
    - name: meter_source
      meters:
          - "*"
      sinks:
          - meter_sink
sinks:
    - name: meter_sink
      publishers:
          - gnocchi://?archive_policy=high&filter_project=service
```

### What is result that you expected
- This metric should've been created with `medium` archive policy

### Additional info
- Gnocchi only tries to match the metric names to archive policy rules if the archive policy name in the incoming metric in `None`
https://github.com/gnocchixyz/gnocchi/blob/master/gnocchi/rest/api.py#L571-L589

- It seems that all incoming metrics from ceilometer have `archive_policy_name` set to it which either comes from `pipeline.yaml` or is set to `ceilometer-low` which is the default AP. Due to which the metric names are not matched to AP rules
```
(Pdb) definition
{'name': 'volume.size', 'archive_policy_name': 'high', 'unit': 'GB'}
(Pdb) definition.get('archive_policy_name')
'high'
```

**Comment by tobias-urdin** [comment]
Isn't that the entire point of the API and the integration from Ceilometer into Gnocchi that ceilometer would be able to select this, it seems intentional, no?

**Comment by tobias-urdin** [comment]
Closing, feel free to open if still relevant, thanks!
