### ISSUE TITLE
Release of 4.6.0

### ISSUE THREAD

**Issue by berendt** [gnocchixyz/gnocchi#1330]
In Kolla we currently build images from master because https://github.com/gnocchixyz/gnocchi/commit/b52f7414d595e8d765fde50992f2776a77b98de6 is not yet part of a release.

Our OpenStack distribution is based on Kolla. We plan our next major release in around 4 weeks. Our first pre-release is in the next week. It would be nice to be able to include a container image build of a Gnocchi release instead of the Gnocchi master branch.

Is it possible to do a 4.6.0 release of Gnocchi next week?

**Comment by tobias-urdin** [comment]
fixed

**Comment by berendt** [comment]
@tobias-urdin Thanks!
