### ISSUE TITLE
gnocchi.osci.io website is missing Sphinx docs

### ISSUE THREAD

**Issue by bkranendonk** [gnocchixyz/gnocchi#1382]
Sphinx docs on https://gnocchi.osci.io/ website are not available for the last week. Please fix this 😇 

### How to reproduce your problem

Go to https://gnocchi.osci.io/

### What is the result that you get

HTTP Server file browser

### What is result that you expected

Sphinx docs.

**Comment by Callum027** [comment]
Nearly 2 months on, this appears to still have not been fixed.

Can an organisation member please respond to this issue?

**Comment by tobias-urdin** [comment]
I've reached out to OSCI (osci.io) in #openinfra channel on Libera IRC. The build logs is available here https://gnocchi.osci.io/build-logs/gnocchi.log and indicates an error, feel free to also reach out to them if it happens in the future.

**Comment by tobias-urdin** [comment]
The site is working again
