### ISSUE TITLE
Could you do a release please, so we can use the Redis TLS support?

### ISSUE THREAD

**Issue by artificial-intelligence** [gnocchixyz/gnocchi#1389]
Redis sentinel/TLS support was added in https://github.com/gnocchixyz/gnocchi/pull/1376

we want to support sentinel and tls in kolla, but there is currently no gnocchi release with TLS support for redis so it would be very kind if you could do a release:

https://review.opendev.org/c/openstack/kolla-ansible/+/909188

Thanks!

**Comment by tobias-urdin** [comment]
I will look into this today or tomorrow.

**Comment by tobias-urdin** [comment]
CI needs fixing and this https://github.com/gnocchixyz/gnocchi/issues/1392 might block until that's resolved

**Comment by tobias-urdin** [comment]
redis changes backport to 4.6 series and 4.6.3 released https://github.com/gnocchixyz/gnocchi/releases/tag/4.6.3
