### ISSUE TITLE
Logging in gnocchi-upgrade is partially skipped

### ISSUE THREAD

**Issue by jd** [gnocchixyz/gnocchi#16]
See https://bugs.launchpad.net/gnocchi/+bug/1664275

**Comment by BigChief45** [comment]
Will `oslo_log` still be the preferred logging library for Gnocchi even after separating from OpenStack?

Also, it seems `gnocchi-upgrade` does not support the `-v` option.

**Comment by jd** [comment]
I'm trying to figure out how to replace oslo.log in the long run.
