### ISSUE TITLE
when running gnocchi-config-generator there are missing depends

### ISSUE THREAD

**Issue by cons0l3** [gnocchixyz/gnocchi#191]
Hi,

I have installed gnocchi 4.0.0 on ubuntu 17.04 (x64) via `pip install gnocchi`. It is running on python 2.7.13 in a virtualenv (15.1.0).

When executing `gnocchi-config-generator` the following modules are missing:
futurist,
tooz,
oslo_db
lz4

I have managed to install them manually and got gnocchi-config-generator executing, but I would argue for a smooth start the dependencies should be included into the requirements.txt or the setuptools config or whereever...

Cheers
Carsten

**Comment by jd** [comment]
Hi @cons0l3 !

I would argue for reading the documentation first though :)

I quote http://gnocchi.xyz/install.html#id1

> Depending on the drivers and features you want to use (see Project Architecture for which driver to pick), you need to install extra variants using, for example:
> `pip install gnocchi[postgresql,ceph,keystone]`

But this page also current mention `pip install` so I sent   https://github.com/gnocchixyz/gnocchi/pull/192 to remove it.
