### ISSUE TITLE
aggregation: issue when one of the resource is no more updated

### ISSUE THREAD

**Issue by jd** [gnocchixyz/gnocchi#2]
See https://bugs.launchpad.net/gnocchi/+bug/1479429

**Comment by BigChief45** [comment]
I think this has been fixed? Or at least partly fixed? I can see that the resources are already been created with a `ended_at` attribute, as suggested by @sileht

**Comment by sileht** [comment]
That was more a Ceilometer/Aodh issue that a Gnocchi one, but yes that have been fixed, gnocchi have ended_at and Ceilometer now set it. Aodh ignore resource with ended_at set.
