### ISSUE TITLE
NoAuth Headers

### ISSUE THREAD

**Issue by BigChief45** [gnocchixyz/gnocchi#20]
Currently *noauth* mode needs `X-User-Id` and `X-Project-Id` headers for the request. I also noticed that the `NoAuthHelper` inherits from `KeystoneAuthHelper`.

Does this mean that `X-User-Id` and `X-Project-Id` actually represent an OpenStack _user_ and _project_, respectively? If this is the case, I am bit confused on why, since the *noauth* mode shouldn't be related to OpenStack at all, if I am not mistaken.

**Comment by jd** [comment]
The `noauth` mode is deprecated. It uses the Keystone headers for historical reasons.

My question would be then, why did you open this bug in the end? Is there anything that you need that's not covered by `basic` mode?

**Comment by BigChief45** [comment]
My bad. I was not aware that *noauth* was deprecated. I think the docs could be updated regarding this.

> My question would be then, why did you open this bug in the end? Is there anything that you need that's not covered by basic mode?

Not really. I am just testing the different authentication methods and I figured *noauth* would be the simplest one to start right away.

Closing this issue.

**Comment by jd** [comment]
The deprecation is recent and is written here http://gnocchi.xyz/releasenotes/unreleased.html#deprecation-notes

If you think of any better place we can write it, just let us know or send a PR ;)

**Comment by BigChief45** [comment]
I think the misleading was because of the sample configuration generated by `gnocchi-config-generator` command. When inspecting the sample configuration I can still see *noauth*:

```ini
[api]
#
# From gnocchi
#

# Authentication mode to use. (string value)
# Allowed values: keystone, noauth, basic
#auth_mode = basic
```

Was trying to find a way to remove it but I think this is somehow automatically generated by `oslo_config`? I would guess it will remove itself when the `NoAuthHelper` is removed?

**Comment by jd** [comment]
Yes it will be removed from the doc as soon as it's removed indeed. :)
