### ISSUE TITLE
Gnocchi + Keystone = The request you have made requires authentication. (HTTP 401)

### ISSUE THREAD

**Issue by jthiyagu** [gnocchixyz/gnocchi#205]
Hi,
I have Openstack ocata configured on Ubuntu 16.0.4-2 and for telemetry service I have ceilometer configured with gnocchi . I followed the document from http://gnocchi.xyz/   to install gnocchi but unfortunately my gnocchi authentication with keystone is not working (auth_mode = keystone). 
           With auth_mode=noauth   works fine. 

My Gnocchi config uses mysql database for Indexer  , files for storage and keystone for authentication. 

Below is the error message ... 
gnocchi status
The request you have made requires authentication. (HTTP 401)
************************************************************
openstack metric resource-type list
Failed to discover available identity versions when contacting http://hsdatactlr1.engba.veritas.com:35357/v3. Attempting to parse version from URL.
Internal Server Error (HTTP 500)

Below is my configuration details ...... 

*******************************************************
Ceilometer : 

cat /etc/ceilometer/ceilometer.conf | grep -iv ^[#]  | sed -e '/^$/d'
[DEFAULT]
meter_dispatchers=gnocchi
event_dispatchers=gnocchi
transport_url = rabbit://openstack:hyperscale@hsdatactlr1.engba.veritas.com
[api]
[collector]
[compute]
[coordination]
[cors]
[cors.subdomain]
[database]
[dispatcher_file]
[dispatcher_gnocchi]
filter_service_activity = False
archive_policy = low
[dispatcher_http]
[event]
[hardware]
[ipmi]
[keystone_authtoken]
auth_uri = http://hsdatactlr1.engba.veritas.com:5000
auth_url = http://hsdatactlr1.engba.veritas.com:35357
memcached_servers = hsdatactlr1.engba.veritas.com:11211
auth_type = password
project_domain_name = default
user_domain_name = default
project_name = service
username = ceilometer
password = hyperscale
[matchmaker_redis]
[meter]
[notification]
[oslo_concurrency]
[oslo_messaging_amqp]
[oslo_messaging_kafka]
[oslo_messaging_notifications]
[oslo_messaging_rabbit]
[oslo_messaging_zmq]
[oslo_middleware]
[oslo_policy]
[polling]
[publisher]
[publisher_notifier]
[rgw_admin_credentials]
[service_credentials]
auth_type = password
auth_url = http://hsdatactlr1.engba.veritas.com:5000/v3
project_domain_name = default
user_domain_name = default
project_name = service
username = ceilometer
password = hyperscale
interface = internalURL
region_name = RegionOne
[service_types]
[storage]
[vmware]
[xenapi]

**************************************************************************************
Gnocchi Config : 

cat /etc/gnocchi/gnocchi.conf | grep -iv ^[#]  | sed -e '/^$/d'
[DEFAULT]
verbose = true
log_dir = /var/log/gnocchi
[api]
auth_mode = keystone
[archive_policy]
[cors]
[database]
connection = mysql+pymysql://gnocchi-common:hyperscale@hsdatactlr1.engba.veritas.com/gnocchidb
[healthcheck]
[incoming]
[indexer]
url = mysql+pymysql://gnocchi:hyperscale@hsdatactlr1.engba.veritas.com/gnocchi
[keystone_authtoken]
auth_uri = http://hsdatactlr1.engba.veritas.com:5000
auth_url = http://hsdatactlr1.engba.veritas.com:35357
memcached_servers = hsdatactlr1.engba.veritas.com:11211
auth_type = password
project_domain_name = default
user_domain_name = default
project_name = service
username = gnocchi-common
password = hyperscale
interface = internalURL
region_name = RegionOne
service_token_roles_required = True
[metricd]
[oslo_middleware]
[oslo_policy]
[statsd]
[storage]
file_basepath = /var/lib/gnocchi

***********************************************************************************
Gnocchi api config : 

cat /etc/gnocchi/api-paste.ini | grep -iv ^[#]  | sed -e '/^$/d'
[composite:gnocchi+noauth]
use = egg:Paste#urlmap
/ = gnocchiversions_pipeline
/v1 = gnocchiv1+noauth
/healthcheck = healthcheck
[composite:gnocchi+basic]
use = egg:Paste#urlmap
/ = gnocchiversions_pipeline
/v1 = gnocchiv1+noauth
/healthcheck = healthcheck
[composite:gnocchi+keystone]
use = egg:Paste#urlmap
/ = gnocchiversions_pipeline
/v1 = gnocchiv1+keystone
/healthcheck = healthcheck
[pipeline:gnocchiv1+noauth]
pipeline = http_proxy_to_wsgi gnocchiv1
[pipeline:gnocchiv1+keystone]
pipeline = http_proxy_to_wsgi keystone_authtoken gnocchiv1
[pipeline:gnocchiversions_pipeline]
pipeline = http_proxy_to_wsgi gnocchiversions
[app:gnocchiversions]
paste.app_factory = gnocchi.rest.app:app_factory
root = gnocchi.rest.VersionsController
[app:gnocchiv1]
paste.app_factory = gnocchi.rest.app:app_factory
root = gnocchi.rest.V1Controller
[filter:keystone_authtoken]
use = egg:keystonemiddleware#auth_token
oslo_config_project = gnocchi
[filter:http_proxy_to_wsgi]
use = egg:oslo.middleware#http_proxy_to_wsgi
oslo_config_project = gnocchi
[app:healthcheck]
use = egg:oslo.middleware#healthcheck
oslo_config_project = gnocchi

[pipeline:main]
pipeline = gnocchi_auth keystone_authtoken gnocchi.........

**********************************************************************

**Comment by chungg** [comment]
what OS_* values are you using when running command line?

**Comment by jthiyagu** [comment]
root@hsdatactlr1:~# cat ~/admin-openrc
export OS_PROJECT_DOMAIN_NAME=Default
export OS_USER_DOMAIN_NAME=Default
export OS_PROJECT_NAME=admin
export OS_USERNAME=admin
export OS_PASSWORD=hyperscale
export OS_AUTH_URL=http://hsdatactlr1.engba.veritas.com:35357/v3
export OS_IDENTITY_API_VERSION=3
export OS_IMAGE_API_VERSION=2
root@hsdatactlr1:~#

**Comment by jthiyagu** [comment]
"root@hsdatactlr1:~# cat ~/admin-openrc
export OS_PROJECT_DOMAIN_NAME=Default
export OS_USER_DOMAIN_NAME=Default
export OS_PROJECT_NAME=admin
export OS_USERNAME=admin
export OS_PASSWORD=hyperscale
export OS_AUTH_URL=http://hsdatactlr1.engba.veritas.com:35357/v3
export OS_IDENTITY_API_VERSION=3
export OS_IMAGE_API_VERSION=2
root@hsdatactlr1:~#
"

**Comment by jthiyagu** [comment]
cat ~/admin-openrc
export OS_PROJECT_DOMAIN_NAME=Default
export OS_USER_DOMAIN_NAME=Default
export OS_PROJECT_NAME=admin
export OS_USERNAME=admin
export OS_PASSWORD=xxxxxxxxx
export OS_AUTH_URL=http://hsdatactlr1.engba.veritas.com:35357/v3
export OS_IDENTITY_API_VERSION=3
export OS_IMAGE_API_VERSION=2

**Comment by chungg** [comment]
i'm not sure what `service_token_roles_required` is but you should also include

> export OS_AUTH_TYPE=password

when using client with authentication: http://gnocchi.xyz/gnocchiclient/shell.html#authentication-method

**Comment by chungg** [comment]
i'm going to assume this resolved issue
