### ISSUE TITLE
Gnocchi & Grafana

### ISSUE THREAD

**Issue by YuXiaoCoder** [gnocchixyz/gnocchi#268]
Hello, I'm not configured Gnocchi & Grafana on OpenStack Cloud.
The use of CLI on Kolla:  gnocchi resource list --type image --endpoint=172.18.50.61:8041
Result:
Unexpected exception for 172.18.50.61:8041/v1/resource/image?: No connection adapters were found for '172.18.50.61:8041/v1/resource/image?'

Asking for help, thank you.

**Comment by chungg** [comment]
"No connection adapters were found" is that a Kolla error?

**Comment by sileht** [comment]
On Thu, Aug 03, 2017 at 05:37:03AM -0700, YuXiao wrote:
>Hello, I'm not configured Gnocchi & Grafana on OpenStack Cloud.
>The use of CLI on Kolla:  gnocchi resource list --type image --endpoint=172.18.50.61:8041

maybe "gnocchi resource list --type image --endpoint=http://172.18.50.61:8041" ?
-- 
Mehdi Abaakouk
mail: sileht@sileht.net
irc: sileht

**Comment by YuXiaoCoder** [comment]
I tried 'gnocchi resource list --type image --endpoint=http://172.18.50.204:8041', but 'The request you have made requires authentication. (HTTP 401)', I don't know how to authenticate.

I tried 'source /etc/kolla/admin-openrc.sh', Asking for help, Thank you.
![admin-openrc](https://user-images.githubusercontent.com/26297513/28950099-caf9af0e-78f3-11e7-84d2-6b337d368353.png)

How do I use Grafana?

![grafana](https://user-images.githubusercontent.com/26297513/28950213-8d7d5652-78f4-11e7-884b-6135b695c896.png)

**Comment by sileht** [comment]
On Fri, Aug 04, 2017 at 01:10:01AM +0000, YuXiao wrote:
>I tried 'gnocchi resource list --type image --endpoint=http://172.18.50.204:8041', but 'The request you have made requires authentication. (HTTP 401)', I don't know how to authenticate.
>
>I tried 'source /etc/kolla/admin-openrc.sh', Asking for help, Thank you.
>![admin-openrc](https://user-images.githubusercontent.com/26297513/28950099-caf9af0e-78f3-11e7-84d2-6b337d368353.png)

Did you read http://gnocchi.xyz/gnocchiclient/shell.html#openstack-keystone-authentication ?

Can you paste the content of admin-openrc.sh ?

In think kolla have missed to put "export OS_AUTH_TYPE=password" inside.

-- 
Mehdi Abaakouk
mail: sileht@sileht.net
irc: sileht

**Comment by YuXiaoCoder** [comment]
Thank You.
