### ISSUE TITLE
"The request you have made requires authentication."

### ISSUE THREAD

**Issue by giangnvbk1989** [gnocchixyz/gnocchi#276]
Hi all,

I installed Ceilometer with Gnocchi as backend (file,mysql,keystone) by following the documents [https://docs.openstack.org/project-install-guide/telemetry/ocata/install-base-ubuntu.html](url) and [http://gnocchi.xyz/install.html. ](url). I can get data by running command lines like "gnocchi resource list", and so on. 
However, I cannot retrieve the outputs by using curl or web browsers. It results error code 401 
**"{"error": {"message": "The request you have made requires authentication.", "code": 401, "title": "Unauthorized"}}**. I am using keystone for authentication of gnocchi. I guess this issue relates to keystone. I have checked gnocchi.conf (keystone section) several times and I used api-paste.ini from https://github.com/openstack/cookbook-openstack-telemetry/blob/master/files/api-paste.ini but I don't know why it still has that problem (which consequently results problem when I integrate Gnocchi with Grafana which is my final goal). Does anyone have idea on this? 

This is my **gnocchi.conf:**
[DEFAULT]
debug = true
verbose = true
log_file = /var/log/gnocchi/gnocchi.log

[api]
workers = 1
host = controller
port = 8041
paste_config = /usr/local/lib/python2.7/dist-packages/gnocchi/rest/api-paste.ini
auth_mode = keystone

[database]
backend = sqlalchemy

[indexer]
url = mysql+pymysql://gnocchi:****@controller/gnocchi

[storage]
driver = file
file_basepath = /var/lib/gnocchi
coordination_url = file:///var/lib/gnocchi/locks

[keystone_authtoken]
auth_type = password
auth_url = http://controller:5000/v3
project_domain_name = Default
user_domain_name = Default
project_name = service
username = gnocchi
password = *****
interface = internalURL
region_name = RegionOne
memcached_servers = controller:11211

[cors]
allowed_origin = "http://controller:3000"

and my **api-paste.ini:** with some modifications from https://github.com/openstack/cookbook-openstack-telemetry/blob/master/files/api-paste.ini

[pipeline:main]
pipeline = cors gnocchi+auth

[composite:gnocchi+auth]
use = egg:Paste#urlmap
/ = gnocchiversions_pipeline
/v1 = gnocchiv1+auth
/healthcheck = healthcheck

[composite:gnocchi+keystone]
use = egg:Paste#urlmap
/ = gnocchiversions_pipeline
/v1 = gnocchiv1+auth
/healthcheck = healthcheck

[composite:gnocchi+keystone]
use = egg:Paste#urlmap
/ = gnocchiversions_pipeline
/v1 = gnocchiv1+keystone
/healthcheck = healthcheck

[composite:gnocchi+remoteuser]
use = egg:Paste#urlmap
/ = gnocchiversions_pipeline
/v1 = gnocchiv1+auth
/healthcheck = healthcheck

[pipeline:gnocchiv1+auth]
pipeline = http_proxy_to_wsgi gnocchiv1

[pipeline:gnocchiv1+keystone]
pipeline = http_proxy_to_wsgi keystone_authtoken gnocchiv1

[pipeline:gnocchiversions_pipeline]
pipeline = http_proxy_to_wsgi gnocchiversions

[app:gnocchiversions]
paste.app_factory = gnocchi.rest.app:app_factory
root = gnocchi.rest.VersionsController

[app:gnocchiv1]
paste.app_factory = gnocchi.rest.app:app_factory
root = gnocchi.rest.V1Controller

[filter:keystone_authtoken]
use = egg:keystonemiddleware#auth_token
oslo_config_project = gnocchi

[filter:http_proxy_to_wsgi]
use = egg:oslo.middleware#http_proxy_to_wsgi
oslo_config_project = gnocchi

[app:healthcheck]
use = egg:oslo.middleware#healthcheck
oslo_config_project = gnocchi

[filter:cors]
paste.filter_factory = oslo_middleware.cors:filter_factory
oslo_config_project = gnocchi

Many thanks!!!

**Comment by giangnvbk1989** [comment]
This is log from gnocchi-api when I run the command line "gnocchi resource list"
**[14/Aug/2017 17:07:11] "GET /v1/resource/generic HTTP/1.1" 200 15729**

While reload browser with the same method http://controller:8041/v1/resource/generic, I got this  log
[**14/Aug/2017 17:09:23] "GET /v1/resource/generic HTTP/1.1" 401 114** on the gnocchi-api running screen.

**Comment by jd** [comment]
If you use your browser, no Keystone token is provided so the request is denied. You cannot do any request to Gnocchi API without being authenticated with a Keystone token first.

**Comment by giangnvbk1989** [comment]
Thank you for your reply Jd,
So there is no problem with my Gnocchi setup?
It results like that error when I configure Gnocchi as data source of Grafana in proxy mode.
I got **"Gnocchi authentication failure"** on the Grafana configuration page and **[14/Aug/2017 17:09:23] "GET /v1/resource/generic HTTP/1.1" 401 114** on the gnocchi-api running screen. I also tried to configure Gnocchi as data source of Grafana in direct mode. It shows **Keystone failure: No response status code, is CORS correctly configured ?** though I have configured CORS in gnocchi.conf and keystone.conf as written in [http://gnocchi.xyz/grafana.html](url). What is my problem here? Many thanks!

**Comment by jd** [comment]
Your problem is likely Grafana configuration. Can you show your Grafana configuration screen?

**Comment by giangnvbk1989** [comment]
Hi jd,
The following is the screenshot of my Grafana configuration: 
![screenshot from 2017-08-15 13-44-11](https://user-images.githubusercontent.com/5535717/29314827-1d87b584-81c0-11e7-9b48-ecc14295e555.png)

**Comment by giangnvbk1989** [comment]
Hi again, 
The following is the screenshot of my Granfana configuration with Gnocchi in proxy mode.
![screenshot from 2017-08-15 17-47-22](https://user-images.githubusercontent.com/5535717/29323685-ed43012c-81e1-11e7-993a-0506f995de80.png)

It is exactly the same configuration as in [https://julien.danjou.info/blog/2017/gnocchi-collectd-setup](url)

**Comment by jd** [comment]
The first screenshot is ok, but you don't need `basic auth`, just uncheck it.

**Comment by giangnvbk1989** [comment]
Hi jd,
I have unchecked and it still has that error.
![screenshot from 2017-08-15 18-25-04](https://user-images.githubusercontent.com/5535717/29325173-17e83fe6-81e7-11e7-95c7-df2a177d0b19.png)

**Comment by giangnvbk1989** [comment]
One more thing is that I don't see any log in /var/log/grafana/grafana.log while adding Gnocchi in direct mode. But there are some logs generated while adding Gnocchi in proxy mode. **t=2017-08-15T18:28:15+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/v1/resource status=401 remote_addr=192.168.x.x time_ms=2 size=114 referer=http://192.168.x.x:3000/datasources/edit/7**

**Comment by jd** [comment]
Direct mode makes your browser send the request itself, not going through Grafana, so that's normal there's nothing in Grafana log. You can pop up your browser debugging console to see the network requests it sends to Keystone.

It seems to me Keystone does not have CORS properly configured/enabled. Can you double check that?

Using your browser debugging console can help.

**Comment by giangnvbk1989** [comment]
Hi jd,

This is [cors] section in my keystone.conf:

[cors]
allowed_origin = http://controller:3000 #for grafana support
allow_methods = GET,PUT,POST,DELETE,PATCH
allow_headers = X-Auth-Token,X-Openstack-Request-Id,X-Subject-Token,X-Project-Id,X-Project-Name,X-Project-Domain-Id,X-Project-Domain-Name,X-Domain-Id,X-Domain-Name

In web debugger mode, I got the following error in the console while adding Gnocchi.
**Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://controller:5000/v3/auth/tokens. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).**

I don't know if my keystone.conf is correct
This is [cors] section in my gnocchi.conf
[cors]
allowed_origin = http://controller:3000

Thank you!

**Comment by jd** [comment]
Are you sure you access Grafana using `http://controller:3000`?
The referer above shows `http://192.168.0.1:3000/datasources/edit/7` so it's likely you set the wrong URL in `allowed_origin`. Try to set `http://192.168.0.1:3000` instead.

**Comment by giangnvbk1989** [comment]
Hi jd,

I have changed configuration files to use host ip address instead of hostname as follows.
My **gnocchi.conf**
[cors]
allowed_origin = http://192.168.254.100:3000

My **keystone.conf** [cors] section
[cors]
allowed_origin = http://192.168.254.100:3000 #for grafana support
allow_methods = GET,PUT,POST,DELETE,PATCH
allow_headers = X-Auth-Token,X-Openstack-Request-Id,X-Subject-Token,X-Project-Id,X-Project-Name,X-Project-Domain-Id,X-Project-Domain-Name,X-Domain-Id,X-Domain-Name

The screenshot of my Grafana configuration page:
![screenshot from 2017-08-16 14-06-46](https://user-images.githubusercontent.com/5535717/29362403-2f5001f0-828c-11e7-9df5-4a43bca7b64a.png)

The error from console in web debugging mode.
**Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://192.168.254.100:5000/v3/auth/tokens. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).**

**Comment by jd** [comment]
Are you really accessing Grafana via `http://192.168.254.100:3000` in your browser window?

**Comment by giangnvbk1989** [comment]
Hi jd,
Yes. It is like the following screenshot.
![screenshot from 2017-08-16 15-26-53](https://user-images.githubusercontent.com/5535717/29365459-631c47f4-8297-11e7-8dc1-244bb5667638.png)

**Comment by jd** [comment]
Ok, that looks good. Can you check in your browser the requests it does? IIRC it should send a first `OPTIONS` request to see if CORS allows the subsequent requests to Keystone. That's probably what fails.

**Comment by giangnvbk1989** [comment]
Yes, you are right. The following sceenshot shows that. But I still don't know how to fix it.
![screenshot from 2017-08-16 15-40-24](https://user-images.githubusercontent.com/5535717/29366110-62cebf00-8299-11e7-9e80-2e1cfe04470b.png)

**Comment by jd** [comment]
Can you include all the details of the request? Like the headers. That'd help debugging.

**Comment by giangnvbk1989** [comment]
Yes, it is the following.
![screenshot from 2017-08-16 16-00-57](https://user-images.githubusercontent.com/5535717/29367126-3307728c-829c-11e7-81e6-96c015a1c099.png)

**Comment by jd** [comment]
Ok, so the problem is CORS in Keystone, definitely.
You said you have this in keystone.conf:
```
[cors]
allowed_origin = http://192.168.254.100:3000 #for grafana support
allow_methods = GET,PUT,POST,DELETE,PATCH
allow_headers = X-Auth-Token,X-Openstack-Request-Id,X-Subject-Token,X-Project-Id,X-Project-Name,X-Project-Domain-Id,X-Project-Domain-Name,X-Domain-Id,X-Domain-Name
```

Can you remove the comment at the end of `allowed_origin` line? I'm not sure that it is actually read as a comment, I think it's used as a value. You should just have the URL. Then make sure you restart Keystone API service.

**Comment by giangnvbk1989** [comment]
Hi jd,
oh that's my stupid mistake. I removed the comment and it works now. However, I have learnt more about Gnocchi & Grafana now.
Thank you very much for your help.

**Comment by jd** [comment]
Cool, glad you have it working!
