### ISSUE TITLE
Using InfluxDB as storage backend

### ISSUE THREAD

**Issue by Hangdong-Zhang** [gnocchixyz/gnocchi#296]
As I konwn, InfluxDB is a modern time series platforms, How about we using Redis as incoming DB and InfluxDB as storage backend ? Is it more effiecent ?

**Comment by jd** [comment]
This already has been discussed tons of time. One of the latest thread:
http://lists.openstack.org/pipermail/openstack-dev/2016-August/100604.html

There was an experimental driver in Gnocchi for InfluxDB a while back, but it was not maintained and has been removed.

InfluxDB does not offer any advantage compared to the storage Gnocchi use currently, which is faster and more scalable. It'd be even better to use the `file` driver IMHO.
