### ISSUE TITLE
GET /v1/resources/generic has no facility to limit output

### ISSUE THREAD

**Issue by jd** [gnocchixyz/gnocchi#3]
See https://bugs.launchpad.net/gnocchi/+bug/1479830

**Comment by sileht** [comment]
This is 80% implemented, we can limit the output and do the pagination, but response body does not
provide 'links' because that will break the API.

I just found rfc5988 that explain how to do the same with links in headers instead of the response body.
.

**Comment by BigChief45** [comment]
Is there any API specification in particular that the API follows or should follow? Like [JSON API](http://jsonapi.org/) for example.

**Comment by jd** [comment]
Not really. We supposedly follow the OpenStack API WG but I don't think nobody ever looked what they pushed. So any spec or RFC that makes sense to follow, we do. :)
