### ISSUE TITLE
pytimeparse is slower than Pandas

### ISSUE THREAD

**Issue by chungg** [gnocchixyz/gnocchi#302]
creating an issue to track performance:

```
>>> values = ["-%s seconds" % i for i in xrange(10)]
>>> valuesbig = ["-%s seconds" % i for i in xrange(100)]
>>> valuesbigger = ["-%s seconds" % i for i in xrange(1000)]

>>> timeit.timeit("[to_timespan(v, True) for v in values]", "import pytimeparse; from __main__ import to_timespan, values, valuesbig, valuesbigger", number=1000)
0.21312499046325684
>>> timeit.timeit("pd.to_timedelta(values, box=False)", "import pandas as pd; from __main__ import values, valuesbig, valuesbigger", number=1000)
0.17818307876586914

>>> timeit.timeit("[to_timespan(v, True) for v in valuesbig]", "import pytimeparse; from __main__ import to_timespan, values, valuesbig, valuesbigger", number=1000)
1.2020509243011475
>>> timeit.timeit("pd.to_timedelta(valuesbig, box=False)", "import pandas as pd; from __main__ import values, valuesbig, valuesbigger", number=1000)
0.8025670051574707

>>> timeit.timeit("[to_timespan(v, True) for v in valuesbigger]", "import pytimeparse; from __main__ import to_timespan, values, valuesbig, valuesbigger", number=1000)
11.29253888130188
>>> timeit.timeit("pd.to_timedelta(valuesbigger, box=False)", "import pandas as pd; from __main__ import values, valuesbig, valuesbigger", number=1000)
7.07202410697937
```

**Comment by chungg** [comment]
tried dateparser, it's 100x slower than pytimeparse

**Comment by chungg** [comment]
tried parsedatetime, it's 7x slower than pytimeparse.

**Comment by jd** [comment]
Are you sure it's the hottest spot right now when ingesting metrics via the API?

**Comment by chungg** [comment]
i don't know if it's slowest part but i do vaguely remember it effecting the batch write performance. it's why i changed it to pandas originally. that said, i don't recall the overall effect but it was probably closer to 20%. i'll time it.

**Comment by sileht** [comment]
With https://gist.github.com/sileht/5ce2163fa23b4376f094edb4dee47332 and https://github.com/wroberts/pytimeparse/pull/14

$ python test.py
https://github.com/wroberts/pytimeparse/pull/14
0.0486791133881
0.643970966339
8.90360498428

pandas
0.195980072021
2.0291531086
20.7331631184

**Comment by sileht** [comment]
Wait... it's faster, but result is wrong ...

**Comment by sileht** [comment]
I fixed it, the result is the same, ouf :)

**Comment by sileht** [comment]
python test.py
https://github.com/wroberts/pytimeparse/pull/14
0.0925829410553
0.937630176544
9.8606569767

pandas
0.197290182114
2.04476308823
20.7988040447

**Comment by chungg** [comment]
tried it without list comprehension... your patch is still better \o/!

```
>>> for v in ["values", "valuesbig", "valuesbigger"]:
...     print(timeit.timeit(
...         "[timeparse(v) for v in %s]" % v,
...         "from pytimeparse.timeparse import timeparse; from __main__ import values, valuesbig, valuesbigger",
...         number=1000
...     ))
... 
0.102396011353
1.07618784904
11.0475950241
```

```
>>> for v in ["values", "valuesbig", "valuesbigger"]:
...     print(timeit.timeit(
...         "pd.to_timedelta(%s, box=False)" % v,
...         "import pandas as pd; from __main__ import values, valuesbig, valuesbigger",
...         number=1000
...     ))
... 
0.140416145325
1.15974092484
11.5684561729
```

**Comment by sileht** [comment]
http://tempora.readthedocs.io/en/latest/#tempora.parse_timedelta

python test.py
tempora
0.0813210010529
0.792341947556
7.77149200439
https://github.com/wroberts/pytimeparse/pull/14
0.0896768569946
0.928112983704
9.97173810005

pandas
0.204941987991
2.11232614517
21.8589720726

It doesn't support timedelta that start with minus, but that not a big deal.

**Comment by jd** [comment]
pytimeparse 1.1.7 is out with @sileht fix.
