### ISSUE TITLE
max_pool_connections should be configurable for the botocore s3 driver

### ISSUE THREAD

**Issue by leandroreox** [gnocchixyz/gnocchi#303]
When testing the s3 driver on gnocchi 4 with plenty of metrics the urrlib3 pool that is created by the boto3 adapter to talk to s3, gets full almost instantaneously, it can be hacked changing the adapter.py file but should be configurable on gnocchi.conf , something like:

s3_ max_pool_connections 

Since max_pool_connections is the parameter that should be passed on the init of the s3 client to be passed trough the http adapter

**Comment by jd** [comment]
If you have references on where this should be changed in the code, that'd be good help for buildling a patch.

**Comment by leandroreox** [comment]
This PR fix this issue: https://github.com/gnocchixyz/gnocchi/pull/304
