### ISSUE TITLE
resource attribute of GET /v1/metric/<id> is incomplete

### ISSUE THREAD

**Issue by sileht** [gnocchixyz/gnocchi#310]
On GET /v1/metric/<id> we don't join the instance_type table, so additional attributes are not show.

**Comment by jd** [comment]
Which attributes?

**Comment by sileht** [comment]
For example if the metric is associated to an 'collectd' resource type.

The 'resource' attribute of the metric have only the 'generic' resource attributes. For 'collectd' type, 'host' attribute will be missing.

**Comment by jd** [comment]
I guess we could add a `details` parameter to the query to fetch more information.

**Comment by sjamgade** [comment]
Can this not be part of the client ? 
Instead adding a features to server
The client can ask the server for `resource_type` info and add it to the dict

**Comment by sum12** [comment]
Can this not be part of the client ? Instead adding a features to server.
The client can ask the server for `resource_type` info and add it to the dict
