### ISSUE TITLE
error in installing of gnocchi with pip in debain linux

### ISSUE THREAD

**Issue by pratikmakune3** [gnocchixyz/gnocchi#311]
I have installed gnocchi in debain linux with pip tool.  Whenver I am running gnocchi with command "gnocchi-api" I am getting following error.

Traceback (most recent call last):
  File "/usr/local/bin/gnocchi-api", line 37, in <module>
    server = wss.make_server(args.host, args.port, build_wsgi_app())
  File "/home/ramesh/.local/lib/python2.7/site-packages/gnocchi/rest/app.py", line 143, in build_wsgi_ap
p
    return load_app(service.prepare_service())
  File "/home/ramesh/.local/lib/python2.7/site-packages/gnocchi/service.py", line 54, in prepare_service
    version=pbr.version.VersionInfo('gnocchi').version_string())
  File "/home/ramesh/.local/lib/python2.7/site-packages/oslo_config/cfg.py", line 2471, in __call__
    self._check_required_opts()
  File "/home/ramesh/.local/lib/python2.7/site-packages/oslo_config/cfg.py", line 3129, in _check_requir
ed_opts
    raise RequiredOptError(opt.name, group)
oslo_config.cfg.RequiredOptError: value required for option url in group [indexer]
r

Shall i get any assistance on this.........Please

**Comment by sileht** [comment]
Gnocchi is complaining about 'url'  missing in the configuration file.

I guess you haven't configure it yet.

Take a look to http://gnocchi.xyz/install.html#configuration

**Comment by pratikmakune3** [comment]
I have a file called gnocchi.conf file in current working directory. But where to modify in this ,could you pease tell me

**Comment by sileht** [comment]
As the message said group 'indexer', option 'url'.

**Comment by jd** [comment]
@pratikmakune3 You should start by reading the documentation:

http://gnocchi.xyz/install.html#configuration-file

**Comment by pratikmakune3** [comment]
can somebody tell me how can we invoke a gnocchi-api since it is not a .sh file and documentation says that we should install it through pip

**Comment by pratikmakune3** [comment]
need help

**Comment by pratikmakune3** [comment]
j

**Comment by chungg** [comment]
http://gnocchi.xyz/operating.html the documentation tells you already.
