### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by ramesh-chowdeshetty** [gnocchixyz/gnocchi#312]
I installed gnocchi through pip command. but i cant find  gnocchi.conf file anywhere in my system. could you please some body help me. here is my system configuration

debain linux,
installed pip through sudo apt-get install python-pip
then installed pip install gnocchi[postgresql,ceph,keystone]

**Comment by sileht** [comment]
The file have to be generated and filled, everything is explain here: http://gnocchi.xyz/install.html#configuration,
