### ISSUE TITLE
Metric listing do not include accessible metrics

### ISSUE THREAD

**Issue by david-hill** [gnocchixyz/gnocchi#314]
Hi guys,

   Gnocchi metric list is pretty much broken.  Let me explain this: 
1) When ceilometer creates a metric, it uses the ceilometer user / project
2) When "gnocchi metric list" is ran, it takes the user and project of the current user
3) This will always be empty for non-admin users

Also, for some reasons, I can't get more than 1004 metrics on a given system.   I tried finding a hard coded limit and the only one close to that is max_limit that is set at 1000.   Does this make sense?

Thank you very much,

David Hill

**Comment by jd** [comment]
Hi David,

The metric limit might be due to the CLI not using paging, which is an issue opened here https://github.com/gnocchixyz/python-gnocchiclient/issues/4

Gnocchi metric list is supposed to list metric created by users, which as you correctly noted, are not created by the user but by Ceilometer.

The resource created by Ceilometer are however exposed to users and their metric are also accessible to users. They are easy to see by using `gnocchi resource list` and `gnocchi resource show`.

It's not really possible to list metric accessible by users right now, because the ACL engine is based on _oslo.policy_ which does not allow that. We'll probably need to replace that engine at some time to allow to express such permissions.

**Comment by david-hill** [comment]
Hello Julien,

    That's where I started my investigation and found out the database counted 550k entries from the ceilimeter user alone ... and no other user ids.  Would you have an idea of why the "gnocchi metric list" would only return 1004 elements put of 550k ?

David Hill

On Sep 1, 2017, at 04:50, Julien Danjou <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi David,

The metric limit might be due to the CLI not using paging, which is an issue opened here gnocchixyz/python-gnocchiclient#4<https://github.com/gnocchixyz/python-gnocchiclient/issues/4>

Gnocchi metric list is supposed to list metric created by users, which as you correctly noted, are not created by the user but by Ceilometer.

The resource created by Ceilometer are however exposed to users and their metric are also accessible to users. They are easy to see by using gnocchi resource list and gnocchi resource show.

It's not really possible to list metric accessible by users right now, because the ACL engine is based on oslo.policy which does not allow that. We'll probably need to replace that engine at some time to allow to express such permissions.

**Comment by jd** [comment]
> Would you have an idea of why the "gnocchi metric list" would only return 1004 elements put of 550k ?

Yes, I just told you:

> The metric limit might be due to the CLI not using paging, which is an issue opened here gnocchixyz/python-gnocchiclient#4<gnocchixyz/python-gnocchiclient#4>

The default `[api]max_limit` is 1000, so that's around that it stops listing metrics, and the client does not yet do paging automatically so it does not try to get the next 1000 (for 550 times in your case).

**Comment by chungg** [comment]
you'll need to pass in a marker to get the next page of items. or i imagine you could give a new limit size but that might just overload your SQL driver.

**Comment by david-hill** [comment]
I tried changing the max_limit to 10000 and still received 1000 but I think it's because I restarted gnocchi services instead of the httpd wsgi service.   Btw, is there a way to restart only one part of the services running under httpd or am I doomed to restart all other services too in a production environment  which might have some impacts as always?

On 2017-09-01 08:34 AM, gord chung wrote:

you'll need to pass in a marker to get the next page of items. or i imagine you could give a new limit size but that might just overload your SQL driver.

**Comment by chungg** [comment]
right, you'll need to restart your api to see change.

don't use apache :p. use uwsgi.

**Comment by david-hill** [comment]
is that an available choice using tripleo?   I'll have to dig for that ...

On 2017-09-01 08:40 AM, gord chung wrote:

right, you'll need to restart your api to see change.

don't use apache :p. use uwsgi.

**Comment by jd** [comment]
I don't think TripleO provides uwsgi. Your next best chance is to have the container support, which will avoid that.
