### ISSUE TITLE
need help on how to change ip address for gnocchi api to 0.0.0.0

### ISSUE THREAD

**Issue by ramesh-chowdeshetty** [gnocchixyz/gnocchi#315]
Could you please somebody tell me how I can bind gnocchi-api to 0.0.0.0 , so that i can access in my local system since it is in cloud

**Comment by Asu4ni** [comment]
Try running the api server using uwsgi. See [here](http://gnocchi.xyz/operating.html#running-api-as-a-wsgi-application). You can set the ip with 'http' option.

And actually if you don't know how to bind a certain ip to it, you could make a nat rule to reset the destination from your host ip to the ip gnocchi-api uses.

**Comment by chungg** [comment]
if you're using master, it should use uwsgi by default. also, what Asu4ni said :+1: 

closing this.
