### ISSUE TITLE
need help on providing authorization header in request

### ISSUE THREAD

**Issue by ramesh-chowdeshetty** [gnocchixyz/gnocchi#316]
when i try to create metric through v1/metric,  i am getting 401 unauthorized error.  As document said , i need to provide admin username in authorization header for basic authentication . Could you please some one tell me the format for basic authentication request

**Comment by chungg** [comment]
pass in a header like https://github.com/gnocchixyz/gnocchi/blob/4407cba46e4ff3a901e14be6e1809a4193ce6d0f/gnocchi/tests/functional/gabbits/archive-rule.yaml#L22

seems like it needs to be encoded in something. *shrugs*

**Comment by chungg** [comment]
should mention it needs to be base64 encoded as per https://tools.ietf.org/html/rfc7617

**Comment by ramesh-chowdeshetty** [comment]
I am getting 415 Unsupported Media Type error while sending measures into metric , can somebody help me on this

**Comment by jd** [comment]
Your `Content-Type` header is wrong.
