### ISSUE TITLE
HTTP "403 Forbidden" from command line in my fresh DevStack environment

### ISSUE THREAD

**Issue by Hangdong-Zhang** [gnocchixyz/gnocchi#317]
A few days ago, I installed a DevStack environment with the latest code. When I run any command of Gnocchi, such as: gnocchi resource list, there was a "403 Forbidden" response. The error is:
[The error of 403 Forbidden.txt](https://github.com/gnocchixyz/gnocchi/files/1273579/The.error.of.403.Forbidden.txt)

When I added:
```
<Directory />
        Require all granted
</Directory>
```
in /etc/apache2/sites-available/gnocchi.conf, the error disappeared.

**Comment by jd** [comment]
@chungg does this look legit?

**Comment by chungg** [comment]
@jd um, yeah. you'll probably need it if you're accessing your devstack from another machine. not sure where this is proposing to add it to.

**Comment by Hangdong-Zhang** [comment]
Actually, I run commands in the devstack, not other machine.

What I want to say is, at least, we should give "granted" to /usr/local/bin/, because the start-up program gnocchi-api was here.
![_20170905102420](https://user-images.githubusercontent.com/29223464/30042562-a60585d4-9224-11e7-87ba-b08cb51f4990.png)

And, I checked apache2.conf,  Directory / was denied, and /usr/local/ was not in the "granted" list.
![_20170905102933](https://user-images.githubusercontent.com/29223464/30042680-5ffc0ec2-9225-11e7-8a94-a372872a7ced.png)

**Comment by jd** [comment]
Is Gnocchi the only program in devstack having its WSGI script in /usr/local/bin?

**Comment by Hangdong-Zhang** [comment]
I guess yes.
aodh and horizon used the same method with gnocchi to configure WSGI.
aodh was in /var/www/ where was "granted" by apache2.conf. 
horizon was in /opt/stack/ and it give "granted" itself.

Other service used the method of "ProxyPass", the conf file is like:
![_20170905165323](https://user-images.githubusercontent.com/29223464/30053332-faddab82-925a-11e7-85b5-997c1836b4ec.png)

The following is all conf files of WSGI in devstack, FYI.
[The conf file of OpenStack services under apache2 in devstack.zip](https://github.com/gnocchixyz/gnocchi/files/1276664/The.conf.file.of.OpenStack.services.under.apache2.in.devstack.zip)

**Comment by chungg** [comment]
what version of ceilometer do you have installed? ie what's the commit id you're running off of.

**Comment by Hangdong-Zhang** [comment]
@chungg I used the master, no any other codes. When I run "git log":
The latest commit id of ceilometer is:  3de27d2855479dbadf9f1146fb1a122968dcfb1e
The latest commit id of gnocchi is: 70555bf48b05339d326fe2ccaa021cd21573dd81

**Comment by chungg** [comment]
hmm... it seems that gnocchi's apache configuration is pretty standard. aodh and gnocchi seem pretty similar in setup:

https://github.com/gnocchixyz/gnocchi/blob/b3a05e42abaa9dcbe8a1d03168bc2c3ea30060e8/devstack/plugin.sh#L157

https://github.com/openstack/aodh/blob/master/devstack/plugin.sh#L68

i don't use apache (and i'm using fedora) so i don't have an environment setup.

**Comment by SuderPawel** [comment]
Also I found that issue. [Here](https://stackoverflow.com/a/46337524/1702557) is posted information what to do to fix it.

**Comment by chungg** [comment]
seems fixed...
