### ISSUE TITLE
Gnocchi High Availability

### ISSUE THREAD

**Issue by hassan091** [gnocchixyz/gnocchi#319]
What are the High availability options available in Gnocchi and how can i configure it? please guide me through it as I am new to Gnocchi.

**Comment by jd** [comment]
You can run any number of API endpoint and metricd. So just run many of them on any number of hosts you want.

**Comment by hassan091** [comment]
What you have described is I guess, this is the scenario of single Gnocchi database and multiple API endpoints on multiple host. I am more concerned about replicating the data itself contained in Gnocchi. how is this possible?

**Comment by jd** [comment]
Set up a replication for your indexer (PostgreSQL or MySQL) and use a storage backend such as a Ceph or Swift.

**Comment by chungg** [comment]
we need to document this?

**Comment by jd** [comment]
@chungg I don't think maintaining a documentation on how to set up *SQL or Ceph/Swift is a good idea for us. Unless you think or something else?

**Comment by chungg** [comment]
for sure not how to install SQL or Ceph. was thinking just having references for Galera or Pacemaker... but i guess it's kind of too detailed. *shrugs*

**Comment by hassan091** [comment]
I think you should document the HA guide and mention the parallel technologies being used only as a reference. This will help novice users like us to setup HA in an efficient manner

**Comment by chungg** [comment]
by 'HA guide' do you mean the HA guide in OpenStack? we can try to add stuff there but Gnocchi isn't an OpenStack project anymore (although we fully support that use case)

**Comment by hassan091** [comment]
yeah in OpenStack and Gnocchi too, or any HA solution that can guarantee protection of data.
