### ISSUE TITLE
need help on archive policies

### ISSUE THREAD

**Issue by ramesh-chowdeshetty** [gnocchixyz/gnocchi#327]
I want to store raw data into gnocchi and later on i want to aggregate it. how can i create a metric without any aggregation methods(archive policies). Is it possible in gnocchi, can somebody help me

**Comment by jd** [comment]
You can't. You need an aggregation, at worst 1 nanosecond. But I would not advise it if you don't sent datapoints every nanoseconds.

You can use something like 1 second aggregation if you send data every second though, and later re-aggregate as you need.
