### ISSUE TITLE
needed info on high archive policy

### ISSUE THREAD

**Issue by ramesh-chowdeshetty** [gnocchixyz/gnocchi#332]
i created metrics with high archive policy, but i cant able to store morethan 467 records into metric.
could someone help me. I have 600 records with 1s granularity

**Comment by jd** [comment]
You need to provide more information about what you are doing, what you get and what you expect instead. Otherwise, it's impossible to help you.

**Comment by ramesh-chowdeshetty** [comment]
I am having a csv file consisting of 600 records with timestamp and values are columns. I am uploading this data into gnocchi metric through rest call. but only 467 records are retrieved through get request.

**Comment by jd** [comment]
Can you provide **detailed** information, such as your CSV, your code, your archive policy configuration, etc?

**Comment by ramesh-chowdeshetty** [comment]
Sorry i a unable upload file here


I am just having a csv file with time and value. till 467 i am able to get all records. after 467 it is not taking data into consideration. I am using builtin high archive policy.

**Comment by jd** [comment]
Unless you provide data and code, it's impossible to help you. Repeating the same thing over and over again is not going to improve the situation.
