### ISSUE TITLE
missing  records while reading 

### ISSUE THREAD

**Issue by ramesh-chowdeshetty** [gnocchixyz/gnocchi#337]
I am having 685 measures in a csv file.
I made an python rest api to store all measures into a metric with "high" archive policy. below I uploaded all code. the issue I am facing here is i am only retrieve 467 records from metric. Can someone help me to sort out this issue.

[FourHundredRecordsCsv.zip](https://github.com/gnocchixyz/gnocchi/files/1295210/FourHundredRecordsCsv.zip)

Let me know in you need any clarification

**Comment by jd** [comment]
The CSV file you sent has data over 2 years whereas the archive policy high defines a retention period of 1 year. That might be a problem at some point.

Also
`headers = {'content-type': 'application/json','content-length':'198','Authorization':'Basic     YWRtaW46aG90aWZ5MTU2'}`

I don't think the `Content-Length` is always the same, I don't really the point of setting it yourself.

**Comment by ramesh-chowdeshetty** [comment]
you means to say there is no need to supply content-length while inserting measures into a metric

**Comment by ramesh-chowdeshetty** [comment]
I need a policy with granularity 1 second and for 10 years of data and 100000 measures maximum, Could you please assist me to create archive policy

**Comment by ramesh-chowdeshetty** [comment]
{
  "back_window": 0,
  "definition": [
    {
      "granularity": "1s",
      "timespan": "1 hour"
    },
    {
      "points": 100000,
      "timespan": "3650 day"
    }
  ],
  "name": "ts1"
}




is that correct policy  to store ten years data with 1 sec granularity

**Comment by chungg** [comment]
you cannnot have 1 second granularity for 10 years and 100K points... there are over 31M seconds in a year alone... 10 years is 10x that...

i think you should read what an archive policy: http://gnocchi.xyz/operating.html#how-to-define-archive-policies. please realise that gnocchi does not store raw datapoints

what you defined is two aggregates: one storing 3600points at 1s granularity (1hr), and the other storing 100Kpoints over 3650days (roughly 2min granularity)
