### ISSUE TITLE
Resource Type Inheritance

### ISSUE THREAD

**Issue by Asu4ni** [gnocchixyz/gnocchi#341]
My idea is that each newly created resource type could inherit existed ones and all the attributes of the inherited resource types could be used in the new one. And each type except 'generic' at least inherit one type 'generic'. Thus, 'project_id', 'creator', etc., wouldn't have to be treated differently but like attributes, and they could be put into 'generic' beforehand.

This is just my thought. Do anyone find this useful? Or it's overkill?

**Comment by jd** [comment]
That's a good idea, and we actually discuss a bit already in older bug reports. I'm not sure of the value of it, I think it could be a bit overkill. That would help to solve problems like https://github.com/gnocchixyz/gnocchi/issues/9 but it also forces users to think about inheritance before hand – unless we can provide a way to alter it later.

**Comment by Asu4ni** [comment]
@jd 
> it also forces users to think about inheritance before hand – unless we can provide a way to alter it later.

I'm thinking that we could have a field like 'inherit_from' just like 'name'. Those could be modified I supposed. But there's a problem that what if there were already some resources with the type one was about to modify. Would it work?

**Comment by Asu4ni** [comment]
And that things get complicated if a parent resource type gets modified.

**Comment by chungg** [comment]
> And that things get complicated if a parent resource type gets modified.

i don't know if we should have inheritance specifically for that reason. we could support creating a resource that just clones another resources attributes on create so we don't have to relationship between the two after initial creation.

i'm just curious, but how often are you creating new resources types? this is probably a use case we never considered.

**Comment by Asu4ni** [comment]
@chungg I agree. It's a feature that'll seldom be used and quite difficult to implement. I guess I close this for now.

**Comment by chungg** [comment]
for the record, i didn't say i was against it. i was just curious if you had a use case which required many different resources types. but since it's not a big issue for you, i'm ok with leaving it :)

**Comment by Asu4ni** [comment]
@chungg No, I don't have a case. I just thought of the idea while I was looking into the api.

**Comment by chungg** [comment]
cool cool :)
