### ISSUE TITLE
stable docs missing REST API usage

### ISSUE THREAD

**Issue by chungg** [gnocchixyz/gnocchi#349]
going to gnocchi.xyz, if looking at stable branches (http://gnocchi.xyz/stable_4.0/index.html, http://gnocchi.xyz/stable_3.1/index.html), the REST API Usage option is missing from table of contents but it can be viewed if you jump to link directly http://gnocchi.xyz/stable_3.1/rest.html

it also says for some reason:

> Warning: This document is for the development version of Gnocchi. The main version is stable/4.0.

similar to master

**Comment by jd** [comment]
I think this is what @sileht is trying to fix with https://github.com/gnocchixyz/gnocchi/pull/345

**Comment by sileht** [comment]
https://github.com/gnocchixyz/gnocchi/pull/345 should be the fix.

I also work on not getting into this again with:
https://github.com/gnocchixyz/gnocchi/pull/348
https://github.com/gnocchixyz/gnocchi/pull/347

Tomorrow I will test if multiversion pass with "warning as error" enabled
