### ISSUE TITLE
need to make timespan infinity

### ISSUE THREAD

**Issue by ramesh-chowdeshetty** [gnocchixyz/gnocchi#362]
I want to create new archive policy with 1 second granularity with infinity timespan. Is it possible make this happen in gnocchi because i will get bulk data from sensors will be stored into gnocchi automatically through my pipeline. I cant verify my timespan in my data  since data will not be exposable. Could you please somone help me

**Comment by chungg** [comment]
i don't understand your infinity argument. ultimately, you will still want to control how long you retain data for. i imagine you could just declare 1s granularity and 1 year timespan? or 2 year timespan? or 5 year?

i'm not understanding why bulk data from sensors changes the retention period of your data.

**Comment by jd** [comment]
You can anyway just create an archive policy with `granularity` only set leaving timespan empty, so it will have infinite retention.
