### ISSUE TITLE
need help on archive policy  creation

### ISSUE THREAD

**Issue by ramesh-chowdeshetty** [gnocchixyz/gnocchi#380]
I created an archive policy like below

{
    "definition": [
        {
            "points": 3600,
            "timespan": "1:00:00",
            "granularity": "0:00:01"
        }
    ],
    "back_window": 0,
    "name": "test",
    "aggregation_methods": [
        "mean"
    ]
}

By using this policy I created a metric with id e2d447c3-8e69-4ba2-ba14-ec2e7ef00393, and I am inserting measures like below

[
  {
    "timestamp": "2017-09-18 12:46:07",
    "value": 0
  },
  {
    "timestamp": "2017-09-18 12:46:07",
    "value": 12000
  },
  {
    "timestamp": "2017-09-18 12:46:07",
    "value": 20
  },
  {
    "timestamp": "2017-09-18 12:46:07",
    "value": 200000
  }
  ]

while retrieving measures I am not getting mean of [0,12000,20,200000] instead i am getting 200000 as aggregated value. below is the results of retrieving measures if above metric

[
    [
        "2017-09-18T12:46:07+00:00",
        1,
        200000
    ]
]

the value 200000 here is last measures value not mean aggregated value of [0,12000,20,200000]

what can be the reason and how it is aggregated

**Comment by jd** [comment]
All your values have the same timestamps. So only the last one is used.

**Comment by ramesh-chowdeshetty** [comment]
According to archive policy i have created , it should take mean of all values right

**Comment by chungg** [comment]
no. because they are all the exact same timestamp. if you had separated them by some time it would've taken all of them.

for example:
- if you had separated them by a second each, then you would be given back all 4 points.
- if you had separated them by a nanosecond each, then you would be given back 1 point but the value being the aggregated mean of all the points.
