### ISSUE TITLE
How to modify a archival policy rule?

### ISSUE THREAD

**Issue by ayush12030** [gnocchixyz/gnocchi#386]
Hey,

I had a question. Suppose I was using the default archival policy rule, which basically matches everything and maps it to archival policy "low". Now i deleted this rule and created another one which maps everything to "medium".

How can I update the exciting metrics to follow this rule in future?

**Comment by jd** [comment]
You can't. Once a metric has an archive policy, it's forever. We should probably add that into documentation so it's clearer.

**Comment by chungg** [comment]
i think the closest thing you can do is to modify the 'low' policy so it retains more data. i believe you can only change the timespan though (you can't modify the granularity itself)

so basically, what jd said.
