### ISSUE TITLE
Which storage back-ends to choose?

### ISSUE THREAD

**Issue by yjLiInSky** [gnocchixyz/gnocchi#387]
Gnocchi currently offers File、Ceph、Swift、S3、Redis.  i have a chose between Ceph and Swift. what is the advantage of them? Could you provide more information about those storage? thanks a lot.

**Comment by jd** [comment]
Ceph is better (faster) than Swift because Gnocchi leverages RADOS rather than an HTTP API.

**Comment by yjLiInSky** [comment]
Thank you very much for your answer. Ceph can provide a storage system with three functions for object storage, block storage, and file system storage. And which one is used?

**Comment by jd** [comment]
Object storage.

**Comment by chungg** [comment]
i should mention most of my testing/development is done against ceph. not sure what other experience dev team has (@sileht maintains a ceph cluster as well i believe, not sure what else)

another difference the ceph driver has is that, under default deployment, it has at least 12 less READ operations than other drivers when doing computations.

**Comment by thiagodasilva** [comment]
@jd @yjLiInSky, IIUC, If the Ceph driver is leveraging RADOS directly, then it is not using Ceph's Object Storage as that typically refers to RGW and the HTTP API. Most of the time when people refer to ceph providing block, file and object they are thinking of rdb, cephfs and rgw which sits atop RADOS. Gnocchi's ceph driver goes directly to RADOS bypassing rdb, cephfs and rgw.

Extra details:
Yes, the low-level underlying architecture in ceph is also an object storage system, but not in the sense of what most people expect of an object storage system and a REST interface to access it.

**Comment by jd** [comment]
Thanks @thiagodasilva!

**Comment by jd** [comment]
I think it's clear now in the doc. Closing.
