### ISSUE TITLE
notifier goes crazy after emptying incoming

### ISSUE THREAD

**Issue by chungg** [gnocchixyz/gnocchi#397]
so, the incoming notifier seems to work really well in terms of improving real-time job scheduling. it clears the incoming storage really fast (not official testing, i just think it's moving well)

but one thing i noticed was after it clears incoming storage, it seems to keep attempting to process storage for a while afterwards until eventually it returns to whatever processing_delay was set. for example, my environment is set to processing_delay = 60 but for at least 60s after reporter tells me incoming is empty, the processing workers are still trying to process sacks non-stop.

there seems to be a backlog of process events which it isn't clearing.

**Comment by chungg** [comment]
also, each worker is maxing out a CPU each during this time where it's nothing but 'processing' empty storage.

**Comment by chungg** [comment]
we need to reconsider notifier system. some things i think are:

- only sub to keys we know we want.
- not be calling run_watchers every single event message
- consider ignoring a key sack which just processed "recently"

right now i think it's a really big liability in terms of scalability as is.

**Comment by chungg** [comment]
my test is i have:
- 18 metricd, 512 sacks
- send ~2.4 million individual measures over 40K metrics. (so there will be effectively 2.4 million notifications)

will clear incoming in ~2min and for 1+min after cleared, it will keep attempting to process sacks (ie, it will try to process sacks all 512 sacks hundreds/thousands of times even though it's empty)

**Comment by jd** [comment]
Do you have some debug logs from metricd?
I'd be curious to know for example if this is because the filler thread is still pushing stuff into the queue for example.

**Comment by chungg** [comment]
is there a specific log you need? i'm not running debug.

i only switched https://github.com/gnocchixyz/gnocchi/blob/master/gnocchi/cli/metricd.py#L237 to INFO which is why i know it was attempting to do work even after it was empty.

**Comment by jd** [comment]
Yeah I'd like to know if https://github.com/gnocchixyz/gnocchi/blob/master/gnocchi/cli/metricd.py#L166 is being hammered.

**Comment by chungg** [comment]
yes, it's being hammered (almost crashed the computer i'm streaming logs from).

it gives me 70K+ hits on that log (for ~1.5min) after reporter has already told me incoming is empty (it report every 20s)

**Comment by chungg** [comment]
actually nevermind, i looked at my test client again, and it's pushing items in batch so it's 40K keyspace notifications, not ~2.4 million.

i imagine if i did not do this in batch, it would explode.
