### ISSUE TITLE
Allow to copy a metric with a different archive policy

### ISSUE THREAD

**Issue by jd** [gnocchixyz/gnocchi#4]
See https://bugs.launchpad.net/gnocchi/+bug/1501352

**Comment by BigChief45** [comment]
I've been thinking on different ways to implement this. 

The most suitable approach in my opinion would be to use the current `POST /metric` endpoint to create a new metric, but we also pass a `source` attribute with the existing metric ID we want to clone. At the same time we can pass an archive policy in the request to assign this archive policy to the metric copy.

Feedback is appreciated.

**Comment by jd** [comment]
That sounds like a neat design.

**Comment by chungg** [comment]
i've never quite understood how this fix would work. if you have a metric with policy = [{1min granularity for 10 days}, { 5min granularity for 30days}] how would you re-map that policy to [{10s granularity for 5 days}, {10min granualrity for 100 days}, {1day granularity for 365 days}]... series does it use to calculate 10s, 10min, and 1 day series? the 1min or 5min series? also, what if the aggregation_methods don't match? what is the aggregation_method you use?

or maybe this is not what we mean by copy metric to new policy.

**Comment by jd** [comment]
@chungg if you read the original bug report, the case you mention is exactly the one I say we can't do.

The problem is that the other way around also has a problem. It's subtle but if you have the points:

* 10:10 28
* 10:11 30
* 10:12 50
* 10:15 1000

If you average on 5 min you get:
* 10:10 = 36
* 10:15 = 1000

If you average on 1 hour you geT:
* 10:00 = 277

But if you transform your 5 minutes average in 1 hour you get:
* 10:00 = (36+1000)/2 = 519

which is not exactly the same thing – it's average of average.

I think the guy that opened the bug 2 years ago did not think that through. So no, I don't think that's possible. In the original bug report, the suggestion was made to rather change the archive policy. I think it's smarter.

I'll close this.
