### ISSUE TITLE
ceph: use 'more' field when retrieving all omaps

### ISSUE THREAD

**Issue by chungg** [gnocchixyz/gnocchi#45]
ceph luminous will include a 'more' field which will help tell us whether there are more omaps to read rather than our current guessing of 'if it doesn't give us limit (aka 1000 items), it's probably the end'

probably not important for a while.

https://github.com/ceph/ceph/pull/12950

**Comment by tobias-urdin** [comment]
The get_omap_vals python binding we call internally calls the new val2 func
