### ISSUE TITLE
rest: operator like with uuid won't work

### ISSUE THREAD

**Issue by sileht** [gnocchixyz/gnocchi#450]
### How to reproduce your problem

do a resource search with `id like "foobar"`

### What is the result that you get

DEBUG [pifpaf.drivers] uwsgi[11888] output:   File "/workspace/sileht/os_dev/stack/gnocchi/client/.tox/py27/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1398, in _handle_dbapi_exception
DEBUG [pifpaf.drivers] uwsgi[11888] output:     util.raise_from_cause(newraise, exc_info)
DEBUG [pifpaf.drivers] uwsgi[11888] output:   File "/workspace/sileht/os_dev/stack/gnocchi/client/.tox/py27/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
DEBUG [pifpaf.drivers] uwsgi[11888] output:     reraise(type(exception), exception, tb=exc_tb, cause=cause)
DEBUG [pifpaf.drivers] uwsgi[11888] output:   File "/workspace/sileht/os_dev/stack/gnocchi/client/.tox/py27/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
DEBUG [pifpaf.drivers] uwsgi[11888] output:     context)
DEBUG [pifpaf.drivers] uwsgi[11888] output:   File "/workspace/sileht/os_dev/stack/gnocchi/client/.tox/py27/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
DEBUG [pifpaf.drivers] uwsgi[11888] output:     cursor.execute(statement, parameters)
DEBUG [pifpaf.drivers] uwsgi[11888] output: DBError: (psycopg2.ProgrammingError) operator does not exist: uuid ~~ uuid
DEBUG [pifpaf.drivers] uwsgi[11888] output: LINE 3: WHERE resource.id LIKE 'b709a41a-fe8e-5070-83d8-7ae45d62b5bb...

### What is result that you expected

An error 400 and not an error 500

**Comment by chungg** [comment]
closing
