### ISSUE TITLE
The request you have made requires authentication. (HTTP 401) - Devstack/Ocata

### ISSUE THREAD

**Issue by maestropandy** [gnocchixyz/gnocchi#452]
Before reporting an issue on Gnocchi, please be sure to provide all necessary
information.

### Gnocchi Version

> gnocchi 3.1.0

### How to reproduce your problem
Install Devstack/ocata  with below local.conf http://paste.openstack.org/show/624797/ and run "

> gnocchi resource list"

### Result I get

> gnocchi --debug resource list
> REQ: curl -g -i -X GET http://localhost:8041/v1/resource/generic? -H "Authorization: {SHA1}d4daf1cf567f14f32dbc762154b3a281b4ea4c62" -H "Accept: application/json, */*" -H "User-Agent: gnocchi keystoneauth1/2.18.0 python-requests/2.12.5 CPython/2.7.12"
> Starting new HTTP connection (1): localhost
> http://localhost:8041 "GET /v1/resource/generic HTTP/1.1" 401 114
> RESP: [401] Date: Fri, 27 Oct 2017 08:29:13 GMT Server: Apache/2.4.18 (Ubuntu) WWW-Authenticate: Keystone uri='http://30.30.0.5/identity' Content-Length: 114 Keep-Alive: timeout=5, max=100 Connection: Keep-Alive Content-Type: application/json
> RESP BODY: {"error": {"message": "The request you have made requires authentication.", "code": 401, "title": "Unauthorized"}}

###File top refer

Ceilometer.Conf http://paste.openstack.org/show/624799/
Gnocchi.conf: http://paste.openstack.org/show/624800/

Although tried with curl call to create metric as below 

> "curl -X POST http://localhost/v1/metric  -H 'content-length: 35' -H 'content-type: application/json' -d '{"archive_policy_name": "high"}'

"

Getting Error as "http://paste.openstack.org/show/624802/"

**Comment by jd** [comment]
Is your environment variable `OS_AUTH_TYPE` set to `password`?
