### ISSUE TITLE
(potential) performance degradation

### ISSUE THREAD

**Issue by chungg** [gnocchixyz/gnocchi#462]
gnocchi v4.x redis is noticeably slower in the openstack gate. note: ceilometer actually uses master so we can track down roughly when it started to suck.

looking at https://review.openstack.org/#/c/503992/ and https://review.openstack.org/#/c/509642/, the compute time per metric (using "Computed new metric * measures in *.**s" log) typically shows the mass majority of metrics are done under 0.10s with most of them hovering around 0.03-0.04s. (this is a number i've typically seen

looking at https://review.openstack.org/#/c/510919/, we have compute times hovering mostly around 0.05-0.08s

looking at https://review.openstack.org/#/c/511618/, the compute time per metric is over typically over 0.10s and generally around 0.10-0.12s where we currently sit.

this is something we should probably track? it could be related to: redis push, the threadpool tweak, openstack ci?

yes, i'm aware we shouldn't benchmark using CI. that said, we haven't done formal benchmark so we should really verify this.

**Comment by jd** [comment]
Totally OK to verify this, but as you said, CI is totally unreliable, so this information has near-zero value to me.

**Comment by chungg** [comment]
this seems to be related to greedy path... if i disable it in gate, it goes back to expected compute times.

i didn't notice this originally when i was testing so maybe it's because the load created by greedy path only becomes noticeable using gate's VMs

**Comment by chungg** [comment]
i'm going to close this. the greedy path seems to work equivalently in my environment

test case:
push 1000 resources, 20 metrics each.
send measures as a batch of 1 resource, 20 metrics, 1point for each metric 60 times to simulate 60 points per metric

in redis+file scenario, performance to clear backlog is equivalent between greedy/periodic.

since we can turn off greedy, i don't really care to look into this specific issue more.
