### ISSUE TITLE
Regular non-admin user can't get measures of his metrics. Gets the 403 response instead.

### ISSUE THREAD

**Issue by ozerovandrei** [gnocchixyz/gnocchi#464]
Hello.
I've performed an upgrade from Gnocchi 4.0 to 4.1 in my testing environment.
I have some issue related to the Gnocchi REST API.

When I'm authorized with the non-admin Keystone token I can't get measures for metrics that have resource.project_id value of my project_id.
I don't have that issue in 4.0 release.

I tested that with the following request:
`curl -XGET -H 'Content-Type: application/json' -H "X-Auth-Token: $(openstack token issue -c id -f value)" 'http://gnocchi_ip:gnocchi_port/v1/resource/SOME_RESOURCE_TYPE/RESOURCE_UUID/metric/SOME_METRIC_NAME/measures'`

I've got the 403 reply to that request, but I can successfully perform the following requests:
`GEl -XGET -H 'Content-Type: application/json' -H "X-Auth-Token: $(openstack token issue -c id -f value)" 'http://gnocchi_ip:gnocchi_port/v1/resource/SOME_RESOURCE_TYPE/RESOURCE_UUID'`

` GEl -XGET -H 'Content-Type: application/json' -H "X-Auth-Token: $(openstack token issue -c id -f value)" 'http://gnocchi_ip:gnocchi_port/v1/resource/SOME_RESOURCE_TYPE/RESOURCE_UUID/metric/SOME_METRIC_NAME'`

As far as I understand, that 403 responce is coming from there: 
[self.enforce_metric("get measures")](https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/rest/api.py#L466)

I've done some debbugging of the [MetricController](https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/rest/api.py#L432.)
What I've got, is that when I'm doing the request to a metric (_curl ...metric/SOME_METRIC_NAME_), I get the
**json.to_primitive(self.metric)** result in the [enforce()](https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/rest/api.py#L444) with the
full info about the metric with the resource info inside (**resource.created_by_user_id**, **resource.id**, **resource.revision_start**, **resource.project_id**, etc.).

But when I make the request to a measures (_curl ...metric/SOME_METRIC_NAME/measures_), I get the tiny result of the **json.to_primitive(self.metric)** without
fields of resource info (just the **resource_id** field).

I have the following rule for that request in the policy.json:
`"metric_owner": "project_id:%(resource.project_id)s",
"get measures":  "rule:admin_or_creator or rule:metric_owner",`

Because **json.to_primitive(self.metric)** doesn't have the **resource.id** in measures request, I've got the 403 responce (**"get measures"** rule just don't work in that case).

I can't find the reason of that behavior. And I don't have that issue with the Gnocchi 4.0 release.

**Comment by jd** [comment]
A good idea, if possible, would be to do a `git bisect` to see which patches introduce that change.

**Comment by zeljkokalezic** [comment]
Hi 😄 ,

I have the same problem, only difference is that I upgraded from Gnocchi 3.1.

I replaced the following line in `policy.json`:
`"get measures":  "rule:admin_or_creator or rule:metric_owner"`
with:
`"get measures":  ""`
to mitigate the issue for testing purposes, but I was wondering is there a proper workaround until bug is fixed ?

Thanks,
Zeljko

**Comment by jd** [comment]
@zeljkokalezic and you upgraded to 4.1, right?

It's likely we changed something in the retrieval code in this path.

**Comment by zeljkokalezic** [comment]
@jd Yes I upgraded to 4.1.

```
# pip show gnocchi
Name: gnocchi
Version: 4.1.1
Summary: Metric as a Service

```

**Comment by jd** [comment]
Ok, I found the culprit: it's 65e65a64d064b4e378e8af053f34f77745cc8708

I'll work on a patch. I need to write some test before to be sure we don't break this again. Stay tuned.

**Comment by ozerovandrei** [comment]
@jd it's broken again. Got the same issue with the `stable/4.1` branch.

**Comment by jd** [comment]
@ozerovandrei Can you provide more details? You say again, so it was fixed in a release?

**Comment by ozerovandrei** [comment]
@jd I tried a [2b241a6a](https://github.com/gnocchixyz/gnocchi/commit/2b241a6ae6fe1660a7e670ce5726b54d96eed670) maybe a month ago. But I can't remember if I tried it with test variant of policy `"get measures": ""` or default like `"get measures": "rule:admin_or_creator or rule:metric_owner"`. And it worked and I'm not sure right now how did it worked 😞 .

So now I've just cloned the latest variant of the `stable/4.1` branch and it's responding with 403 to only `GET v1/metric/UUID/measures` again. I will try to debug it deeper and check/compare with your previous commit again send some results here.

**Comment by ozerovandrei** [comment]
@jd sorry for a long delay.
I've test Gnocchi with the latest 4.1.3 tag and then I've tried the [2b241a6a](https://github.com/gnocchixyz/gnocchi/commit/2b241a6ae6fe1660a7e670ce5726b54d96eed670) commit.
In both cases I've tested getting resource, metric and measures from a regular user perspective and got the 403 error for a `GET measures` request.

I don't know how to correctly debug that problem. So I've just tested [enforce_metric](https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/rest/api.py#L445) method. I've added  logging into the api.py and checked the value that this method returns.

In case of `GET v1/metric/UUID` I got the following `json.to_primitive(self.metric)` result:
```
{
  "unit ": "metric_unit",
  "id ": "metric_uuid",
  "archive_policy ": {
    ...
  },
  "created_by_project_id ": "admin_project_uuid",
  "creator ": "admin_user_uuid:admin_project_uuid",
  "name ": "metric_name ",
  "resource ": {
    "id ": "resource_uuid",
    "type ": "resource_type ",
    "started_at ": "timestamp",
    "revision_start ": "timestamp",
    "created_by_user_id ": "admin_user_uuid",
    "user_id ": "regular_user_uuid",
    "project_id ": "regular_project_uuid",
    "ended_at ": "None",
    "revision_end ": "None",
    "creator ": "admin_user_uuid:admin_project_uuid ",
    "created_by_project_id ": "admin_project_uuid",
    "original_resource_id ": "resource_uuid"
  },
  "created_by_user_id ": "admin_user_uuid"
}
```

And in case of `GET v1/metric/UUID/measures` I got the following `json.to_primitive(self.metric)` result:
```
{
  "unit ": "metric_unit",
  "id ": "metric_uuid",
  "archive_policy ": {
    ...
  },
  "created_by_project_id ": "admin_project_uuid",
  "resource_id ": "resource_uuid",
  "creator ": "admin_user_uuid:admin_project_uuid",
  "name ": "metric_name ",
  "created_by_user_id ": "admin_user_uuid"
}
```

I have standard policy rules for both of that cases:
```
{
"admin_or_creator": "role:admin or user:%(creator)s or project_id:%(created_by_project_id)s",
"metric_owner": "project_id:%(resource.project_id)s",
"get measures":  "rule:admin_or_creator or rule:metric_owner",
}
```

So, in the second case, policy `rule:metric_owner` just doesn't work because json doesn't have a resource inside.

**Comment by jd** [comment]
I only fixed `/v1/resource/generic/<resource id>/metric/disk/measures`, so there might also be a bug in `/v1/metric/UUID/measures`.

**Comment by jd** [comment]
Fixed in #675 and need to backport to 4.1

**Comment by jazeltq** [comment]
When will #675  be merged?

**Comment by jd** [comment]
@jazeltq When 2 smart people will have reviewed it.

**Comment by ozerovandrei** [comment]
@jd thank you!

I've tried the latest version of `stable/4.1` branch and have no more troubles with getting measures from
```
v1/metric/UUID/measures
```
or
```
v1/resource/generic/UUID/metric/NAME/measures
``` 
as a regular Identity user.

I guess that you can close this issue when you're ready.

_Off-topic_: I'm really looking forward to `4.2` version and hope you'll release it soon. New measures batching format is looking really great as well as the Prometheus storage backend.
Thank you again 😄
