### ISSUE TITLE
periodic/batch redis

### ISSUE THREAD

**Issue by chungg** [gnocchixyz/gnocchi#472]
currently redis driver (as of 4.1) will aggregate ASAP when there is data to aggregate. this behaves differently than other drivers. i'm wondering if we should support ability to behave like other drivers (while still leveraging the fact we know which sacks to poll)

currently, redis driver has pros/cons:

pros:
- does not need to poll so it can aggregate as fast as possible and minimise work of polling
- don't poll sacks that are empty

cons:
- we can't batch to minimise aggregate storage IO, so this is max IO

i don't know if this matters much since redis isn't that durable of a storage driver anyways (or that's the reputation) so i don't know if we want to encourage data to sit on redis for extend periods.

**Comment by chungg** [comment]
this is a placeholder mainly to see if someone jumps in to say 'i want this'

**Comment by jd** [comment]
> (while still leveraging the fact we know which sacks to poll)

Correct me if I'm wrong, but I don't think this is usable. It's not possible to trust this information as a notification can be lost for whatever reasons (reboot?) so I think it's safer to just use the usual scheme and disable the notification (if asked to respect metric delay).

**Comment by chungg** [comment]
yeah, youre right. i do prefer that if we take all sacks we disable the push path completely.

**Comment by chungg** [comment]
https://github.com/gnocchixyz/gnocchi/commit/586de48d281aabae88243282687cfc3e61c21ddc
