### ISSUE TITLE
intermittent test failure

### ISSUE THREAD

**Issue by sileht** [gnocchixyz/gnocchi#474]
Sometimes this test fail:

gnocchi.tests.test_indexer.TestIndexerDriver.test_list_resources_custom_with_history
------------------------------------------------------------------------------------

Captured stderr:
~~~~~~~~~~~~~~~~
    b'Unique keys not in sort_keys. The sorting order may be unstable.'
    b''

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    b'Traceback (most recent call last):'
    b'  File "/home/tester/src/gnocchi/tests/base.py", line 59, in skip_if_not_implemented'
    b'    return func(*args, **kwargs)'
    b'  File "/home/tester/src/gnocchi/tests/test_indexer.py", line 987, in test_list_resources_custom_with_history'
    b'    self.assertEqual([r1, r2], resources)'
    b'  File "/home/tester/src/.tox/py35-mysql/lib/python3.5/site-packages/testtools/testcase.py", line 411, in assertEqual'
    b'    self.assertThat(observed, matcher, message)'
    b'  File "/home/tester/src/.tox/py35-mysql/lib/python3.5/site-packages/testtools/testcase.py", line 498, in assertThat'
    b'    raise mismatch_error'
    b'testtools.matchers._impl.MismatchError: !=:'
    b"reference = [{'col1': 'foo',"
    b"  'created_by_project_id': '',"
    b"  'created_by_user_id': '141584cd-77c9-4477-b31d-a3780499403a',"
    b"  'creator': '141584cd-77c9-4477-b31d-a3780499403a',"
    b"  'ended_at': None,"
    b"  'id': UUID('4212f8f8-0934-440d-91cc-02d7a75ebd40'),"
    b"  'metrics': {'bar': '81ad0db9-d472-43b9-9145-d266a2bc73d0',"
    b"              'foo': 'afa2c01f-f161-4f72-ad98-f81c6e89903c'},"
    b"  'original_resource_id': '4212f8f8-0934-440d-91cc-02d7a75ebd40',"
    b"  'project_id': '29fd9d9b-5d10-4f5b-b29f-403d2510479f',"
    b"  'revision_end': datetime.datetime(2017, 11, 9, 14, 50, 35, 96172, tzinfo=datetime.timezone.utc),"
    b"  'revision_start': datetime.datetime(2017, 11, 9, 14, 50, 35, 297899, tzinfo=datetime.timezone.utc),"
    b"  'started_at': datetime.datetime(2017, 11, 9, 14, 50, 35, 297889, tzinfo=datetime.timezone.utc),"
    b"  'type': 'b21afe90-6813-4207-b53e-a3c1f781cae9',"
    b"  'user_id': 'f4e009ac-b9c0-4232-b4fa-5e98c5ee7512'},"
    b" {'col1': 'bar',"
    b"  'created_by_project_id': '',"
    b"  'created_by_user_id': '141584cd-77c9-4477-b31d-a3780499403a',"
    b"  'creator': '141584cd-77c9-4477-b31d-a3780499403a',"
    b"  'ended_at': None,"
    b"  'id': UUID('4212f8f8-0934-440d-91cc-02d7a75ebd40'),"
    b"  'metrics': {'bar': '81ad0db9-d472-43b9-9145-d266a2bc73d0',"
    b"              'foo': 'afa2c01f-f161-4f72-ad98-f81c6e89903c'},"
    b"  'original_resource_id': '4212f8f8-0934-440d-91cc-02d7a75ebd40',"
    b"  'project_id': 'dc00832e-20f4-4af8-888e-33cb6b0cfb73',"
    b"  'revision_end': None,"
    b"  'revision_start': datetime.datetime(2017, 11, 9, 14, 50, 35, 96172, tzinfo=datetime.timezone.utc),"
    b"  'started_at': datetime.datetime(2017, 11, 9, 14, 50, 35, 297889, tzinfo=datetime.timezone.utc),"
    b"  'type': 'b21afe90-6813-4207-b53e-a3c1f781cae9',"
    b"  'user_id': '11cd13c6-3f35-4b01-8419-00c7977ce4f1'}]"
    b"actual    = [{'col1': 'bar',"
    b"  'created_by_project_id': '',"
    b"  'created_by_user_id': '141584cd-77c9-4477-b31d-a3780499403a',"
    b"  'creator': '141584cd-77c9-4477-b31d-a3780499403a',"
    b"  'ended_at': None,"
    b"  'id': UUID('4212f8f8-0934-440d-91cc-02d7a75ebd40'),"
    b"  'metrics': {'bar': '81ad0db9-d472-43b9-9145-d266a2bc73d0',"
    b"              'foo': 'afa2c01f-f161-4f72-ad98-f81c6e89903c'},"
    b"  'original_resource_id': '4212f8f8-0934-440d-91cc-02d7a75ebd40',"
    b"  'project_id': 'dc00832e-20f4-4af8-888e-33cb6b0cfb73',"
    b"  'revision_end': None,"
    b"  'revision_start': datetime.datetime(2017, 11, 9, 14, 50, 35, 96172, tzinfo=datetime.timezone.utc),"
    b"  'started_at': datetime.datetime(2017, 11, 9, 14, 50, 35, 297889, tzinfo=datetime.timezone.utc),"
    b"  'type': 'b21afe90-6813-4207-b53e-a3c1f781cae9',"
    b"  'user_id': '11cd13c6-3f35-4b01-8419-00c7977ce4f1'},"
    b" {'col1': 'foo',"
    b"  'created_by_project_id': '',"
    b"  'created_by_user_id': '141584cd-77c9-4477-b31d-a3780499403a',"
    b"  'creator': '141584cd-77c9-4477-b31d-a3780499403a',"
    b"  'ended_at': None,"
    b"  'id': UUID('4212f8f8-0934-440d-91cc-02d7a75ebd40'),"
    b"  'metrics': {'bar': '81ad0db9-d472-43b9-9145-d266a2bc73d0',"
    b"              'foo': 'afa2c01f-f161-4f72-ad98-f81c6e89903c'},"
    b"  'original_resource_id': '4212f8f8-0934-440d-91cc-02d7a75ebd40',"
    b"  'project_id': '29fd9d9b-5d10-4f5b-b29f-403d2510479f',"
    b"  'revision_end': datetime.datetime(2017, 11, 9, 14, 50, 35, 96172, tzinfo=datetime.timezone.utc),"
    b"  'revision_start': datetime.datetime(2017, 11, 9, 14, 50, 35, 297899, tzinfo=datetime.timezone.utc),"
    b"  'started_at': datetime.datetime(2017, 11, 9, 14, 50, 35, 297889, tzinfo=datetime.timezone.utc),"
    b"  'type': 'b21afe90-6813-4207-b53e-a3c1f781cae9',"
    b"  'user_id': 'f4e009ac-b9c0-4232-b4fa-5e98c5ee7512'}]"
    b''
    b''

**Comment by chungg** [comment]
is datetime.datetime(2017, 11, 9, 14, 50, 35, 96172) suppose to be 961720 instead of 96172? because python sees revision_end is before revision_start... ie datetime.datetime(2017, 11, 9, 14, 50, 35, 96172) < datetime.datetime(2017, 11, 9, 14, 50, 35, 297889)
