### ISSUE TITLE
Add an UDP protocol support

### ISSUE THREAD

**Issue by jazeltq** [gnocchixyz/gnocchi#496]
Ceilometer now use rest api to access gnocchi. Can we support
udp at api level? For example, we listen on a udp port, got samples, 
and save it.

**Comment by jd** [comment]
Yes, this could be done. There is support for the statsd protocol already to that purpose. Does that cover it for you? If not, why?

**Comment by jazeltq** [comment]
It can not cover, because the ceilometer do not send measures in statsd protocol, or should we add the adapter in ceilometer? and then use gnocchi statds?  Is it possible?

**Comment by jd** [comment]
Everything is possible with computers.

**Comment by jazeltq** [comment]
Yes. It is too sample. And put all into one resource....
What we should do in this issues?

**Comment by jd** [comment]
The first thing would be to lay down any requirements you might have about this protocol. I imagine you just want to use UDP for faster ingestion than TCP.

I think @sileht had a few ideas about how to make things fast for ingestion. He played with protobuf recently too, so he might have an idea about if this is a good opportunity to use that or if we should stick to something simpler such as a e.g. text protocol.

Once the protocol is designed, implementing should pretty straightforward.

**Comment by jazeltq** [comment]
It is more than tcp. Because if you configured ceilometer with gnocchi as dispatcher. It use
http and every request will go to keystone. The poor keystone is easily to hit down, or response
more slow.  
If we generate a protocol here. Then the we should also change ceilometer's udp dispatcher or 
add a new one.

**Comment by jd** [comment]
> It is more than tcp. Because if you configured ceilometer with gnocchi as dispatcher. It use
http and every request will go to keystone. The poor keystone is easily to hit down, or response
more slow.

You can configure Ceilometer to use Gnocchi without Keystone IIRC. So if that's your only reason for UDP, this is not a good one.

**Comment by jazeltq** [comment]
How? we can only make gnocchi to use noauth, but this will make everyone can change gnocchi's database.

**Comment by jd** [comment]
You could use the `remoteuser` auth mode and set up an authentication via e.g. Apache.

**Comment by jazeltq** [comment]
Oh....Can you give more details? If someone want to sent a url to gnocchi, what it will do?

**Comment by jazeltq** [comment]
i search the gnocchiclient, thereis nothing about remoteuser? If someone use gnocchiclient to connect gnocchi, he must use keystone or noauth?

**Comment by jd** [comment]
@sileht want to chime in? we should add that in Ceilometer doc.

**Comment by gyurco** [comment]
Well, I think it is better to use proper batching, we have some hundred metrics/minute, and only 2 POST requests/minute from the collector to each gnocchi-api instance.

**Comment by chungg** [comment]
@gyurco that's a great point.

**Comment by jazeltq** [comment]
well, because udp is hard to do loadblance. I want to make a tcp server that will
accept ceilometer's measures. In ceilometer, we can change the http request to 
tcp request.

The tcp server just depacked the ceilometer's measures messages.
how about this? @jd

**Comment by jd** [comment]
@jazeltq sure

**Comment by jazeltq** [comment]
I review gnocchi publisher in ceilometer. And find it mainly do three jobs.
1) post measures 
2) create resource if there is no, or the metrics hash is not same
3) update resource extra if there is
So, here in gnocchi  tcp server, i think we should do those
1) can add measures, if no resource id, we should return those resources
2) can add resource
3) can update resource
The msg protocol can be this

msg_version: 8bit: [0x01,0xff]
msg_len: 32bit: [0x00000000,0xffffffff]
msg_sign: sha-1? of others?
msg_operation:16bit: msg_measures_add/msg_resources_add/msg_resources_update
                                     0x0001                        0x0002                     0x0003
msg_payload: json?

Any suggestion?  @jd

**Comment by jd** [comment]
First, we need to split this in 2 different problems:
- the message format
- the message serialization scheme

For the format we probably need to define which operations we want to expose and how we expose them. This is the most difficult part IMHO. You can take a look at InfluxDB line protocol or statsd protocol to see how they do things. It's likely we'll need something more complete though.

For the serialization, there are plenty of choice: JSON, msgpack, protobuf, etc. I don't have a particular opinion, though I'm pretty sure JSON would be the worst choice – it's convenient over HTTP, but is not particularly efficient. @sileht might have an opinion here.

**Comment by jazeltq** [comment]
OK. I drop my opinion on JSON.  
Yes, it is a little complicated.  
What about this:
we just send the samples like udp, one by one or batch in one tcp mtu (about < 1400)and let gnocchi tcp server process samples. Then we do not need expose function like add measures
add resources and update them.

How about this @jd

**Comment by jd** [comment]
You need to write a more concrete and complete option if you want my opinion, @jazeltq.

**Comment by chungg** [comment]
@jazeltq  did you ever test how much of the round trip time is from HTTP and how much is from processing and storage? personally i'd start there. yes, HTTP adds a bunch of overhead as it extends TCP but i'm curiuos how much before we start another API.

**Comment by jazeltq** [comment]
After some log print. It is not very simple.
The total time for publish samples include below:
batch resources metrics measures create
resource create
resource patch

It always to do resource patch. I do not very understand.
The log is here
http://paste.openstack.org/show/628451/

The total time for storage is very low. Much time is spent on update database because it always to update resource......

**Comment by jazeltq** [comment]
May be some extra should be handled by event, not by samples?

**Comment by chungg** [comment]
do you not have cache enabled in Ceilometer? the cache is what stops needless resource update requests.

**Comment by jazeltq** [comment]
After use cache, we found the time consume is  very low and the rate is acceptable. We only test under 100 vm. We should decide whether to go on this after more load test. For example, if 5k vm is ok, then we do not need to change it to use tcp right now.

**Comment by chungg** [comment]
just fyi, @akrzos already tested this to 10K+ VMs: https://www.youtube.com/watch?v=PC96PpT05G4

this was without batching (if i understand correctly)

**Comment by jazeltq** [comment]
Thanks a lot...

**Comment by tobias-urdin** [comment]
Closing, no new information in a long time.
