### ISSUE TITLE
Get metric measures of more than one resource (no aggregation)

### ISSUE THREAD

**Issue by jd** [gnocchixyz/gnocchi#5]
See https://bugs.launchpad.net/gnocchi/+bug/1516741

**Comment by chungg** [comment]
i think we can close this? #87 was very similar from what i can tell.

**Comment by jd** [comment]
#87 does not offer resource querying at all, it's just measures retrieval for metric ids :( There's no search support.

**Comment by chungg** [comment]
word, didn't read the filtering part

**Comment by jd** [comment]
This is not fixed via the new `/v1/aggregates` endpoint in 4.1.
