### ISSUE TITLE
Unable to list metrics with non admin Keystone token

### ISSUE THREAD

**Issue by zeljkokalezic** [gnocchixyz/gnocchi#519]
For the project I'm working on I need to retrieve metric unit, but I only have metric name and project id, my idea was to filter the metrics by name and project id with limit of one, and then fetch the unit from first metric (metrics are generated by OpenStack so they should have same units for same metric name). 

Gnocchi API is accessed with non admin token for security reasons but I'm unable to filter metrics with non admin token. 

Not sure if this is a bug or misconfiguration, so any advice will be much appreciated 😃.

I'm doing this because I did not find a way to fetch metric unit along with aggregated data using `/v1/aggregates` API, if there is a way to do that using aggregates API please let me know (I tried grouping by unit but got error 500 - error from log was ` InvalidPagination: Invalid pagination: Sort key supplied is invalid: unit`).

I see that cause is following line in policy.json:`"list all metric": "role:admin"`.
Deleting `role:admin` rule allows for measures listing.
I also tried using rule `rule:admin_or_creator or rule:metric_owner or rule:resource_owner` but effect is the same.

Not sure if this is related to https://github.com/gnocchixyz/gnocchi/issues/464 

### Which version of Gnocchi are you using
4.1.1
### How to reproduce your problem
Access `v1/metric?name={metric_name}&project_id={project_id}&limit=1` with non admin Keystone token from user that belongs to specified project.
### What is the result that you get
```
<html>
    <head>
        <title>403 Forbidden</title>
    </head>
    <body>
        <h1>403 Forbidden</h1>
  Access was denied to this resource.
        <br />
        <br />
Insufficient privileges to filter by user/project
    </body>
</html>
```
### What is result that you expected
```
[
    {
        "created_by_user_id": "45687d46ccf3451f95ef83505919eb0e",
        "name": "cpu_util",
        "creator": "45687d46ccf3451f95ef83505919eb0e:7a0bbd89a13946c8a7b64d14b72de604",
        "resource_id": "8bd16625-4ea2-47b6-bb7e-a715eb7aa1b9",
        "created_by_project_id": "7a0bbd89a13946c8a7b64d14b72de604",
        "archive_policy": {
            "definition": [
                {
                    "points": 8640,
                    "timespan": "30 days, 0:00:00",
                    "granularity": "0:05:00"
                }
            ],
            "back_window": 0,
            "name": "low",
            "aggregation_methods": [
                "std",
                "count",
                "min",
                "max",
                "sum",
                "mean"
            ]
        },
        "id": "074a0174-5a64-40e4-977a-56787194167f",
        "unit": "%"
    }
]
```

**Comment by jd** [comment]
Hey @zeljkokalezic! Thanks for this complete bug report, that's awesome.

> I'm doing this because I did not find a way to fetch metric unit along with aggregated data using /v1/aggregates API, if there is a way to do that using aggregates API please let me know (I tried grouping by unit but got error 500 - error from log was InvalidPagination: Invalid pagination: Sort key supplied is invalid: unit).

You should not get a 500 here. Can you open another bug with the request you made and the complete traceback. We need to fix this – either by returning a proper error, either by doing what you requested.

> /v1/metric?name={metric_name}&project_id={project_id}&limit=1 

If you get 403 here, it's likely because the user you are authenticated with is not authenticated on `project_id`, therefore you cannot do that (`policy.json` forbids it as you notice).

If your user is not authenticated against that project (i.e. it is not part of it) then modifying the `policy.json` to fits your use case is the correct fix.

**Comment by zeljkokalezic** [comment]
Hey @jd (awesome username by the way 😄) no problem, I will submit another bug request.

Unfortunately user is member of the project, can you please help me how to create a rule that allows the user to list metrics for his project? I tried using `rule:admin_or_creator or rule:metric_owner or rule:resource_owner` but I also get the same error.

User in question is 100002:
![image](https://user-images.githubusercontent.com/9953216/33381528-92625b00-d51e-11e7-8c84-69ccf79e9bf1.png)


**Also I noticed that metrics are created as different project maybe that is the actual issue.**
I'm using RDO Packstack with Gnocchi upgraded using pip upgrade on CentOS 7.

Project list in OpenStack dashboard:
![2017-11-29 15_01_30-projects - openstack dashboard](https://user-images.githubusercontent.com/9953216/33381329-00f2eb76-d51e-11e7-81f5-7fcc25898128.png)
When I retrieve the metric (created_by_project_id is actually `services` project and created_by_user_id is `admin` user)
![2017-11-29 15_02_07-postman](https://user-images.githubusercontent.com/9953216/33381358-1c95d17c-d51e-11e7-92c5-a472f05b9f04.png)

**Comment by jd** [comment]
> can you please help me how to create a rule that allows the user to list metrics for his project?

Well, this is allowed by default. The problem is that you pass `project_id=` in the URL with a project id that is different that the one your user is authenticated with.

The fact that it does not work in your case might be explained by what you say after:

> Also I noticed that metrics are created as different project maybe that is the actual issue.

So yeah, what you're saying is that user $foobar (probably Ceilometer, if you use it) creates the metric for 10002. In that case, the metric listing won't include the metrics. This is a missing feature tracked as #314.
