### ISSUE TITLE
Metric types in Gnocchi

### ISSUE THREAD

**Issue by zeljkokalezic** [gnocchixyz/gnocchi#523]
Not sure if actual issue or not so please close if not an issue 😃.

I was wondering if there is a way to distinguish metric types in Gnocchi as in Ceilometer which has three types for meters:

- Cumulative: Increasing over time (e.g.: instance hours)
- Gauge: Discrete items (e.g.: floating IPs, image uploads) and fluctuating values (e.g.: disk I/O)
- Delta: Changing over time (bandwidth)

Should that be inferred from unit, or is there some other approach?

Thanks,
Zeljko

**Comment by chungg** [comment]
this seems more like metadata that we could potentially add as a metric attribute. that said, this isn't dictated by gnocchi but by the source providing data to gnocchi. i think the only way gnocchi can know the type of a metric is if it's told.

regarding adding it as an attribute, for me it's a decision whether it's documentation or something useful to query on. in my opinion, unit and type are documentation items but as we already have unit as an attribute, other's have a different opinion.
