### ISSUE TITLE
rest: narrow down the response attributes

### ISSUE THREAD

**Issue by nmi** [gnocchixyz/gnocchi#545]
### Which version of Gnocchi are you using
master branch (commit 7892684dde395dd3ccec67a9cb172659975d74a8)

### How to reproduce your problem
```bash
$ cd gnocchi-docker
$ source devel.env
$ docker-compose up
```
### What is result that you expected
Templating of gnocchi's grafana-datasource converts a query option (ex. `resources(instance, host, {})`) to a query(ex. `{}`) and post it to `/v1/search/resource/instance` endpoint. The response size of this endpoint will be too large (ex. dozens of MB), if the number of resources increases (ex. 1,000 instances). So, I'd like to modify gnocchi-api to response only specified attributes such as `host` and `flavor_id` as below:

```bash
# Request
POST /v1/search/resource/instance?details=true&attributes=host,id,flavor_id HTTP/1.1
Content-Length: XX
Content-Type: application/json

{
  "=": {
    "user_id": "BD3A1E52-1C62-44CB-BF04-660BD88CD74D"
  }
}

# Response
HTTP/1.1 200 OK
Content-Length: XXXX
Content-Type: application/json

[
  {
    "flavor_id": "2",
    "host": "compute1",
    "id": "6868da77-fa82-4e67-aba9-270c5ae8cbca"
  }
]
```
I would like to get your feedback.

**Comment by jd** [comment]
I see no objection. @sileht?
