### ISSUE TITLE
Archive-policy-less metrics

### ISSUE THREAD

**Issue by jd** [gnocchixyz/gnocchi#547]
Currently a metric has to be attached to an archive policy. This is problematic as archive policies do not always exist for every case that metrics might need.

The archive policy system is a concept that has been built to ease the use of Gnocchi, but that point is still to be determined. Concretely, it limits today Gnocchi API users in what they might want to do.

The suggestion would be here to allow metrics to be created without archive policies at all.

**Comment by chungg** [comment]
i think you already created this. https://github.com/gnocchixyz/gnocchi/issues/175
