### ISSUE TITLE
Processing data is slow when i test 200 instances with polling configures to 60s

### ISSUE THREAD

**Issue by yjLiInSky** [gnocchixyz/gnocchi#603]
### Which version of Gnocchi are you using
I run the gnocchi 4.0.2. For HA , i deploy gnocchi service in 3 hosts, and use zookeeper for coordination.

### How to reproduce your problem
when i start a small number of instances, the gnocchi process data is good without backlog .  But when i run 200 instances with 60s polling granularity, there is a lot of data backlog. when i run "gnocchi status",it shows like this: 
 ```
+-----------------------------------------------------+-------+
| Field                                               | Value |
+-----------------------------------------------------+-------+
| storage/number of metric having measures to process | 3006  |
| storage/total number of measures to process         | 16838 |
+-----------------------------------------------------+-------+

+-----------------------------------------------------+-------+
| Field                                               | Value |
+-----------------------------------------------------+-------+
| storage/number of metric having measures to process | 3002  |
| storage/total number of measures to process         | 16854 |
+-----------------------------------------------------+-------+
```
I waited a long time these figures didn't go down.
This is part of my gnocchi.conf : 
```
[storage]
driver = ceph
ceph_pool = gnocchi
ceph_username = gnocchi
ceph_keyring = /etc/ceph/ceph.client.gnocchi.keyring
ceph_conffile = /etc/ceph/ceph.conf
coordination_url = zookeeper://controller:2181,compute1:2181,compute2:2181
aggregation_workers_number = 8
#metric_processing_delay = 60
#metric_reporting_delay = 10
#metric_processing_delay = 1

[metricd]
workers = 9
metric_reporting_delay = -1
metric_processing_delay = 60
worker_sync_rate = 30
processing_replicas = 6
```

### What is result that you expected
I'm not sure if my configuration is correct,can anyone give me some advice? thanks a lot .

**Comment by sileht** [comment]
Did you check the gnocchi-metricd logs to be sure it processes measures ?

**Comment by yjLiInSky** [comment]
![2k _ v j h r718i _5m](https://user-images.githubusercontent.com/30643908/34514314-d8e52306-f0a7-11e7-9631-cb5453a55124.png)
from the log, the measures are processed.

**Comment by jd** [comment]
If you generate 16k every 60s and process them a few seconds later, that looks like something normal that they sit there for a while.

**Comment by yjLiInSky** [comment]
Thank you so much for taking the time to see my problem.
The number keep growing. It's now this:
```
+-----------------------------------------------------+-------+
| Field                                               | Value |
+-----------------------------------------------------+-------+
| storage/number of metric having measures to process | 3120  |
| storage/total number of measures to process         | 26526 |
+-----------------------------------------------------+-------+
```

**Comment by jd** [comment]
Add more metricd to process faster? Configure your archive policy to be smaller?

**Comment by chungg** [comment]
how fast is this 'growing'?

that said, there seems to be something wrong with your ceph configuration. it should not take 2s to process and store a metric. in the gate, with file driver, it takes ~0.1s/metric... when i benchmark with ceph, it took something similar.
