### ISSUE TITLE
avoid/minimise object scanning on write

### ISSUE THREAD

**Issue by chungg** [gnocchixyz/gnocchi#608]
when storing measures, we run _list_split_keys_for_metric, which does a scan of objects, for each single granularity and aggregate to figure out what to delete/compress. this sucks.

ideally, we shouldn't call _list_split_keys_for_metric at all as we can easily just compute the keys and delete/compress until the object fails to delete/compress. the problem is that certain drivers s3 do not fail if you attempt to delete something that doesn't exist. i'm not sure how ceph and s3 behave. maybe @sileht would know.

that said, if we are forced to do a _list_split_keys_for_metric scan, we should do it once and rather than for ever single granularity x aggregation permutation as _list_split_keys_for_metric already is capable of returning everything, we're just filtering in post (in most cases)

**Comment by chungg** [comment]
the super radical solution to avoid scans is to defer delete/compress actions to another process/janitor. this will delay cleanup though.

**Comment by chungg** [comment]
note, the radical solution isn't great now that i think more about it as it probably causes janitor to do a lot of useless checking of metrics that don't need work.

**Comment by chungg** [comment]
i benched os.listdir vs glob.glob... it's actually faster to call listdir multiple times rather than glob once. :(

i'll need to debug this more to verify it's actually performance gain for other drivers

**Comment by chungg** [comment]
there's a scenario which my patch does not handle currently. it's if you don't have:
- very short granularity
- very long/no timespan
- no rewrites (aka not ceph)

in this case, we don't need to do scans, but it will do scans. the amount of useless scans increases as granularities decrease. i don't know how critical this scenario is but just stating it for us to discuss (if needed) else we can close.

**Comment by jd** [comment]
I think we're good at this point. We can't make further optimization without bending the code too much and storing additional state or something like that AFAICS.
