### ISSUE TITLE
Problem with get measures permission

### ISSUE THREAD

**Issue by jazeltq** [gnocchixyz/gnocchi#613]
There is one policy in policy.json, here it is:
"metric_owner": "project_id:%(resource.project_id)s"

If one normal user (not admin) want to get measures from this metric, this policy in policy.json will raise an exception because it can not get project from resource.project_id....

**Comment by jd** [comment]
Can you paste the backtrace you see?

**Comment by jazeltq** [comment]
It raises 403.  We pdb into the gnocchi, and find this. It is a image. so I upload it here.
https://pasteboard.co/H1XsWVI.png

**Comment by jd** [comment]
What version are you running?

It sounds like a duplicate of https://github.com/gnocchixyz/gnocchi/issues/464

**Comment by jazeltq** [comment]
Oh, sounds like it. We use newton, it is 3.0.15...
