### ISSUE TITLE
need help to configure gnocchi in production

### ISSUE THREAD

**Issue by ramesh-chowdeshetty** [gnocchixyz/gnocchi#619]
I would like to deploy gnocchi in my production environment. What configuration can i use to scale my system in nanoseconds.

I would like to increase performance of gnocchi-metricd daemon to scale upto fulfill 100000 measures per millisecond .
Please help me to configure this.

**Comment by chungg** [comment]
> scale my system in nanoseconds.

can you clarify what you mean by this? what do you want in nanoseconds? to temper your expectations, if you want scale, i imagine you are looking at ceph (or swift/s3) as aggregate storage driver and i think it's apparent you cannot write to a remote object store in nanoseconds let alone do other stuff.

it's really hard to help as the request is so generic. i'd start with reading docs, installing gnocchi 4.1.2, and attempting to accomplish what you need. maybe do some tests so it's possible for us to understand how far away you are from requirements. if you have this information already, please let us know :)

**Comment by ramesh-chowdeshetty** [comment]
whenever i am sending measures it is giving 202 error response and the gnocchi is ready to take another request without completing sending of measures. My requirement is to push and pull data synchronously.



 I will send one measures and the next request is to read measure from the metric within milliseconds. How can i achieve this .

**Comment by chungg** [comment]
202 is not an error response, quite the opposite actually: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

you can pass 'refresh=True' parameter when querying. see: https://gnocchi.xyz/rest.html#refresh gnocchi functions asynchronously but this is as synchronous as you can get.

i'm still very wary that you keep mentioning millisecond timing. to be honest, this really doesn't seem like the correct workflow but rather you have a lambda architecture for your millisecond workflow and gnocchi for your 'big data' flow.
