### ISSUE TITLE
GET resource by original_resource_id

### ISSUE THREAD

**Issue by sasvaritoni** [gnocchixyz/gnocchi#651]
When I use original_resource_id instead of id when getting a resource, it fails with gnocchi 4.1.2.dev6:
GET /v1/resource/generic/test8
404 Not Found
The resource could not be found.
 Resource 2d46d43c-fb8c-5a62-a52d-68a64e1f674a does not exist 

Which is completely ok, according to the documentation :)

But strangely in some earlier version of gnocchi (e.g. 3.0.7) this used to work even if I used the original_resource_id instead of id in GET.

Could you please point out the commit or version where this behavior was changed/corrected?

**Comment by jd** [comment]
This depends on the user doing the request. The resource_id are computed based on the original resource id and the user id.

This has been added in 3.1 IIRC.

**Comment by sasvaritoni** [comment]
Oh, I see, thanks a lot!
Based on this I found the relevant ticket:
https://bugs.launchpad.net/gnocchi/+bug/1617918
