### ISSUE TITLE
janitor is idle most of the time

### ISSUE THREAD

**Issue by chungg** [gnocchixyz/gnocchi#652]
Before reporting an issue on Gnocchi, please be sure to provide all necessary
information.

### Which version of Gnocchi are you using
master

### How to reproduce your problem
just run it 

### What is the result that you get
janitor process on each metricd

### What is result that you expected
do we really need a janitor process on each metricd? majority of the time it's doing nothing. when there is work, it's a race between all the other janitors in metricd agents to cleanup a deleted metric.

this connects back to #608... in my mind, it's a bit strange that part of the cleanup is done by janitor and part of it's done by processors. it'd be good to make compress/delete separate from standard processing but we need to leverage the knowledge of processors to avoid pointless checking in janitor

maybe the processor can put on to a (internal/external) queue that metricA is processed and has a new last timestamp and first mutable timestamp. it's then the janitor's job to deal with cleanup.

this isn't necessarily to speed up processing time but to make better use of janitor.

**Comment by chungg** [comment]
i'm thinking we could create a local queue. when a processor agent works on metric, it will push to queue -> (metricid, aggregates, granularities, last_timestamp). the janitor, at each cycle, will grab everything from queue and cleanup each metric based on information provided. some notes:
- it will require locking metric, as a metric may be processed by different metricd.
- this is obviously not durable so it might miss cleanup (until next datapoint, if there is another). we can make this 'durable' but i think we'd still need lock.

we can also wakeup janitor like how greedy path works but tbh, i don't think timing is critical. the main concern of deferring cleaning to another process is the memory required to capture which metrics need to be cleaned and how.

**Comment by jd** [comment]
- I don't really like the fact that it's not stateless
- I don't think timing is critical either

Did you consider the following alternative: synchronize the janitors via tooz partitioner and only spawns a janitor process on N nodes that are responsible for running the expunging task. So you'd save memory/cpu on (total_nodes - N).

That also has the downside that you then need to scale your janitor yourself based on your deletion rate, whereas the current design is stateless and scaled automatically…

**Comment by chungg** [comment]
good argument regarding stateless. that's one of the reasons i want to hash out design to see if it's actually useful.

technically you have to scale your janitor right now. the only reason it's not considered is because there's so little to scale. :P

that said, i think there is very little to do for cleanup/rewrite as well. most of the time, the cleanup/rewrite steps in _add_measures are doing nothing but scanning for objects, looping through objects, realise nothing to do, continue... the only reason cleanup/rewrite should be triggered often is if the policy is very, granular. 3600 points means even if 1s granularity, each object to rewrite/cleanup is 1hr duration. the medium policy, at 1min, won't cleanup/rewrite for 2.5days and the low policy is 12.5days.

i wonder if there's a way to figure out if current last timestamp is > 3600 points from last rewrite or > X points from last cleanup? in reality, that is the condition when rewrite/cleanup is even useful.

**Comment by chungg** [comment]
add enhancement tag. this probably doesn't improve performance. maybe it improves performance of scenario where there is a really large series (many splits). in this case, we can avoid the needless scanning each time.

**Comment by chungg** [comment]
i think #654 resolves the scanning. the issue still remains that the janitor does very little. this seems better served as a cron job given it's idle time.

**Comment by jd** [comment]
Make it smaller, but please, don't bring up cron. :)

**Comment by chungg** [comment]
i don't know if we can make it smaller. it needs to access all data locations (indexer, storage, incoming)... in reality, i imagine this only need to be done once a day if not longer as deleting metrics are not time critical at all.

**Comment by jd** [comment]
Maybe that's the key here: make the master process spawn the janitor once every N seconds rather than being idle most of the time.

**Comment by chungg** [comment]
i like that.

**Comment by chungg** [comment]
just fyi, i have no idea how to do this properly in cotyledon.

**Comment by jd** [comment]
I've looked into that, and from what I see the alternative is to implement a thread in the master process that would spawn a new janitor process every N seconds.
I'm not sure this is a real gain. I mean now we have to run code in the master process… where I guess we could just run the janitor code directly rather than forking… whereas the current state makes isolation of the janitor so that it's safe and it can crash without having any effect on other processes.

It's just a matter of trade-off at this point and I'm not convinced we need to change it. Do you have convincing arguments @chungg?

**Comment by chungg** [comment]
not really. this isn't really that important if it's difficult to handle. it just bothers me a little when i run top and see the process and i know it's not doing anything.lol

my only other idea was to piggyback worker=0 of processing workers. but then cleanup interval would be some multiple of processing interval (i think)

**Comment by jd** [comment]
Closing this as I don't think see how we can change the design to improve this and it's not a "real" issue.
