### ISSUE TITLE
Document support for arbitrary resource ids

### ISSUE THREAD

**Issue by larsks** [gnocchixyz/gnocchi#698]
I'm using gnocchi `4.1.3`.

I've discovered that it is possible to create resources with an arbitrary resource id.  For example,

```
$ curl -H 'content-type: application/json' -u admin: localhost:8041/v1/resource/generic -d @- <<EOF
{
  "id": "some-arbitrary-string",
}
EOF
```

Gnocchi moves that over to the `original_resource_id` field and assigns a unique UUID, and that original id can be used in queries where normally one would put the UUID, as in:

```
$ curl -s -u admin: localhost:8041/v1/resource/generic/some-arbitrary-string
{
  "user_id": null,
  "revision_end": null,
  "original_resource_id": "some-arbitrary-string",
  "created_by_user_id": "admin",
  "revision_start": "2018-01-28T17:24:11.509758+00:00",
  "project_id": null,
  "id": "6fba60c9-8174-5822-8730-9d4bf6a7c1b9",
  "metrics": {},
  "ended_at": null,
  "creator": "admin",
  "started_at": "2018-01-28T17:24:11.509746+00:00",
  "created_by_project_id": "",
  "type": "generic"
}
```

I don't see this behavior documented anywhere. Can I rely on it? It's extremely interesting for an IoT use case, where a device may already have a unique id and being able to use that avoids some round-trips to the gnocchi api.

**Comment by jd** [comment]
It is not documented but it is reliable.

The `original_resource_id` is converted to an UUID using https://docs.python.org/3/library/uuid.html#uuid.uuid5 with a constant namespace.

The UUID is unique for `(user, original_resource_id)` so different users can use the same `original_resource_id` and it'll map to different `resource_id`.

**Comment by larsks** [comment]
Thanks.  I have a related question, then.  At the moment, it appears that one is *required* to provide an ID when creating a resource:


```
$ curl localhost:8041/v1/resource/generic -u admin: -H 'Content-type: application/json' -d '{}' 
[...]
<h1>400 Bad Request</h1>
The server could not comply with the request since it is either malformed or otherwise incorrect.<br /><br />
Invalid input: required key not provided @ data[&#x27;id&#x27;]
```
Is there a particular reason why Gnocchi doesn't simply generate a UUID at this point (and return that in the reponse)?

**Comment by jd** [comment]
It could generates a unique random ID for sure. Would it be more interesting than generating one client side?

**Comment by larsks** [comment]
I'm not entirely sure. I mean, my expectation from using the other openstack apis is that the server will generate a UUID for me, but I can see why that might not be the case for Gnocchi resources.  I am waffling between "an empty id is an error" and "an empty id should result in a random id", and I can't think of a concrete use case that helps either way.  I dunno, I guess table this question for now unless more people start asking the same thing.

**Comment by larsks** [comment]
> The UUID is unique for (user, original_resource_id) so different users can use the same original_resource_id and it'll map to different resource_id.

It looks like if you pass in a UUID that Gnocchi will use it verbatim. E.g.:

```
curl --trace-ascii log -i localhost:8041/v1/resource/generic -u admin: -H 'Content-type: application/json' -d '{"id": "38951a06-7cf8-443b-a507-8427dfac91c3"}'
```

Results in:

```
{
  "revision_end": null,
  "started_at": "2018-01-29T13:27:42.030105+00:00",
  "revision_start": "2018-01-29T13:27:42.030118+00:00",
  "original_resource_id": "38951a06-7cf8-443b-a507-8427dfac91c3",
  "project_id": null,
  "user_id": null,
  "creator": "admin",
  "id": "38951a06-7cf8-443b-a507-8427dfac91c3",
  "type": "generic",
  "metrics": {},
  "ended_at": null,
  "created_by_project_id": "",
  "created_by_user_id": "admin"
}
```

Should the same hashing on the user id be applied even in this case?  I can see situations in a multi-tenant environment in which two people might want to track metrics for the same thing, and if the object they are tracking has a native UUID they both might attempt to use that for the Gnocchi resource id.

**Comment by chungg** [comment]
i think the idea is if two users are tracking the same resource, that they would be part of same project which would give them visibility (based on policy)

**Comment by larsks** [comment]
I was thinking outside the context of openstack...but maybe I am just making stuff up.  And obviously someone who wanted this particular use case could just prefix the native uuid with something to get the unique-per-use behavior.
