### ISSUE TITLE
Allow to edit generic resource type

### ISSUE THREAD

**Issue by jd** [gnocchixyz/gnocchi#7]
See https://bugs.launchpad.net/gnocchi/+bug/1603326

**Comment by chungg** [comment]
i'm not sure we want to all edits to generic as everything inherits from it no?... and i don't know if it's worth the hassle of renaming it to 'all'

**Comment by jd** [comment]
I think the requirements back then was different, as people wanted to have e.g. custom fields on all resources. It's now pretty clear that since you can create your own resources types etc, this is not really useful. I still have the idea to reduce the default field of the generic resource types, but that's a different issue and it's a compatibility issue.
