### ISSUE TITLE
archive policy explanation

### ISSUE THREAD

**Issue by ramesh-chowdeshetty** [gnocchixyz/gnocchi#715]
I have created an archive policy as follows
{
    "definition": [
        {
            "points": 144000000,
            "timespan": "100000 days, 0:00:00",
            "granularity": "0:01:00"
        }
    ],
    "back_window": 0,
    "name": "timeseries_minute_policy",
    "aggregation_methods": [
        "std",
        "count",
        "min",
        "max",
        "sum",
        "mean"
    ]
}

and I have inserted some measures as follows

[{'timestamp': '2014-04-01 00:00:00', 'value': '18.090486228499998'}
{'timestamp': '2014-04-01 00:05:00', 'value': '20.359842585899997'}
 {'timestamp': '2014-04-01 00:10:00', 'value': '21.105469847200002'}
 {'timestamp': '2014-04-01 00:15:00', 'value': '21.1515852522'}
 {'timestamp': '2014-04-01 00:20:00', 'value': '18.1371405424'}
 {'timestamp': '2014-04-01 00:25:00', 'value': '21.6256605306'}
 {'timestamp': '2014-04-01 00:30:00', 'value': '21.6738066877'}
 {'timestamp': '2014-04-01 00:35:00', 'value': '20.2455614926'}]

But gnocchi returning only one measure as follows

[
    [
        "2014-04-01T00:00:00+00:00",
        3600,
        20.2986941458875
    ]
]

what can be the reason could somebody explain me.

**Comment by chungg** [comment]
> [
> "2014-04-01T00:00:00+00:00",
> 3600,
> 20.2986941458875
> ]

this shows you created an archive policy of 1 hour, not 1 minute. in this case, all the data points you push between 2014-04-01 00:00:00 and 2014-04-01 00:59:59.999999 will be rolled up to 2014-04-01T00:00:00+00:00

**Comment by ramesh-chowdeshetty** [comment]
how can i create archive policy for minutes data

**Comment by chungg** [comment]
> POST /v1/archive_policy HTTP/1.1
> Content-Length: 255
> Content-Type: application/json
> 
> {
>   "back_window": 0,
>   "definition": [
>     {
>       "granularity": "60s",
>       "timespan": "100000 days"
>     }
>   ],
>   "name": "blah"
> }

i don't know why you're creating keeping data for 250+ years but ok.
