### ISSUE TITLE
Set null value for UUID attribute

### ISSUE THREAD

**Issue by m0zart89** [gnocchixyz/gnocchi#757]
Gnocchi 2.2.1

I have resource _host_network_interface_ with attribute _account_ (type: uuid, required: false).

Requrest:
```shell
PATCH /v1/resource/host_network_interface/0f1a8f61-0294-56d8-961f-6dd10d6e70d7 HTTP/1.1
HOST: 192.168.1.1:8041
x-auth-token: a64adca7a4184f6cbe08235df1943089
content-type: application/json
content-length: 23

{
  "account": null
}
```
Response:
```shell
400 Bad Request

The server could not comply with the request since it is either malformed or otherwise incorrect.

 Invalid input: not a valid value for dictionary value @ data[u'account']  #
```
Is it possible to set null value for UUID attribute ?

P.s: I use "00000000-0000-0000-0000-000000000000" as a temporary solution)

**Comment by jd** [comment]
I did not check the code (2.2 is old) but it's likely that this is not supported. What's supported is not passing the value at all.
