### ISSUE TITLE
needed explanation on aggregation 

### ISSUE THREAD

**Issue by ramesh-chowdeshetty** [gnocchixyz/gnocchi#788]
I have created metric to store days data.

how can i aggregate by week,month,year,every weekday,every weekend,every hour on everyday.
Is there any builtin functions  to do this aggregations.

Can somebody help me to solve this.

**Comment by chungg** [comment]
you define these rules either in your archive policies[1] or by using resample[2][3]. i don't understand your 'every weekday, every weekend' requirement' though -- the groupings must be consistent timespans (by hour, 3 hours, day, 2 days, 7 days, etc...)

[1] https://gnocchi.xyz/operating.html#how-to-define-archive-policies
[2] https://gnocchi.xyz/rest.html#resample
[3] https://gnocchi.xyz/rest.html#id27
