### ISSUE TITLE
Resource types should allow dynamic changes

### ISSUE THREAD

**Issue by jd** [gnocchixyz/gnocchi#8]
See https://bugs.launchpad.net/gnocchi/+bug/1615077

**Comment by BigChief45** [comment]
I think this has already been fixed. See: https://review.openstack.org/#/c/363737/

So this can probably be closed.

**Comment by jd** [comment]
@sileht did you have anything else you wanted to implement?

**Comment by sileht** [comment]
I don't think so, resource types attributes can now be added and deleted. And it doesn't make sense to update them because we can't ensure type conversion of all data already stored.

**Comment by sileht** [comment]
The link to the delete part: https://review.openstack.org/#/c/363770/ for the history
