### ISSUE TITLE
measure omap may grown large enough to break ceph cluster

### ISSUE THREAD

**Issue by jeffrey4l** [gnocchixyz/gnocchi#804]
Before reporting an issue on Gnocchi, please be sure to provide all necessary
information.

### Which version of Gnocchi are you using

gnocchi 3.x + ceph jewel (incoming & storage )

### How to reproduce your problem

In a normal environment, stop all gnocchi-metricd processes for long time.

### What is the result that you get

Along with the increasing of incoming data, the number of omap values in "measure" object increases massively. all the data is saved in ceph leveldb, and it is not recommended to store many data in leveldb in ceph.

As a result, the ceph is response very slow when accessing the "measure" object's omap when the omap is large enough.

### What is result that you expected

Should we save the omap values into multi object or use other ways to avoid such case?

**Comment by jd** [comment]
Gnocchi 4.x splits the incoming storage in multiple sacks.

**Comment by chungg** [comment]
i'm not sure there's  a way around it in gnocchi v3. you can hack the code so it schedules better but it's not great. best bet is to use gnocchi4+ as @jd said

**Comment by jeffrey4l** [comment]
@jd  thanks, i read the gnocchi 4.x code. if i understand correct, in default, there are 128 sacks and incoming measures will be added into there sacks' omap.

If so, isn't it still a issue? because the sacks are still finite and the omap list will become long enough. Or is it a good idea to set a higher sacks value? like 10240?

**Comment by chungg** [comment]
there are some docs to show how to configure sacks (the docs are just a recommendation): https://gnocchi.xyz/operating.html#how-to-scale-measure-processing.

in addition to sharding into sacks, the scheduling logic in gnocchi4+ is also different. without getting into details, just ensure you have enough metricd workers for your workload.

**Comment by jeffrey4l** [comment]
@chungg got, thanks a lot.
