### ISSUE TITLE
collectd measures show -r "metric-name" returns error

### ISSUE THREAD

**Issue by fbattle** [gnocchixyz/gnocchi#808]
Versions:
collectd-gnocchi (1.7.0)
collectd 5.8.0
gnocchi (4.2.0)
gnocchiclient (7.0.1)
gnocchi-metricd --version returns 4.2.0
python --version returns 2.7.5

### How to reproduce your problem
Run gnocchi-api using apache / wsgi, run gnocchi-metricd in separate shell, run collectd in separate shell.

### What is the result that you get
I am seeing several problems.
1) gnocchi-metricd reports these errors:
2018-03-09 18:57:16,510 [20897] INFO     gnocchi.cli.metricd: 0 measurements bundles across 0 metrics wait to be processed.
2018-03-09 18:57:20,087 [20894] WARNING  py.warnings: /usr/lib64/python2.7/site-packages/pymysql/cursors.py:165: Warning: (1300, u"Invalid utf8 character string: 'BF50C3'")
  result = self._query(query)

2018-03-09 18:57:20,194 [20894] WARNING  py.warnings: /usr/lib64/python2.7/site-packages/pymysql/cursors.py:165: Warning: (1300, u"Invalid utf8 character string: 'A38BE6'")
  result = self._query(query)

2) Running this collectd command returns an error:
gnocchi measures show -r collectd:scc2-4-vm21.us.oracle.com memory@memory-free

[Fri Mar 09 22:22:40.959894 2018] [:error] [pid 28880] [remote ::1:1692] mod_wsgi (pid=28880): Exception occurred processing WSGI script '/usr/bin/gnocchi-a
pi'.
[Fri Mar 09 22:22:40.959953 2018] [:error] [pid 28880] [remote ::1:1692] Traceback (most recent call last):
[Fri Mar 09 22:22:40.959975 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 131, in __call__
[Fri Mar 09 22:22:40.960004 2018] [:error] [pid 28880] [remote ::1:1692]     resp = self.call_func(req, *args, **self.kwargs)
[Fri Mar 09 22:22:40.960013 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 196, in call_func
[Fri Mar 09 22:22:40.960025 2018] [:error] [pid 28880] [remote ::1:1692]     return self.func(req, *args, **kwargs)
[Fri Mar 09 22:22:40.960032 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/oslo_middleware/base.py", line 131, in __c
all__
[Fri Mar 09 22:22:40.960045 2018] [:error] [pid 28880] [remote ::1:1692]     response = req.get_response(self.application)
[Fri Mar 09 22:22:40.960052 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1327, in send
[Fri Mar 09 22:22:40.960063 2018] [:error] [pid 28880] [remote ::1:1692]     application, catch_exc_info=False)
[Fri Mar 09 22:22:40.960069 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1291, in call_appl
ication
[Fri Mar 09 22:22:40.960079 2018] [:error] [pid 28880] [remote ::1:1692]     app_iter = application(self.environ, start_response)
[Fri Mar 09 22:22:40.960086 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/paste/urlmap.py", line 216, in __call__
[Fri Mar 09 22:22:40.960098 2018] [:error] [pid 28880] [remote ::1:1692]     return app(environ, start_response)
[Fri Mar 09 22:22:40.960104 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 131, in __call__
[Fri Mar 09 22:22:40.960126 2018] [:error] [pid 28880] [remote ::1:1692]     resp = self.call_func(req, *args, **self.kwargs)
[Fri Mar 09 22:22:40.960135 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/webob/dec.py", line 196, in call_func
[Fri Mar 09 22:22:40.960145 2018] [:error] [pid 28880] [remote ::1:1692]     return self.func(req, *args, **kwargs)
[Fri Mar 09 22:22:40.960152 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/oslo_middleware/base.py", line 131, in __c
all__
[Fri Mar 09 22:22:40.960162 2018] [:error] [pid 28880] [remote ::1:1692]     response = req.get_response(self.application)
[Fri Mar 09 22:22:40.960168 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1327, in send
[Fri Mar 09 22:22:40.960188 2018] [:error] [pid 28880] [remote ::1:1692]     application, catch_exc_info=False)
[Fri Mar 09 22:22:40.960194 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/webob/request.py", line 1291, in call_appl
ication
[Fri Mar 09 22:22:40.960203 2018] [:error] [pid 28880] [remote ::1:1692]     app_iter = application(self.environ, start_response)
[Fri Mar 09 22:22:40.960209 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/webob/exc.py", line 1162, in __call__
[Fri Mar 09 22:22:40.960220 2018] [:error] [pid 28880] [remote ::1:1692]     return self.application(environ, start_response)
[Fri Mar 09 22:22:40.960226 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/gnocchi/rest/app.py", line 124, in __call_
_
[Fri Mar 09 22:22:40.960236 2018] [:error] [pid 28880] [remote ::1:1692]     return self.app(environ, start_response)
[Fri Mar 09 22:22:40.960242 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/pecan/middleware/recursive.py", line 56, i
n __call__
[Fri Mar 09 22:22:40.960255 2018] [:error] [pid 28880] [remote ::1:1692]     return self.application(environ, start_response)
[Fri Mar 09 22:22:40.960261 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/pecan/core.py", line 840, in __call__
[Fri Mar 09 22:22:40.960272 2018] [:error] [pid 28880] [remote ::1:1692]     return super(Pecan, self).__call__(environ, start_response)
[Fri Mar 09 22:22:40.960278 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/pecan/core.py", line 683, in __call__
[Fri Mar 09 22:22:40.960286 2018] [:error] [pid 28880] [remote ::1:1692]     self.invoke_controller(controller, args, kwargs, state)
[Fri Mar 09 22:22:40.960292 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/pecan/core.py", line 574, in invoke_contro
ller
[Fri Mar 09 22:22:40.960300 2018] [:error] [pid 28880] [remote ::1:1692]     result = controller(*args, **kwargs)
[Fri Mar 09 22:22:40.960306 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/gnocchi/rest/api.py", line 544, in get_mea
sures
[Fri Mar 09 22:22:40.960317 2018] [:error] [pid 28880] [remote ::1:1692]     resample)
[Fri Mar 09 22:22:40.960322 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/gnocchi/storage/__init__.py", line 223, in
 get_measures
[Fri Mar 09 22:22:40.960596 2018] [:error] [pid 28880] [remote ::1:1692]     for ag in aggregations))
[Fri Mar 09 22:22:40.960610 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/gnocchi/utils.py", line 312, in parallel_m
ap
[Fri Mar 09 22:22:40.960628 2018] [:error] [pid 28880] [remote ::1:1692]     return list(executor.map(lambda args: fn(*args), list_of_args))
[Fri Mar 09 22:22:40.960635 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/concurrent/futures/_base.py", line 641, in
 result_iterator
[Fri Mar 09 22:22:40.960645 2018] [:error] [pid 28880] [remote ::1:1692]     yield fs.pop().result()
[Fri Mar 09 22:22:40.960651 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/concurrent/futures/_base.py", line 462, in
 result
[Fri Mar 09 22:22:40.960660 2018] [:error] [pid 28880] [remote ::1:1692]     return self.__get_result()
[Fri Mar 09 22:22:40.960666 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in
 run
[Fri Mar 09 22:22:40.960676 2018] [:error] [pid 28880] [remote ::1:1692]     result = self.fn(*self.args, **self.kwargs)
[Fri Mar 09 22:22:40.960682 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/gnocchi/utils.py", line 312, in <lambda>
[Fri Mar 09 22:22:40.960690 2018] [:error] [pid 28880] [remote ::1:1692]     return list(executor.map(lambda args: fn(*args), list_of_args))
[Fri Mar 09 22:22:40.960695 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/gnocchi/storage/__init__.py", line 252, in
 _get_measures_timeserie
[Fri Mar 09 22:22:40.960710 2018] [:error] [pid 28880] [remote ::1:1692]     metric, aggregation.method, aggregation.granularity)
[Fri Mar 09 22:22:40.960716 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/gnocchi/storage/__init__.py", line 185, in
 _list_split_keys_for_metric
[Fri Mar 09 22:22:40.960725 2018] [:error] [pid 28880] [remote ::1:1692]     metric, aggregation, granularity, version)),
[Fri Mar 09 22:22:40.960731 2018] [:error] [pid 28880] [remote ::1:1692]   File "/usr/lib/python2.7/site-packages/gnocchi/storage/file.py", line 110, in _li
st_split_keys
[Fri Mar 09 22:22:40.960800 2018] [:error] [pid 28880] [remote ::1:1692]     files = os.listdir(self._build_metric_path(metric, aggregation))
[Fri Mar 09 22:22:40.960822 2018] [:error] [pid 28880] [remote ::1:1692] OSError: [Errno 13] Permission denied: '/home/gnocchi/1ecaa05a-1201-48a3-8be6-94f48f2997a2/agg_mean'

3) gnocchi-mertricd reports Invalid utf8 character:
 [20894] WARNING  py.warnings: /usr/lib64/python2.7/site-packages/pymysql/cursors.py:165: Warning: (1300, u"Invalid utf8 character string: '9E595B'")
  result = self._query(query)

4) And just to pile on:, /var/log/mysqld.log shows:
2018-03-09T11:52:51.498162Z 653404 [Note] Aborted connection 653404 to db: 'gnocchi' user: 'gnocchi' host: 'localhost' (Got timeout reading communication packets)
And yes, the gnocchi@localhost user exists and is granted full rights.

As a side note, I'm checking aureport -a to look for selinux permissions errors. I set httpd_t to run in permissive mode, which I believe allows httpd to behave as if selinux is not enabled.  aureport returns the following, which I don't know if this is logging in permissive mode, or is something that selinux is denying.
52643. 03/09/2018 22:42:59 (wsgi:gnocchi)  system_u:system_r:httpd_t:s0 5 file getattr system_u:object_r:home_root_t:s0 denied 7543392
52644. 03/09/2018 22:42:59 (wsgi:gnocchi)  system_u:system_r:httpd_t:s0 2 dir write unconfined_u:object_r:home_root_t:s0 denied 7543391
52645. 03/09/2018 22:42:59 (wsgi:gnocchi)  system_u:system_r:httpd_t:s0 2 dir add_name unconfined_u:object_r:home_root_t:s0 denied 7543391
52646. 03/09/2018 22:42:59 (wsgi:gnocchi)  system_u:system_r:httpd_t:s0 2 file create system_u:object_r:home_root_t:s0 denied 7543391
52647. 03/09/2018 22:42:59 (wsgi:gnocchi)  system_u:system_r:httpd_t:s0 2 file read write open system_u:object_r:home_root_t:s0 denied 7543391
52648. 03/09/2018 22:42:59 (wsgi:gnocchi)  system_u:system_r:httpd_t:s0 82 dir write system_u:object_r:home_root_t:s0 denied 7543393
52649. 03/09/2018 22:42:59 (wsgi:gnocchi)  system_u:system_r:httpd_t:s0 82 dir remove_name unconfined_u:object_r:home_root_t:s0 denied 7543393
52650. 03/09/2018 22:42:59 (wsgi:gnocchi)  system_u:system_r:httpd_t:s0 82 file rename system_u:object_r:home_root_t:s0 denied 7543393
52651. 03/09/2018 22:42:59 (wsgi:gnocchi)  system_u:system_r:httpd_t:s0 82 dir add_name system_u:object_r:home_root_t:s0 denied 7543393
52652. 03/09/2018 22:42:59 httpd system_u:system_r:httpd_t:s0 83 dir create system_u:object_r:home_root_t:s0 denied 7543394

### What is result that you expected
I expect to see data when I run gnocchi measures show -r <metric name>

I can run the gnocchi commands to list resources, list the metrics for a given collectd resource, and also the details of a given metric, it's just the actual data for the metric that returns these errors.

**Comment by jd** [comment]
> 1. gnocchi-metricd reports these errors:
2018-03-09 18:57:16,510 [20897] INFO gnocchi.cli.metricd: 0 measurements bundles across 0 metrics wait to be processed.
2018-03-09 18:57:20,087 [20894] WARNING py.warnings: /usr/lib64/python2.7/site-packages/pymysql/cursors.py:165: Warning: (1300, u"Invalid utf8 character string: 'BF50C3'")
result = self._query(query)
2018-03-09 18:57:20,194 [20894] WARNING py.warnings: /usr/lib64/python2.7/site-packages/pymysql/cursors.py:165: Warning: (1300, u"Invalid utf8 character string: 'A38BE6'")
result = self._query(query)

Well, those INFO and WARNING. Not ERRORs. The first INFO indicates there's nothing to do, and the two warning are generated by SQLAlchemy (IIRC) and that might be because you're using a version that has not that fixed in SQLAlchemy or pymysql. You can ignore anyway.

> 2. Permission denied

You're again having a permission issue. Check that the user that runs Apache is correcly able to access the file, and check for SELinux too.

> 3. gnocchi-mertricd reports Invalid utf8 character:

Ditto as 1.

> 4. And just to pile on:, /var/log/mysqld.log shows:

Might be linked to 2. Since 2. makes Gnocchi abort, the connection is probably cut roughly.

**Comment by fbattle** [comment]
OK. I got tired of fighting SELinux, so I disabled it and rebooted.
I deleted /home/gnocchi, ran gnocchi-upgrade, started gnocchi-metricd in a shell, started collected in a shell, and /var/log/messages instantly writes this error:
```
Mar 10 20:06:15 scc2-4-vm21 collectd[22520]: ClientException: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">#012<html><head>#012<title>500 Internal Server Error</title>#012</head><body>#012<h1>Internal Server Error</h1>#012<p>The server encountered an internal error or#012misconfiguration and was unable to complete#012your request.</p>#012<p>Please contact the server administrator at #012 root@localhost to inform them of the time this error occurred,#012 and the actions you performed just before this error.</p>#012<p>More information about this error may be available#012in the server error log.</p>#012</body></html>#012 (HTTP 500)
Mar 10 20:06:15 scc2-4-vm21 collectd[22520]: Traceback (most recent call last):
Mar 10 20:06:15 scc2-4-vm21 collectd[22520]: File "/usr/lib/python2.7/site-packages/collectd_gnocchi/__init__.py", line 79, in inner_func#012    return func(*args, **kwargs)
Mar 10 20:06:15 scc2-4-vm21 collectd[22520]: File "/usr/lib/python2.7/site-packages/collectd_gnocchi/__init__.py", line 227, in flush#012    self._batch(host, values)
Mar 10 20:06:15 scc2-4-vm21 collectd[22520]: File "/usr/lib/python2.7/site-packages/collectd_gnocchi/__init__.py", line 244, in _batch#012    measures, create_metrics=True)Mar 10 20:06:15 scc2-4-vm21 collectd[22520]: File "/usr/lib/python2.7/site-packages/gnocchiclient/v1/metric.py", line 236, in batch_resources_metrics_measures#012    params=dict(create_metrics=create_metrics))
Mar 10 20:06:15 scc2-4-vm21 collectd[22520]: File "/usr/lib/python2.7/site-packages/gnocchiclient/v1/base.py", line 41, in _post#012    return self.client.api.post(*args, **kwargs)
Mar 10 20:06:15 scc2-4-vm21 collectd[22520]: File "/usr/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 310, in post#012    return self.request(url, 'POST', **kwargs)
Mar 10 20:06:15 scc2-4-vm21 collectd[22520]: File "/usr/lib/python2.7/site-packages/gnocchiclient/client.py", line 52, in request#012    raise exceptions.from_response(resp, method)
Mar 10 20:06:15 scc2-4-vm21 collectd[22520]: ClientException: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">#012<html><head>#012<title>500 Internal Server Error</title>#012</head><body>#012<h1>Internal Server Error</h1>#012<p>The server encountered an internal error or#012misconfiguration and was unable to complete#012your request.</p>#012<p>Please contact the server administrator at #012 root@localhost to inform them of the time this error occurred,#012 and the actions you performed just before this error.</p>#012<p>More information about this error may be available#012in the server error log.</p>#012</body></html>#012 (HTTP 500)
```
Where else can I look to debug this problem?

**Comment by fbattle** [comment]
I found an error in /var/log/httpd/error_log:
```
[Sat Mar 10 20:15:05.980312 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]   File "/usr/lib/python2.7/site-packages/concurrent/futures/_base.py", line 641, in result_iterator
[Sat Mar 10 20:15:05.980321 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]     yield fs.pop().result()
[Sat Mar 10 20:15:05.980326 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]   File "/usr/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
[Sat Mar 10 20:15:05.980335 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]     return self.__get_result()
[Sat Mar 10 20:15:05.980340 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]   File "/usr/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
[Sat Mar 10 20:15:05.980349 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]     result = self.fn(*self.args, **self.kwargs)
[Sat Mar 10 20:15:05.980354 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]   File "/usr/lib/python2.7/site-packages/gnocchi/utils.py", line 312, in <lambda>
[Sat Mar 10 20:15:05.980363 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]     return list(executor.map(lambda args: fn(*args), list_of_args))
[Sat Mar 10 20:15:05.980369 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]   File "/usr/lib/python2.7/site-packages/gnocchi/incoming/file.py", line 79, in _store_new_measures
[Sat Mar 10 20:15:05.980378 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]     delete=False)
[Sat Mar 10 20:15:05.980383 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]   File "/usr/lib64/python2.7/tempfile.py", line 458, in NamedTemporaryFile
[Sat Mar 10 20:15:05.980392 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]     (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
[Sat Mar 10 20:15:05.980402 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]   File "/usr/lib64/python2.7/tempfile.py", line 239, in _mkstemp_inner
[Sat Mar 10 20:15:05.980412 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]     fd = _os.open(file, flags, 0600)
[Sat Mar 10 20:15:05.980426 2018] [:error] [pid 22328] [remote 10.133.4.21:1168] OSError: [Errno 13] Permission denied: '/home/gnocchi/tmp/gnocchiMcc0Xe'
```
I'm surprised I'm still seeing this permission error, since /home/gnocchi was rebuilt by gnocchi-upgrade.

**Comment by jd** [comment]
We still don't know what user your Apache server uses to run the Gnocchi processes nor who owns the `/home/gnocchi` directory. You should check that they are the same.

**Comment by fbattle** [comment]
I found an error in /var/log/httpd/error_log:
```
[Sat Mar 10 20:15:05.980312 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]   File "/usr/lib/python2.7/site-packages/concurrent/futures/_base.py", line 641, in result_iterator
[Sat Mar 10 20:15:05.980321 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]     yield fs.pop().result()
[Sat Mar 10 20:15:05.980326 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]   File "/usr/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
[Sat Mar 10 20:15:05.980335 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]     return self.__get_result()
[Sat Mar 10 20:15:05.980340 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]   File "/usr/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
[Sat Mar 10 20:15:05.980349 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]     result = self.fn(*self.args, **self.kwargs)
[Sat Mar 10 20:15:05.980354 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]   File "/usr/lib/python2.7/site-packages/gnocchi/utils.py", line 312, in <lambda>
[Sat Mar 10 20:15:05.980363 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]     return list(executor.map(lambda args: fn(*args), list_of_args))
[Sat Mar 10 20:15:05.980369 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]   File "/usr/lib/python2.7/site-packages/gnocchi/incoming/file.py", line 79, in _store_new_measures
[Sat Mar 10 20:15:05.980378 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]     delete=False)
[Sat Mar 10 20:15:05.980383 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]   File "/usr/lib64/python2.7/tempfile.py", line 458, in NamedTemporaryFile
[Sat Mar 10 20:15:05.980392 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]     (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
[Sat Mar 10 20:15:05.980402 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]   File "/usr/lib64/python2.7/tempfile.py", line 239, in _mkstemp_inner
[Sat Mar 10 20:15:05.980412 2018] [:error] [pid 22328] [remote 10.133.4.21:1168]     fd = _os.open(file, flags, 0600)
[Sat Mar 10 20:15:05.980426 2018] [:error] [pid 22328] [remote 10.133.4.21:1168] OSError: [Errno 13] Permission denied: '/home/gnocchi/tmp/gnocchiMcc0Xe'
```
I'm surprised I'm still seeing this permission error, since /home/gnocchi was rebuilt by gnocchi-upgrade.

**Comment by fbattle** [comment]
1) After deleting /home/gnocchi and running gnocchi-upgrade, /home/gnocchi is created and ownership is root/root.

2) I'm using apache & mod_wsgi to run gnocchi-api, so I created /etc/httpd/conf.d/gnocchi-api.conf with the following contents:
```
<VirtualHost *:8041>
  WSGIDaemonProcess gnocchi user=gnocchi processes=4 threads=32 display-name=%{GROUP}
  WSGIProcessGroup gnocchi
  WSGIScriptAlias / /usr/bin/gnocchi-api
  WSGIPassAuthorization On
  WSGIApplicationGroup %{GLOBAL}

  <Directory />
      Require all granted
  </Directory>
</VirtualHost>
```
So I assume that means apache is configured to run the gnocchi processes as gnocchi/gnocchi.  Although seeing /home/gnocchi (and all files and dirs under it) as root/root tells me that is not happening.  Did I put my gnocchi-api.conf file in the wrong location?  I was not sure where to put the above WSGI directives.

3) I have another question concerning the gnocchi user.  When starting from a fresh OS image, do I need to create the gnocchi user or will the gnocchi installer or gnoochi-upgrade create that user?

**Comment by jd** [comment]
The fact that `/home/gnocchi` is owned by root/root is the source of the problem, as you said, Apache runs Gnocchi with the `gnocchi` user, so there's no way it'll be able to write in a directory that has a different owner.

It is your responsibility to provide a directory for Gnocchi with the correct permission. You have the solution right under your eyes: create a `/home/gnocchi` directory that is owned by gnocchi/gnocchi and run `gnocchi-upgrade` as the gnocchi user, not as root.

That also answer your question 3., Gnocchi does not create any user or play anything with permission. It's your job as the deployer to provide and user whatever user you want.

**Comment by fbattle** [comment]
Thank you Julien. I now have data!

-bash-4.2$ gnocchi measures show -r collectd:machine-name memory@memory-free
+---------------------------+-------------+--------------+
| timestamp                 | granularity |        value |
+---------------------------+-------------+--------------+
| 2018-03-12T23:45:00+00:00 |       300.0 | 1789186048.0 |
| 2018-03-12T23:50:00+00:00 |       300.0 | 1725214720.0 |
+---------------------------+-------------+--------------+
