### ISSUE TITLE
Needed explanation to scale Gnocchi

### ISSUE THREAD

**Issue by ramesh-chowdeshetty** [gnocchixyz/gnocchi#812]
Can somebody explain me how to scale gnocchi to coordinate the speed of apache kafka message broker.

kafka is processing 1 million datapoints in 1 sec. I would like to integrate kafka with gnocchi.
my expectation  is to push  1 millions datapoints into metric and retrieve same in 1 sec.

Which architecture i needs to follow........

**Comment by chungg** [comment]
i don't know how much we can help you here as this seems specific to your application/deployment.

my only suggestion is you *do not* push points individually. you should probably have a worker pull chunks of datapoints from kafka and push to gnocchi.
