### ISSUE TITLE
how to create sub metrics with dynamic aggregates

### ISSUE THREAD

**Issue by ramesh-chowdeshetty** [gnocchixyz/gnocchi#813]
I have created a metric to store minutes data.

How can i create sub metrics with aggregation like weekly,monthly,yearly,weekday(monday,tuesday,thursday,friday),moving mean,median,hourly (1AM,2AM,3AM,4AM).

**Comment by chungg** [comment]
https://gnocchi.xyz/rest.html#resample

although it won't work for for weekday (only daily)... there's also https://gnocchi.xyz/rest.html#rolling-window-aggregation to do moving aggregates.
