### ISSUE TITLE
Question regarding benchmarking

### ISSUE THREAD

**Issue by ayushmittal** [gnocchixyz/gnocchi#814]
Hey

I wanted to do a benchmark on gnocchi for my organisation. I was looking at the benchmarks you had posted on the blog, and was checking the source code of the gnocchiclient benchmark tool, and found out that it's mainly to either benchmark metric creation or measures creation for a particular metric. I would like to know if you have any suggestions on how we could create a tool which would basically simulate something like 1000 hosts sending lets say 100 metrics each with 10000 measures, or something like that.

Regards,
Ayush Mittal

**Comment by jd** [comment]
That should not be too hard to do. Do you want to test this sending via the REST API or would you like to test this by directly ingesting the data into Gnocchi?

**Comment by ayushmittal** [comment]
So basically the use case is that collectd would be sending to the gnocchi APIs, so I guess benchmarking using REST API would be better

**Comment by jd** [comment]
That should not be hard to implement using `gnocchiclient`. I'll mark this as a feature request for gnocchiclient: https://github.com/gnocchixyz/python-gnocchiclient/issues/82

**Comment by chungg** [comment]
just for reference, this is somewhat similar to my benchmark scenarios: https://www.slideshare.net/GordonChung/gnocchi-v4-past-and-present/#16

i basically tested 1K resources, 20metrics each and pushing 60 measures for each of the 20K metrics (batched in various ways)

**Comment by chungg** [comment]
i'll need to dig around. i switched jobs recently so i don't have access to my previous script.

i basically just generated a bunch of dummy data and tested it against https://gnocchi.xyz/rest.html#batch endpoint using `requests` library. then i just shifted the test data timestamps to generate each subsequent batch of data.

**Comment by ayushmittal** [comment]
Thanks for the information. I'll try that approach. :)
