### ISSUE TITLE
mysql indexer throws a lot of warnings in API

### ISSUE THREAD

**Issue by chungg** [gnocchixyz/gnocchi#847]
Before reporting an issue on Gnocchi, please be sure to provide all necessary
information.

### Which version of Gnocchi are you using

master

### How to reproduce your problem

run with mysql (or just look at ceilometer gate)

### What is the result that you get

gnocchi-api has a lot of logs similar to:

> Mar 21 23:48:05.359717 ubuntu-xenial-rax-iad-0003115279 devstack@gnocchi-api.service[13367]: 2018-03-21 23:48:05,358 [13370] WARNING  py.warnings: /usr/local/lib/python2.7/dist-packages/pymysql/cursors.py:165: Warning: (1300, u"Invalid utf8 character string: 'FB3351'")
> Mar 21 23:48:05.360008 ubuntu-xenial-rax-iad-0003115279 devstack@gnocchi-api.service[13367]:   result = self._query(query)

### What is result that you expected

they're just warnings... but they seem concerning.

**Comment by jd** [comment]
Isn't that something to do with oslo.db or SQLAlchemy itself?

**Comment by chungg** [comment]
i never looked into it.

**Comment by jd** [comment]
Warnings do not generate 503 errors. Don't mix things up @skinnyh.

**Comment by devfaz** [comment]
same here, running latest git-master-version 

`2018-06-28 09:55:40,815 [17] WARNING  py.warnings: /usr/local/lib/python2.7/dist-packages/pymysql/cursors.py:170: Warning: (1300, u"Invalid utf8 character string: 'BFBA64'")
  result = self._query(query)
`

**Comment by chungg** [comment]
maybe related to: https://github.com/PyMySQL/PyMySQL/blob/c51b47e3c6fa0d8b8090a6b25f7168ed68082dea/CHANGELOG#L7-L10

**Comment by jd** [comment]
Latest test run locally and in Travis shows no trace of this.

**Comment by weehal** [comment]
I have the same WARNINGS after migration from stable/4.0 to stable/4.2. 
But all this warnings come from gnocchi-api.

**Comment by skinnyh** [comment]
stable/4.2 still have those warnings if use PyMySQL==0.8.0. After downgrade PyMySQL to 0.7.x all the warnings are gone. Maybe we still need cap the version in gnocchi.
