### ISSUE TITLE
Numpy/Carbonara issue in compressing measures

### ISSUE THREAD

**Issue by ozerovandrei** [gnocchixyz/gnocchi#848]
Hi guys.

I've been running a Gnocchi cluster for 6-7 months (started from 3.x something).
I'm using Redis (3.2) for the incoming backend and Ceph (10.2.10 "Jewel") for the storage backend.

Right now I'm using the latest 4.2.2 Gnocchi release and for some reason I've started receiving tracebacks into the Metricd logs:
```
TypeError: ufunc subtract cannot use operands with types dtype('O') and dtype('<M8[ns]')
```
They're coming from this line: [carbonara.py#L709](https://github.com/gnocchixyz/gnocchi/blob/stable/4.2/gnocchi/carbonara.py#L709). Apparently, `self.first` returns `None`, because it catches the `IndexError` since `timestamps` list is empty for some reason.

I'm getting lots of those messages and unaggregated backlog started growing rapidly (I think because of that).

I have those archive policies:
```
+---------------------+---------------------------------------------------------------------------+
| Field               | Value                                                                     |
+---------------------+---------------------------------------------------------------------------+
| aggregation_methods | max, sum, min, mean                                                       |
| back_window         | 72                                                                        |
| definition          | - points: 9216, granularity: 0:05:00, timespan: 32 days, 0:00:00          |
|                     | - points: 2304, granularity: 1:00:00, timespan: 96 days, 0:00:00          |
|                     | - points: 1825, granularity: 1 day, 0:00:00, timespan: 1825 days, 0:00:00 |
| name                | instance_metrics                                                        |
+---------------------+---------------------------------------------------------------------------+
```
```
+---------------------+---------------------------------------------------------------------------+
| Field               | Value                                                                     |
+---------------------+---------------------------------------------------------------------------+
| aggregation_methods | max, min, mean                                                            |
| back_window         | 8769                                                                      |
| definition          | - points: 2016, granularity: 0:05:00, timespan: 7 days, 0:00:00           |
|                     | - points: 2160, granularity: 1:00:00, timespan: 90 days, 0:00:00          |
|                     | - points: 1825, granularity: 1 day, 0:00:00, timespan: 1825 days, 0:00:00 |
| name                | host_metrics                                                       |
+---------------------+---------------------------------------------------------------------------+
```
I have about 40k resources (about 130k metrics) for the first archive policy and about 1k amount of metrics for the second archive policy. All measures are coming from the Ceilometer every 5 minutes.
All those metrics have measures with different timestamps. Many of them are aggregated over 90 days.
I have the following Metricd options:
```
workers = 28
metric_processing_delay = 10
metric_reporting_delay = 30
metric_cleanup_delay = 60
worker_sync_rate = 25
processing_replicas = 2
greedy=False # I'm using it so Ceph storage backend won't over-utilize it's disks every second.
```

Can you please help me understand why this can happen?
It will be better also if Gnocchi can work with this error and doesn't throw a traceback. I still can see how new measures are saved (maybe because I have 84 Metricd workers) but backlog is still growing.

### Which version of Gnocchi are you using

Gnocchi version: 4.2.2

### How to reproduce your problem

Create about 100k metrics with timestamps over couple of months and aggregate them.

### What is the result that you get

Numpy can't substract `datetime64[ns]` from the `None` and throws an exception.

### What is result that you expected

Gnocchi is successfully compressing my measures that are aggregated for over couple of months. Or doesn't throw an exception and works better with this error.

**Comment by chungg** [comment]
want to see if the above patch fixes your issue? i think your issue is valid as in 4.2 we changed behaviour to truncate based on timespan vs. number of points.

**Comment by chungg** [comment]
hmmm. actually, would you know if the timeseries it's failing on was not capturing data for some period? ie, there's a timerange where it wasn't getting data every 5 min from ceilometer?

just asking because i don't want to be hiding a bigger error... in my mind, the above is the only scenario i can think of which can cause this issue.

**Comment by ozerovandrei** [comment]
@chungg thank you for the fix. It works!

About not capturing data. I've got some problems with the RabbitMQ cluster that Ceilometer uses to send samples from the Compute-agent to the Notification-agent. So some samples just got lost while I was fixing it (couple of times, I think).
Some metrics in Ceilometer are calculated by delta between current and previous measures. So losing samples for those measures is cirtical I guess.

**Comment by jd** [comment]
@chungg does this exist in master?

**Comment by chungg** [comment]
no, there is a check: https://github.com/gnocchixyz/gnocchi/blob/master/gnocchi/storage/__init__.py#L405

**Comment by ozerovandrei** [comment]
I'm closing it as it is working great.
Thank you for the quick fix.
