### ISSUE TITLE
Pushing measures to API is slowish

### ISSUE THREAD

**Issue by ayushmittal** [gnocchixyz/gnocchi#850]
Hey

**Architecture**

I have been evaluating gnocchi for our central metrics platform. The current evaluation setup is the following:

1 APId running on 16 cores with 16 uwsgi processes
1 Metricd running on 8 cores with 8 threads
1 postgres db instance

The incoming storage is redis and the Aggregated storage is on ceph with SSD based OSDs

The metrics collection is being done by collectd.

**Test Bench**

So for now i started getting metricd from around 20 hosts. Each sending it's own system level metrics as well as some metrics for its virtual machines. So in total around 700 resources are present. 

**Problems**

The problem I am facing is that the APId is consuming too many system resources. For just 700 hosts all the 16 cores are being completely utilised. This would mean that if we start getting data from 3000-4000 hosts we'll need way too many high end servers to support multiple APId and Metricd.

Is this an expected behaviour? Or can this be optimized more?
Or is there any flaw in the architecture that I am using?

**Comment by chungg** [comment]
what version are you using?

how many metrics per host are you collecting?

i don't know the collectd plugin works but the way ceilometer works is that it will buffer/batch metrics so it's pushing a group of datapoints at a time. this will minimise the number of reqs and minimise io from gnocchi.

i should also mention, that 8 threads for 1 metricd is not actually parallelism. it will still just write  in parallel but will still only be a single process working on metrics sequentially.

**Comment by ayushmittal** [comment]
Hey,

Thanks for the response.

> what version are you using?
4.2.1

> how many metrics per host are you collecting?
For 20 hosts around 1000 metrics each
For rest 600 hosts: 50 metrics each

> i should also mention, that 8 threads for 1 metricd is not actually parallelism. it will still just write in parallel but will still only be a single process working on metrics sequentially.

Umm I meant workers. So it's a 8 core cpu, so i'm running Metricd with 8 workers. Isn't that fine? Is there any better way of implementing this?

**Comment by chungg** [comment]
> For 20 hosts around 1000 metrics each
> For rest 600 hosts: 50 metrics each

so that's about ~50K metrics. do you know at what frequency you get data? at first look, this is probably expected as that is quite a bit of data for 16 processes... for reference, i would bench at 20K metrics with 18 API workers.

we do have https://github.com/gnocchixyz/gnocchi/issues/13 as our POST format is more verbose than it needs to be which could shrink CPU usage... that said, i don't know by how much.

i don't know what a typical HTTP server request/s is.  @jd also looked at switching web frameworks to something more performant but that work hasn't been started yet.

> Umm I meant workers. So it's a 8 core cpu, so i'm running Metricd with 8 workers. Isn't that fine? Is there any better way of implementing this?

that's fine. as long as your unaggregated backlog is being processed accordingly. just thought it was a single worker.

**Comment by jd** [comment]
There's also discussion to provide a better alternative to HTTP to push metrics. Would that help you too @ayushmittal ?

**Comment by ayushmittal** [comment]
@jd Umm anything which is supported by the collectd gnocchi plugin would definitely help

**Comment by jd** [comment]
@ayushmittal the collectd plugin only supports HTTP right now, but it could be changed.

The real question is do you need HTTP or could you use something else?

**Comment by ayushmittal** [comment]
@jd So we were using HTTP only because we are sending data from collectd. Anything faster can be used and would be of help. Basically that's kind of what i'm looking at right now also, if I could somehow get data from collectd and push it to gnocchi without the HTTP overheads.

**Comment by jd** [comment]
Sounds good to me. So this is similar to https://github.com/gnocchixyz/gnocchi/issues/496

In the meantime feel free to profile the REST API if you see any bottleneck there of course.

**Comment by tobias-urdin** [comment]
Closing, no new information in a long time.
