### ISSUE TITLE
gnocchi-execution-error-metricd.py

### ISSUE THREAD

**Issue by hyunchic86** [gnocchixyz/gnocchi#856]
Before reporting an issue on Gnocchi, please be sure to provide all necessary
information.

### Which version of Gnocchi are you using
master
### How to reproduce your problem
When i install gnocchi, it makes a error.

### What is the result that you get
error message is below :

gnocchi-metricd[21542]: Traceback (most recent call last):
 Apr 06 13:05:10 gnocchi-metricd[21542]: File "/opt/stack/devstack/src/gnocchi/gnocchi/cli/metricd.py", line 85, in run
 Apr 06 13:05:10 gnocchi-metricd[21542]: self._run_job()
 Apr 06 13:05:10 gnocchi-metricd[21542]: File "/opt/stack/devstack/src/gnocchi/gnocchi/cli/metricd.py", line 246, in _run_job
 Apr 06 13:05:10 gnocchi-metricd[21542]: LOG.debug("{1}", self.coord)
 Apr 06 13:05:10 gnocchi-metricd[21542]: AttributeError: 'RedisDriver' object has no attribute 'update_capabitilities'

### Solution 
Line 245 : 
        # Update statistics
        self.coord.update_capabitilities(self.GROUP_ID, self.statistics)
        if sacks == self._get_sacks_to_process():
            # We just did a full scan of all sacks, reset the timer

Change capabitilities  ---> capabilities

**Comment by hyunchic86** [comment]
I want to fix it. but when i push the modified code, i got permission denied message.

**Comment by chungg** [comment]
are you pushing to your fork?

**Comment by hyunchic86** [comment]
Today, i forked it and push it.  please check . i am not used to git.. :)

**Comment by chungg** [comment]
no worries. now you need to create a PR against your commit. click `new pull request` on https://github.com/gnocchixyz/gnocchi. if you don't see your branch, click `compare across forks` and then create pull request from there.

i saw you pushed to master so you'll want to select that. next time i suggest you create a new branch `git branch -B <branch_name>` and git commit/push that.

**Comment by hyunchic86** [comment]
is it merged?

**Comment by jd** [comment]
Not yet.

**Comment by hyunchic86** [comment]
can i add one more?

cuz i found another error at the same line.

**Comment by jd** [comment]
Just write it here.

**Comment by hyunchic86** [comment]
self.coord.update_capabilities(self.GROUP_ID, self.store.statistics)

it adds 'self.store.statistics' too

**Comment by jd** [comment]
I've updated the PR, thanks!
