### ISSUE TITLE
bulk GET metrics support

### ISSUE THREAD

**Issue by chungg** [gnocchixyz/gnocchi#87]
it'd be nice to be able to support retrieving multiple metrics at once if we want to minimise API requests. there are multiple dimensions we can do this on.

1. get all metrics for resource A
2. get all 'cpu_util' for all resources
3. get any metric on any resource

i think (1) makes sense, but do we need to consider the other two cases?  if just the first case, we can have a payload like {'cpu_util': [(time, value), ...], 'memory':  [(time, value), ...]}. if we need to handle cross resources, the payload would probably need another level for resource id (or we use metric_id, but i don't think that's a good idea).

**Comment by BigChief45** [comment]
I thought number 1 was already supported, but I cannot find it anywhere in the docs. I think this one would be a good starting point.

**Comment by BigChief45** [comment]
I think this can be closed now.
