### ISSUE TITLE
How to configure Gnocchi / Ceilometer

### ISSUE THREAD

**Issue by sbritton12345** [gnocchixyz/gnocchi#871]
Hello, This is probably more of a question than an issue so I apologize for posting it here but I think this is the only place where a question would get answered.   

I have Gnocchi/Ceilometer running in Devstack but I want to get some information in how to configure it to measure:

* object space usage (# files, GB)
* instances running (cpu, mem)
* volumes (GB)
* network traffic flow volume in/out 

I need to do this in order to figure out how to charge for Openstack resources being utilized.     This will be set up in a multi-company situation on Openstack.

I've read the documents but I just don't understand the logic behind this tool and how to configure it to get the information I need.

Thanks, 
Scott

### Which version of Gnocchi are you using
latest 

### How to reproduce your problem
install gnocchi using default procedures in devstack.

### What is the result that you get
I created a metric but not sure where to go from here.

**Comment by jd** [comment]
That sounds like a Ceilometer configuration issue. You probably want to check the doc at https://docs.openstack.org/ceilometer/latest/ or ask help on OpenStack community.
