### ISSUE TITLE
DevStack GNOCCHI_METRICD_PROCESSING_DELAY default value is too small

### ISSUE THREAD

**Issue by skinnyh** [gnocchixyz/gnocchi#884]
The default setting in code is every 5 seconds: https://github.com/gnocchixyz/gnocchi/blob/stable/4.2/devstack/settings#L14

According gnocchi document it should be 60s by default:
https://gnocchi.xyz/install.html#gnocchi-configuration-sample

Using 5 seconds is easily to have too many TCP connections in TIME_WAIT to index backend like MySQL and make other services fail to connect to the DB.

**Comment by chungg** [comment]
the devstack settings are for testing and not meant for production.

how many metricd workers and api workers do you have? asking in case we are creating too many connections based on workers.

**Comment by skinnyh** [comment]
I used 8 metricd workers and 4 api workers. When using with gnocchi_metricd_processing_delay=5, it generated about 20K TCP connections in TIME_WAIT and when I changed the delay to 60, the TIME_WAIT numbers dropped to 2K.

**Comment by skinnyh** [comment]
I didn't use coordination_url as I installed gnocchi in virtualenv in DevStack and had some issue to use Redis. Do you think running multiple workers without coordination enabled causes this issue? I'm using stable/4.0 version of gnocchi and tooz version is 1.48.2. Thanks.

**Comment by chungg** [comment]
@skinnyh if you don't define a coordintion_url it will use your SQL database as a locking mechanism which puts more requirements there.

you should try updating your tooz library. you are probably hitting: https://github.com/openstack/tooz/commit/ee66b6e4e416569cb8d51a9b19263c22c6e1f87d
or
https://github.com/openstack/tooz/commit/6e3f5ceb75f54fde1cef4b4596ea537c0aef2616

which require tooz >=1.57.2

**Comment by chungg** [comment]
closing as i'm assuming newer tooz fixes issue. please reopen if required.
