### ISSUE TITLE
Record (last) insertion time of measures

### ISSUE THREAD

**Issue by paramite** [gnocchixyz/gnocchi#889]
There is no way to list aggregates with time constraint. For example I cannot just list aggregates created within last hour or day. IMO this kind of feature is important for metrics DB.

**Comment by jd** [comment]
I don't understand what you mean @paramite. Can you be more explicit about what you would like to do?

**Comment by paramite** [comment]
Ok, so I roughly remember, that I wanted to use gnocchi CLI to list metrics aggregates saved in the DB in last hour (for example). Basically this RFE is about time based filter for listing records in Gnocchi. Does this answer your question?

**Comment by jd** [comment]
Yes it does. So that means Gnocchi would have to save the last insert time for each metric.

That's probably something that should be saved in the database for easy querying.

**Comment by jd** [comment]
I've retitled that as recording the last insertion time of measures. I don't think recording the insert time of all measures would be worth it, as it would be basically building a second timeseries inside the timeseries. :)

**Comment by paramite** [comment]
I think that you did not get the point. IMO you already have a time information saved in DB already. What is missing is possibility to query that information. Eg. CLI should understand following request and give me a data I need: "yo, gnocchi, give me a list of all aggregated measures of CPU load for last ten minutes" and gnocchi would tell me: "yo martin, CPU load was 0.5 minute ago, 0.6 two minutes ago, 1.0 three minutes ago, ... etc."

**Comment by chungg** [comment]
uh... like https://gnocchi.xyz/rest.html#time-range?

**Comment by paramite** [comment]
Ok great, that the API node exists for that. Can we have a support for it in CLI too?

**Comment by jd** [comment]
AFAIU that exists, it's: `gnocchi measures show <metric-id> --start "-10 minutes"`
