### ISSUE TITLE
Allow to use common time series frequencies when resampling, e.g. calendar month

### ISSUE THREAD

**Issue by scolinas** [gnocchixyz/gnocchi#890]
Hi,
It will be really useful to support common time series frequencies (https://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases) when resampling. Is it possible to add that feature to gnocchi?

**Comment by chungg** [comment]
starting work in #892. i don't plan to add all the offsets above... only those that i believe are groupings rather than just offsets to specific dates.

i should probably add support for quarterly and half year grouping as well now that i think about it.

**Comment by chungg** [comment]
closing this. i didn't add all possible groupings but we can open a new issue if we need something specific.
