### ISSUE TITLE
Support "server_group" for instance_network_interface metrics

### ISSUE THREAD

**Issue by hoangphuocbk** [gnocchixyz/gnocchi#906]
Currently, Gnocchi supports monitoring instance network metrics that only apply on one VM (https://github.com/pablobrunetti/Openstack-Multi-Node-Ceilometer-and-Gnocchi/blob/master/ceilometer/gnocchi_resources.yaml#L91).

That causes some problems when I want to apply scaling out/in a group of VMs. IMO, if Gnocchi can support attribute "server_group", that can apply to all VMs with same user metadata, it will be better.

I am trying scaling feature with gnocchi alarm using Heat. Thank Gnocchi team~

**Comment by jd** [comment]
Gnocchi does not monitor anything but just stores data.
Your problem seems to be around Ceilometer, Heat or the like. AFAIK Ceilometer creates instance resource type with server_group.
