### ISSUE TITLE
[Docs] Link to a Go client library

### ISSUE THREAD

**Issue by ozerovandrei** [gnocchixyz/gnocchi#926]
Hello.

Can we add a link to a open source Go library in the Gnocchi documentation?

There is a popular Go library to work with the different OpenStack API services: [Gophercloud](https://github.com/gophercloud/gophercloud).
I raised an issue to add a Gnocchi API v1 client implementation: [Gophercloud#698](https://github.com/gophercloud/gophercloud/issues/698). Unfortunately, maintainers of that project decided to allow me to implement such client in a separate repo (because Gnocchi is not an OpenStack project now).

So, currently it's implemented in [Gophercloud/utils](https://github.com/gophercloud/utils).

Right now it support the following API v1 requests:
 - Archive policies Create / Update / Delete / List / Get
 - Resources Create / Update / Delete / List / Get
 - Metrics Create / Delete / List / Get
 - Measures Create(via metric ID) / Batch(via metric IDs) / Batch(via resource IDs + metric names)

And following API v1 requests will be added in some near future:
 - Resource types Create / Update / Delete / List / Get
 - Archive policy rules Create / Update / Delete / List / Get

There is also a documentation with usage examples in the [godoc.org](https://godoc.org/github.com/gophercloud/utils).

**Comment by jd** [comment]
Sure, feel free to send a PR!

**Comment by ozerovandrei** [comment]
@jd thank you!
