### ISSUE TITLE
Grafana cannot connect gnocchi 

### ISSUE THREAD

**Issue by Shawnma1** [gnocchixyz/gnocchi#929]
### Which version of Gnocchi are you using
gnocchi 3.3.1
### How to reproduce your problem
I tried to install a grafana to view the openstack metric via gnocchi datasource, but after following the documents by google, I failed.

I am not sure what I am missing, I am appreciated if anyone can help.

Grafana is started with 5901 port on the same host with keystone and gnocchi, and has installed with gnocchixyz-gnocchi-datasource plugin.

CORS configuration is set in `keystone.conf` and `gnocchi.conf`
```ini
[cors]
allowed_origin = http://localhost:5901
```
PS: I also tried to use the ip to replace localhost, doesnt work either.

Grafana configration:
![image](https://user-images.githubusercontent.com/40825081/42271011-de597e58-7fb4-11e8-811b-13a3438a4b2c.png)

### What is the result that you get
Keystone failure: No response status code, is CORS correctly configured ?

### What is result that you expected
The datasource should be added successfully.

**Comment by jd** [comment]
> gnocchi 3.3.1

That does not exist. I imagine it's a client version, but that'd be a pretty old version anyway.

> after following the documents by google

I don't think Google provide any doc for Gnocchi. However, we do and we have a documentation here for Grafana: https://gnocchi.xyz/grafana.html

From the screenshot, I'd say your Keystone port is wrong, it should be `5000`.

Also be sure that `http://localhost:5901` is the URL that is shown in *your browser*. Otherwise that won't work.

**Comment by Shawnma1** [comment]
@jd 
For the gnocchi version, does it mean gnocchi client?
[root@X4221C ~]# gnocchi --version
gnocchi 3.3.1

I also tried to set 5000, but still not work, this is the gnocchi.conf I set
[keystone_authtoken]
auth_uri=http://10.113.77.93:5000/v3
auth_type=password
auth_version=v3
auth_url=http://10.113.77.93:35357
username=gnocchi
password=c848832648924f97
user_domain_name=Default
project_name=services
project_domain_name=Default


For grafana port, it can be access by browser on 5901, I know its default port is 3000

**Comment by jd** [comment]
Do Gnocchi work with the command line client? That'd be the first thing to test before using Grafana.

> For grafana port, it can be access by browser on 5901, I know its default port is 3000

That's not what I'm saying. I'm saying that you need to have `http://localhost:5901` in your browser URL location if you want CORS to work.

**Comment by Shawnma1** [comment]
@jd yes, gnocchi works fine with the command line, and can show metrics.
I also set http://grafanaip:5901 for CORS, definitely it can be accessed by browser.

I did not find any related logs for the request.

**Comment by sileht** [comment]
"Keystone failure: No response status code, is CORS correctly configured ?" can means:
* Keystone is unreachable from the network point of view.
* The url you enter in your brower to connect to Grafana is different from the one you put in "allowed_origin=" (they must be identique)

**Comment by Shawnma1** [comment]
@sileht thanks for your reply

Actually, keystone and grafana are deployed in the same host, and I believe the keystone is reachable on port 35357 and 5000, 
tcp6       0      0 :::35357                :::*                    LISTEN      439/httpd      
tcp6       0      0 :::5000                 :::*                    LISTEN      439/httpd        

And for grafana
[root@X4221C ~]# netstat -anp | grep 5901
tcp6       0      0 :::5901                 :::*                    LISTEN      10848/grafana-serve 

for cors of keystone and gnocchi:
allowed_origin = http://10.113.77.93:5901

![image](https://user-images.githubusercontent.com/40825081/42372996-415a152a-8146-11e8-9259-7802bd027840.png)

![image](https://user-images.githubusercontent.com/40825081/42373024-531d7f40-8146-11e8-82f3-dbb70473b620.png)

**Comment by Shawnma1** [comment]
keystone-paste.ini
[filter:cors]
use = egg:oslo.middleware#cors
oslo_config_project = keystone

do I miss something configure?
