### ISSUE TITLE
store timeseries csv file at a time in gnocchi

### ISSUE THREAD

**Issue by ramesh-chowdeshetty** [gnocchixyz/gnocchi#945]
i have a csv file which contains multiple columns with single timestamp. i have rest api which will read entire csv and push into gnocchi.
how to push a measure like {timestamp:2017-06-05 07:05:06,value:56,value:45,value:70} into a single metric.
If i create multiple metric then i have to call my rest api many times which is not feasible in production.
how can i achieve this in single request.

**Comment by sileht** [comment]
I have already answered here: https://github.com/gnocchixyz/gnocchi/issues/944#issuecomment-407770880
