### ISSUE TITLE
Travis based release is broken

### ISSUE THREAD

**Issue by jd** [gnocchixyz/gnocchi#949]
Pushing a tag on Travis does not work anymore. Nothing is pushed on PyPI.
Same for gnocchiclient.

**Comment by sileht** [comment]
It's a travis bug:
https://github.com/travis-ci/travis-ci/issues/9848
https://github.com/travis-ci/travis-ci/issues/9800
https://github.com/travis-ci/travis-ci/issues/9701
https://github.com/travis-ci/travis-ci/issues/9531
...

**Comment by chungg** [comment]
think this is resolved.
