### ISSUE TITLE
Clearing non-active resources

### ISSUE THREAD

**Issue by m0zart89** [gnocchixyz/gnocchi#961]
Gnocchi 3.0

Hello!

I keep openstack metrics in gnocchi storage. All is OK.
But gnocchi accumulates metrics of excess non-active resources ( of deleted instances for all time). How can I catch non-active resources without doing comparsion with active instances of my openstack.

**Comment by jd** [comment]
Non-active resources have a `ended_at` field set by Ceilometer to a timestamp value.
