### ISSUE TITLE
Unable to initialize redis driver 

### ISSUE THREAD

**Issue by GibeomOh** [gnocchixyz/gnocchi#966]
Hi, I am currently using an elasticsearch driver based on version 4.2.
I got an error while installing redis to compare performance with other drivers while upgrading to version 4.3 and upgrading the es driver.
There is no problem in version 4.2, but only in 4.3.
Please check the above problem.

### Which version of Gnocchi are you using
gnocchi-4.3.2.dev1

### How to reproduce your problem
After installing gnocchi 4.3 version, run gnocchi upgrade or start the process.

### What is the result that you get
I received an error from gnocchi.

```
ERROR    gnocchi.utils: Unable to initialize storage driver

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 279, in call
    result = fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/gnocchi-4.3.2.dev1-py2.7.egg/gnocchi/storage/__init__.py", line 102, in get_driver
    conf.storage)
  File "/usr/lib/python2.7/site-packages/gnocchi-4.3.2.dev1-py2.7.egg/gnocchi/storage/redis.py", line 56, in __init__
    self._client, self._scripts = redis.get_client(conf, self._SCRIPTS)
  File "/usr/lib/python2.7/site-packages/redis/client.py", line 992, in __getitem__
    raise KeyError(name)
KeyError: 0
```

### What is result that you expected
The error should not occur in the same way as in 4.2.

**Comment by sileht** [comment]
Can you add more detail about your redis setup ? redis version ? redis url you use in gnocchi.conf ?

Also the version show a modified version of Gnocchi, did you check with an unmodified version 4.3.2.

**Comment by GibeomOh** [comment]
I installed it via yum and make in CentOS 7 environment.
The redis version was tested in 2.9 and 4.0.
- redis_url = redis://10.xxx.xxx.xxx:26379?sentinel=mymaster&sentinel_fallback=10.xxx.xxx.xxx:26379&sentinel_fallback=10.xxx.xxx.xxx:26379
And redis setting also specified db.
 ex> mymaster&db=0

Also gnocchi is used the code in the stable/4.3 branch. And the code used is pure code that only clones and does not have an elasticsearch driver.

**Comment by GibeomOh** [comment]
If you set the redis store setting instead of using the redis centinel setting, it is no problem. Is my centinel setting wrong?

**Comment by jd** [comment]
Likely. The erro seems to indicate it can't find the database '0' which is the default one used by the Redis client. Did you check with `redis-cli`?

**Comment by GibeomOh** [comment]
There are databases from 0 to 15 in redis db. Maybe I think there is an error when the db0, would not have version 4.2 or if sentinel setting.
