### ISSUE TITLE
Support numpy clip

### ISSUE THREAD

**Issue by sorrison** [gnocchixyz/gnocchi#988]
Would be great to support the numpy clip operation. The only issue I see is that it is not like the other binary operators in that it can support a min and a max.

https://docs.scipy.org/doc/numpy/reference/generated/numpy.clip.html

Could have 2 operators clip_min and clip_max maybe that set the other argument to None. Or can gnocchi support something like:

(clip (operation) min max)

**Comment by vinaykns** [comment]
So in this context, is it mean to add a new aggregation method.? or doing this sort of operation while querying for the data.?

**Comment by chungg** [comment]
pretty sure it's a query operation. don't think it works as an aggregation method as it doesn't actually combine anything.

**Comment by vinaykns** [comment]
Yep, that's what I'm thinking too. Thank you.!

**Comment by sorrison** [comment]
Supporting the clip operation is a bit trickier than the other ones already supported. In our case we just wanted to support a max so I did this to get it working for us https://github.com/NeCTAR-RC/gnocchi/commit/00f688f2104089daa72454222b6faf7191bed4ac

Not the nicest way but did what we wanted

**Comment by chungg** [comment]
closing this as it was part of #1001
