### ISSUE TITLE
Unexpected behaviour when resampling with granularity = end - start

### ISSUE THREAD

**Issue by alakae** [gnocchixyz/gnocchi#997]
I am currently working with gnocchi version 4.1.4, since as of now we are unable to upgrade to the latest version due to some OpenStack cross-dependencies.  

Our use case is to identify the top most resource consuming instances. Therefore, I started to work out a solution based on [the example posted here](https://github.com/gnocchixyz/gnocchi/issues/465#issuecomment-342784617):

There @sileht wrote:
> Note that start - stop is exactly one week and we resample series to 1w too. This will ensure, each resulting series have only one point. 

which is exactly what I want to achieve as well.  However, if I run the following minimal working example:
```
start = datetime(2018, 10, 15, 1, 0)
end = datetime(2018, 10, 15, 23, 0)
delta = end - start
raw_result = gnocchi_client.aggregates.fetch(
        resource_type='instance',
        operations=[
            'resample',
            'max',
            "{}s".format(delta.seconds),
            [
                'metric',
                'cpu_util',
                'max'
            ]
        ],
        start=start,
        stop=end,
        groupby=['original_resource_id'],
        search=get_range_query(end, start)
    )
```

the resulting entries contain two elements in the `max` list, e.g.:
```
{
  'group':{
    'original_resource_id':'0ab6bc1b-d67c-4c84-a73a-7595f8afca7b'
  },
  'measures':{
    'measures':{
      '0ab6bc1b-d67c-4c84-a73a-7595f8afca7b':{
        'cpu_util':{
          'max':[
            (datetime.datetime(2018,10,14,4,0,tzinfo=datetime.timezone(datetime.timedelta(0),'+00:00')),79200.0,1.7204191457),
            (datetime.datetime(2018,10,15,2,0,tzinfo=datetime.timezone(datetime.timedelta(0),'+00:00')),79200.0,3.7629098805)
          ]
        }
      }
    }
  }
}
```
However, when I set`start = datetime(2018, 10, 15, 13, 0)` and `end = datetime(2018, 10, 15, 14, 0)` I get only one entry as I anticipated. Therefore, I have the feeling that it could be bug. But it could also be a misunderstanding on my side.

Thanks

**Comment by alakae** [comment]
> just curious but what is `get_range_query`?

It returns a search expression to find instances that exist within the given time window:
``` 
def get_range_query(filter_end, filter_start):
    return {
        "and": [
            {
                'le': {
                    "started_at": filter_end
                }
            },
            {
                "or": [
                    {
                        'ge': {
                            "ended_at": filter_start
                        }
                    },
                    {
                        '==': {
                            "ended_at": None
                        }
                    }
                ]
            },
        ]
    }
```

> i'd have to look into this it's possible it's because we time is aggregated relative to epoch so maybe 22hrs splits different? i'm completely guessing.

I think something like that could be a likely explanation. I investigated a bit more and made the following observation: 

duration 1h returns single value for intervals [0:00,1:00],[1:00,2:00],[2:00,3:00], etc.
duration 2h returns single value for intervals [0:00,2:00],[2:00,4:00],[4:00,6:00], etc.
duration 3h returns single value for intervals [0:00,3:00],[3:00,6:00],[6:00,9:00], etc.
duration 4h returns single value for intervals [0:00,4:00],[4:00,8:00],[8:00,12:00], etc.

**Comment by alakae** [comment]
> just curious but what is `get_range_query`?

It returns a search query to find instances that existed in the given time range:

```
def get_range_query(filter_end, filter_start):
    return {
        "and": [
            {
                'le': {
                    "started_at": filter_end
                }
            },
            {
                "or": [
                    {
                        'ge': {
                            "ended_at": filter_start
                        }
                    },
                    {
                        '==': {
                            "ended_at": None
                        }
                    }
                ]
            },
        ]
    }
```

> i'd have to look into this it's possible it's because we time is aggregated relative to epoch so maybe 22hrs splits different? i'm completely guessing.

That sounds like e very likely explanation to me.

**Comment by alakae** [comment]
> just curious but what is `get_range_query`?

It returns a search query to find instances that existed in the given time range:

```
def get_range_query(filter_end, filter_start):
    return {
        "and": [
            {
                'le': {
                    "started_at": filter_end
                }
            },
            {
                "or": [
                    {
                        'ge': {
                            "ended_at": filter_start
                        }
                    },
                    {
                        '==': {
                            "ended_at": None
                        }
                    }
                ]
            },
        ]
    }
```

> i'd have to look into this it's possible it's because we time is aggregated relative to epoch so maybe 22hrs splits different? i'm completely guessing.

That sounds like e very likely explanation to me.

**Comment by alakae** [comment]
> just curious but what is `get_range_query`?

It returns a search expression to find instances that exist within the given time window:
``` 
def get_range_query(filter_end, filter_start):
    return {
        "and": [
            {
                'le': {
                    "started_at": filter_end
                }
            },
            {
                "or": [
                    {
                        'ge': {
                            "ended_at": filter_start
                        }
                    },
                    {
                        '==': {
                            "ended_at": None
                        }
                    }
                ]
            },
        ]
    }
```

> i'd have to look into this it's possible it's because we time is aggregated relative to epoch so maybe 22hrs splits different? i'm completely guessing.

I think something like that could be a likely explanation. I investigated a bit more and made the following observation: 

duration 1h returns single value for intervals [0:00,1:00],[1:00,2:00],[2:00,3:00], etc.
duration 2h returns single value for intervals [0:00,2:00],[2:00,4:00],[4:00,6:00], etc.
duration 3h returns single value for intervals [0:00,3:00],[3:00,6:00],[6:00,9:00], etc.
duration 4h returns single value for intervals [0:00,4:00],[4:00,8:00],[8:00,12:00], etc.

**Comment by chungg** [comment]
hmmm maybe resample with `count` instead of `max`... you could see what the grouping is like.

not sure if this is reason but i don't think get_range_query should be `ge` and `le`. i would think it should not be inclusive on one end.

**Comment by chungg** [comment]
also, could you add what the archive policy is for the metrics are? are there multiple granularities?

**Comment by tobias-urdin** [comment]
Closing because of no new information, please update and we can open again.
