### ISSUE TITLE
Gnocchi and Ceilometer integration after deprecation changes

### ISSUE THREAD

**Issue by ntk148v** [gnocchixyz/gnocchi#999]
Before reporting an issue on Gnocchi, please be sure to provide all necessary
information.

*Disclaimer*: Idk is this the right place to ask the question. Hope it is.

### Which version of Gnocchi are you using

* Gnocchi: 4.3.1
* Ceilometer: Rocky.
* Aodh: Rocky.

### How to reproduce your problem

* `cpu_util` was computed wrongly and it makes Aodh alarms be wrong too.

* [Transformers and pipeline partitioning has been deprecated in Ceilometer](https://review.openstack.org/#/c/560854/), it means `cpu_util` will be unusable soon. In the commit message, @sileht wrote that "Also backend like Gnocchi offers a better alternative to compute them.". Is there any equivalent metric in Gnocchi? Or how to compute these metrics with Gnocchi?  Do we have any documentations about this change?

* If I have to compute metric using Gnocchi, how can I integrate with Aodh? Aodh just allows to get metric rather than compute it.

### What is result that you expected

Thanks in advice.

**Comment by hieulq** [comment]
just got the same problems between aodh, ceilometer (Rocky) with gnocchi after upgrading.

**Comment by sileht** [comment]
This is not a Gnocchi issue, but a support request for Ceilometer.

**Comment by sileht** [comment]
With new ceilometer, you can use the metric `cpu` with the aggregation `rate:mean`

**Comment by ntk148v** [comment]
> With new ceilometer, you can use the metric `cpu` with the aggregation `rate:mean`

Hi @sileht, thanks for your quick support. Unfortunately, Aodh still uses [depreacated Gnocchi Aggregation API](https://github.com/openstack/aodh/blob/master/aodh/evaluator/gnocchi.py#L140) which [doesn't support `rate:mean`](https://github.com/gnocchixyz/gnocchi/blob/master/gnocchi/rest/aggregates/operations.py#L26). 

How can I deal with it? I've tried a Dynamic Aggregates API: `operations='(/ (aggregate mean (metric cpu rate:mean)) 10e9)'`. But the result seems not correct, even when I did a stress test, none of them was above 50.

**Comment by dommgifer** [comment]
HI @ntk148v !
I have same issue.
Did you resolve how to aggregates cpu_util from cpu and vcpus?

**Comment by ntk148v** [comment]
Hi @dommgifer
Unfortunately, I try to deal with the issue but finally have to give up on it.
Switching to another approach to evaluate VM metrics is a better move for me, you might want to take a look at Prometheus openstack discovery.

**Comment by dommgifer** [comment]
HI @ntk148v 
Thank you for your advice .
I'll give it a try!
